load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.design-plugin",
    iml_files = ["intellij.android.design-plugin.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/adt/idea/designer:intellij.android.designer",
        "//tools/adt/idea/nav/editor:intellij.android.nav.editor",
        "//tools/adt/idea/nav/editor:intellij.android.nav.editor.gradle",
        "//tools/adt/idea/compose-designer:intellij.android.compose-designer",
        "//tools/adt/idea/designer/customview:intellij.android.designer.customview",
        "//tools/adt/idea/layoutlib:intellij.android.layoutlib",
        "//tools/adt/idea/glance-designer:intellij.android.glance-designer",
        "//tools/adt/idea/wear-designer:intellij.android.wear-designer",
        "//tools/adt/idea/design-plugin/descriptor:intellij.android.design-plugin.descriptor",
    ],
    # do not sort: must match IML order
    deps = ["//tools/adt/idea/.idea/libraries:layoutlib"],
)
