/*
 * Copyright 2025 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.idea.blaze.java.qsync

import com.android.SdkConstants
import com.google.idea.blaze.qsync.deps.JavaArtifactInfo
import com.intellij.psi.PsiFile
import java.nio.file.Path

/**
 * Finds java source files in jars generated by java_proto_library targets.
 */
class ClassFileSrcJarJavaSourceFinder(clsFile: PsiFile) : SourceFileInCompiledFileFinderBase(clsFile) {

  override fun filterSourcePaths(artifactInfo: JavaArtifactInfo): Sequence<Path> {
    val pathResolver = querySyncManager.assertProjectLoaded().projectPathResolver
    return artifactInfo.srcJars().asSequence()
      .map { pathResolver.resolve(it) }
      .filter { path ->
        val pathString = path.toString()
        pathString.endsWith(SdkConstants.DOT_JAR) || pathString.endsWith(SdkConstants.DOT_SRCJAR)
      }
  }
}