/*
 * Copyright 2025 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.idea.blaze.java.qsync;

import com.android.SdkConstants;
import com.google.idea.blaze.qsync.artifacts.BuildArtifact;
import com.google.idea.blaze.qsync.deps.ArtifactDirectories;
import com.google.idea.blaze.qsync.deps.JavaArtifactInfo;
import com.google.idea.blaze.qsync.project.ProjectPath;
import com.intellij.psi.PsiFile;
import java.nio.file.Path;
import java.util.stream.Stream;

/**
 * Finds java source files in jars generated by java_proto_library targets.
 */
public class ClassFileGenSrcJarJavaSourceFinder extends SourceFileInCompiledFileFinderBase {

  public ClassFileGenSrcJarJavaSourceFinder(PsiFile clsFile) {
    super(clsFile);
  }

  @Override
  Stream<Path> filterSourcePaths(JavaArtifactInfo artifactInfo) {
    return artifactInfo.genSrcs().stream()
      .map(BuildArtifact::artifactPath)
      .map(ArtifactDirectories.DEFAULT::resolveChild)
      .map(ProjectPath.ProjectRelativeProjectPath::relativePath)
      .map(projectPath::resolve)
      .filter(
        path ->
          (path.toString().endsWith(SdkConstants.DOT_JAR))
          || path.toString().endsWith(SdkConstants.DOT_SRCJAR));
  }
}
