package(default_visibility = ["//tools/adt/idea/aswb/base:__subpackages__"])

java_library(
    name = "test",
    srcs = glob(["*.java"]),
)

filegroup(
    name = "test_srcs",
    srcs = glob(["*.java"]),
)
