/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.uibuilder.property2.testutils

import com.android.tools.idea.uibuilder.property2.NelePropertyType

/**
 * This file has data from analyzing the framework code in P.
 * The result were incomplete such that a number of attributes
 * had to be remapped by hand (from the online documentation).
 *
 * This file is assumed to be the truth about the attribute
 * types used in the framework. Use this file to verify any
 * type mappings of android framework attributes.
 */
object AndroidAttributeFact {

  fun lookup(name: String): NelePropertyType {
    when (name) {
      // Material Design additions
      "boxStrokeErrorColor" -> return NelePropertyType.COLOR_STATE_LIST
      "boxStrokeWidthFocused" -> return NelePropertyType.DIMENSION
      "checkedChip" -> return NelePropertyType.ID
      "checkedIcon" -> return NelePropertyType.DRAWABLE
      "checkedIconEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "checkedIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "checkedIconVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "chipBackgroundColor" -> return NelePropertyType.COLOR_STATE_LIST
      "chipCornerRadius" -> return NelePropertyType.DIMENSION
      "chipEndPadding" -> return NelePropertyType.DIMENSION
      "chipIcon" -> return NelePropertyType.DRAWABLE
      "chipIconEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "chipIconSize" -> return NelePropertyType.DIMENSION
      "chipIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "chipIconVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "chipMinHeight" -> return NelePropertyType.DIMENSION
      "chipMinTouchTargetSize" -> return NelePropertyType.DIMENSION
      "chipSpacing" -> return NelePropertyType.DIMENSION
      "chipSpacingHorizontal" -> return NelePropertyType.DIMENSION
      "chipSpacingVertical" -> return NelePropertyType.DIMENSION
      "chipStartPadding" -> return NelePropertyType.DIMENSION
      "chipStrokeColor" -> return NelePropertyType.COLOR_STATE_LIST
      "chipStrokeWidth" -> return NelePropertyType.DIMENSION
      "chipSurfaceColor" -> return NelePropertyType.COLOR_STATE_LIST
      "closeIconEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "closeIconEndPadding" -> return NelePropertyType.DIMENSION
      "closeIconSize" -> return NelePropertyType.DIMENSION
      "closeIconStartPadding" -> return NelePropertyType.DIMENSION
      "closeIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "closeIconVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "cornerRadius" -> return NelePropertyType.DIMENSION
      "counterOverflowTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "counterTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "endIconCheckable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "endIconContentDescription" -> return NelePropertyType.STRING
      "endIconDrawable" -> return NelePropertyType.DRAWABLE
      "endIconMode" -> return NelePropertyType.ENUM
      "endIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "endIconTintMode" -> return NelePropertyType.ENUM
      "ensureMinTouchTargetSize" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "errorContentDescription" -> return NelePropertyType.STRING
      "errorIconDrawable" -> return NelePropertyType.DRAWABLE
      "errorIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "errorIconTintMode" -> return NelePropertyType.ENUM
      "errorTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "extendMotionSpec" -> return NelePropertyType.ANIMATOR
      "fabAlignmentMode" -> return NelePropertyType.ENUM
      "fabAnimationMode" -> return NelePropertyType.ENUM
      "fabCradleMargin" -> return NelePropertyType.DIMENSION
      "fabCradleRoundedCornerRadius" -> return NelePropertyType.DIMENSION
      "fabCradleVerticalOffset" -> return NelePropertyType.DIMENSION
      "haloColor" -> return NelePropertyType.COLOR_STATE_LIST
      "haloRadius" -> return NelePropertyType.DIMENSION
      "helperTextTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "hideOnScroll" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hintTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "iconEndPadding" -> return NelePropertyType.DIMENSION
      "iconStartPadding" -> return NelePropertyType.DIMENSION
      "iconGravity" -> return NelePropertyType.FLAGS
      "iconPadding" -> return NelePropertyType.DIMENSION
      "iconSize" -> return NelePropertyType.DIMENSION
      "insetBottom" -> return NelePropertyType.DIMENSION
      "insetLeft" -> return NelePropertyType.DIMENSION
      "insetRight" -> return NelePropertyType.DIMENSION
      "insetTop" -> return NelePropertyType.DIMENSION
      "itemMaxLines" -> return NelePropertyType.INTEGER
      "itemRippleColor" -> return NelePropertyType.COLOR_STATE_LIST
      "itemShapeAppearance" -> return NelePropertyType.STYLE
      "itemShapeAppearanceOverlay" -> return NelePropertyType.STYLE
      "itemShapeFillColor" -> return NelePropertyType.COLOR_STATE_LIST
      "itemShapeInsetBottom" -> return NelePropertyType.DIMENSION
      "itemShapeInsetEnd" -> return NelePropertyType.DIMENSION
      "itemShapeInsetStart" -> return NelePropertyType.DIMENSION
      "itemShapeInsetTop" -> return NelePropertyType.DIMENSION
      "itemSpacing" -> return NelePropertyType.DIMENSION
      "labelBehavior" -> return NelePropertyType.ENUM
      "labelStyle" -> return NelePropertyType.STYLE
      "layout_collapseMode" -> return NelePropertyType.ENUM
      "layout_collapseParallaxMultiplier" -> return NelePropertyType.FLOAT
      "layout_scrollFlags" -> return NelePropertyType.FLAGS
      "layout_scrollInterpolator" -> return NelePropertyType.INTERPOLATOR
      "liftOnScrollTargetViewId" -> return NelePropertyType.ID
      "lineSpacing" -> return NelePropertyType.DIMENSION
      "paddingBottomSystemWindowInsets" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "paddingLeftSystemWindowInsets" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "paddingRightSystemWindowInsets" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "placeholderText" -> return NelePropertyType.STRING
      "placeholderTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "placeholderTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "prefixText" -> return NelePropertyType.STRING
      "prefixTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "prefixTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "selectionRequired" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "shapeAppearance" -> return NelePropertyType.STYLE
      "shapeAppearanceOverlay" -> return NelePropertyType.STYLE
      "shrinkMotionSpec" -> return NelePropertyType.ANIMATOR
      "singleSelection" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "startIconCheckable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "startIconContentDescription" -> return NelePropertyType.STRING
      "startIconDrawable" -> return NelePropertyType.DRAWABLE
      "startIconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "startIconTintMode" -> return NelePropertyType.ENUM
      "statusBarForeground" -> return NelePropertyType.DRAWABLE
      "strokeColor" -> return NelePropertyType.COLOR_STATE_LIST
      "strokeWidth" -> return NelePropertyType.DIMENSION
      "suffixText" -> return NelePropertyType.STRING
      "suffixTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "suffixTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "tabBackground" -> return NelePropertyType.DRAWABLE
      "tabContentStart" -> return NelePropertyType.DIMENSION
      "tabGravity" -> return NelePropertyType.ENUM
      "tabIconTint" -> return NelePropertyType.DRAWABLE
      "tabIconTintMode" -> return NelePropertyType.ENUM
      "tabIndicator" -> return NelePropertyType.DRAWABLE
      "tabIndicatorAnimationDuration" -> return NelePropertyType.INTEGER
      "tabIndicatorColor" -> return NelePropertyType.COLOR
      "tabIndicatorFullWidth" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "tabIndicatorGravity" -> return NelePropertyType.ENUM
      "tabIndicatorHeight" -> return NelePropertyType.DIMENSION
      "tabInlineLabel" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "tabMaxWidth" -> return NelePropertyType.DIMENSION
      "tabMinWidth" -> return NelePropertyType.DIMENSION
      "tabMode" -> return NelePropertyType.ENUM
      "tabPadding" -> return NelePropertyType.DIMENSION
      "tabPaddingBottom" -> return NelePropertyType.DIMENSION
      "tabPaddingEnd" -> return NelePropertyType.DIMENSION
      "tabPaddingStart" -> return NelePropertyType.DIMENSION
      "tabPaddingTop" -> return NelePropertyType.DIMENSION
      "tabRippleColor" -> return NelePropertyType.COLOR
      "tabSelectedTextColor" -> return NelePropertyType.COLOR
      "tabTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "tabTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "tabUnboundedRipple" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "tickColor" -> return NelePropertyType.COLOR_STATE_LIST
      "tickColorActive" -> return NelePropertyType.COLOR_STATE_LIST
      "tickColorInactive" -> return NelePropertyType.COLOR_STATE_LIST
      "textEndPadding" -> return NelePropertyType.DIMENSION
      "textInputLayoutFocusedRectEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "textStartPadding" -> return NelePropertyType.DIMENSION
      "thumbColor" -> return NelePropertyType.COLOR_STATE_LIST
      "thumbElevation" -> return NelePropertyType.DIMENSION
      "thumbRadius" -> return NelePropertyType.DIMENSION
      "trackColor" -> return NelePropertyType.COLOR_STATE_LIST
      "trackColorActive" -> return NelePropertyType.COLOR_STATE_LIST
      "trackColorInactive" -> return NelePropertyType.COLOR_STATE_LIST
      "trackHeight" -> return NelePropertyType.DIMENSION
      "useMaterialThemeColors" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "expanded" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "liftOnScroll" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "insetForeground" -> return NelePropertyType.DRAWABLE
      "itemBackground" -> return NelePropertyType.DRAWABLE
      "itemHorizontalPadding" -> return NelePropertyType.DIMENSION
      "itemIconPadding" -> return NelePropertyType.DIMENSION
      "itemIconTint" -> return NelePropertyType.DRAWABLE
      "itemTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "itemTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "menu" -> return NelePropertyType.MENU
      "boxBackgroundColor" -> return NelePropertyType.COLOR
      "boxBackgroundMode" -> return NelePropertyType.ENUM
      "boxCollapsedPaddingTop" -> return NelePropertyType.DIMENSION
      "boxCornerRadiusBottomEnd" -> return NelePropertyType.DIMENSION
      "boxCornerRadiusBottomStart" -> return NelePropertyType.DIMENSION
      "boxCornerRadiusTopEnd" -> return NelePropertyType.DIMENSION
      "boxCornerRadiusTopStart" -> return NelePropertyType.DIMENSION
      "boxStrokeColor" -> return NelePropertyType.COLOR
      "boxStrokeWidth" -> return NelePropertyType.DIMENSION
      "counterEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "counterMaxLength" -> return NelePropertyType.INTEGER
      "counterOverflowTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "counterTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "errorEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "errorTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "helperText" -> return NelePropertyType.STRING
      "helperTextEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "helperTextTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "hintAnimationEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hintEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hintTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "passwordToggleContentDescription" -> return NelePropertyType.STRING
      "passwordToggleDrawable" -> return NelePropertyType.DRAWABLE
      "passwordToggleEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "passwordToggleTint" -> return NelePropertyType.COLOR_STATE_LIST
      "passwordToggleTintMode" -> return NelePropertyType.ENUM
      "itemHorizontalTranslationEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "itemIconSize" -> return NelePropertyType.DIMENSION
      "itemTextAppearanceActive" -> return NelePropertyType.TEXT_APPEARANCE
      "itemTextAppearanceInactive" -> return NelePropertyType.TEXT_APPEARANCE
      "labelVisibilityMode" -> return NelePropertyType.ENUM
      "borderWidth" -> return NelePropertyType.DIMENSION
      "fabCustomSize" -> return NelePropertyType.DIMENSION
      "fabSize" -> return NelePropertyType.ENUM
      "hideMotionSpec" -> return NelePropertyType.ANIM
      "hoveredFocusedTranslationZ" -> return NelePropertyType.DIMENSION
      "maxImageSize" -> return NelePropertyType.DIMENSION
      "pressedTranslationZ" -> return NelePropertyType.DIMENSION
      "rippleColor" -> return NelePropertyType.COLOR_STATE_LIST
      "showMotionSpec" -> return NelePropertyType.ANIM
      "useCompatPadding" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "collapsedTitleGravity" -> return NelePropertyType.FLAGS
      "collapsedTitleTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "contentScrim" -> return NelePropertyType.DRAWABLE
      "expandedTitleGravity" -> return NelePropertyType.FLAGS
      "expandedTitleMargin" -> return NelePropertyType.DIMENSION
      "expandedTitleMarginBottom" -> return NelePropertyType.DIMENSION
      "expandedTitleMarginEnd" -> return NelePropertyType.DIMENSION
      "expandedTitleMarginStart" -> return NelePropertyType.DIMENSION
      "expandedTitleMarginTop" -> return NelePropertyType.DIMENSION
      "expandedTitleTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "scrimAnimationDuration" -> return NelePropertyType.INTEGER
      "scrimVisibleHeightTrigger" -> return NelePropertyType.DIMENSION
      "statusBarScrim" -> return NelePropertyType.DRAWABLE
      "titleEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "toolbarId" -> return NelePropertyType.ID

      // RecyclerView additions
      "fastScrollHorizontalThumbDrawable" -> return NelePropertyType.DRAWABLE
      "fastScrollHorizontalTrackDrawable" -> return NelePropertyType.DRAWABLE
      "fastScrollVerticalThumbDrawable" -> return NelePropertyType.DRAWABLE
      "fastScrollVerticalTrackDrawable" -> return NelePropertyType.DRAWABLE
      "layoutManager" -> return NelePropertyType.STRING // actually a class name
      "reverseLayout" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "spanCount" -> return NelePropertyType.INTEGER
      "stackFromEnd" -> return NelePropertyType.THREE_STATE_BOOLEAN

      // ConstraintLayout additions
      "barrierAllowsGoneWidgets" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "barrierDirection" -> return NelePropertyType.ENUM
      "barrierMargin" -> return NelePropertyType.DIMENSION
      "chainUseRtl" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "constraintSet" -> return NelePropertyType.ID
      "constraint_referenced_ids" -> return NelePropertyType.STRING
      "flow_firstHorizontalBias" -> return NelePropertyType.FLOAT
      "flow_firstHorizontalStyle" -> return NelePropertyType.ENUM
      "flow_firstVerticalBias" -> return NelePropertyType.FLOAT
      "flow_firstVerticalStyle" -> return NelePropertyType.ENUM
      "flow_horizontalAlign" -> return NelePropertyType.FLOAT  // This should be ENUM, see b/168495397
      "flow_horizontalBias" -> return NelePropertyType.FLOAT
      "flow_horizontalGap" -> return NelePropertyType.DIMENSION
      "flow_horizontalStyle" -> return NelePropertyType.ENUM
      "flow_lastHorizontalBias" -> return NelePropertyType.FLOAT
      "flow_lastHorizontalStyle" -> return NelePropertyType.ENUM
      "flow_lastVerticalBias" -> return NelePropertyType.FLOAT
      "flow_lastVerticalStyle" -> return NelePropertyType.ENUM
      "flow_maxElementsWrap" -> return NelePropertyType.INTEGER
      "flow_verticalAlign" -> return NelePropertyType.ENUM
      "flow_verticalBias" -> return NelePropertyType.FLOAT
      "flow_verticalGap" -> return NelePropertyType.DIMENSION
      "flow_verticalStyle" -> return NelePropertyType.ENUM
      "flow_wrapMode" -> return NelePropertyType.ENUM
      "layout_constrainedHeight" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_constrainedWidth" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_constraintBaseline_creator" -> return NelePropertyType.INTEGER
      "layout_constraintBaseline_toBaselineOf" -> return NelePropertyType.ID
      "layout_constraintBottom_creator" -> return NelePropertyType.INTEGER
      "layout_constraintBottom_toBottomOf" -> return NelePropertyType.ID
      "layout_constraintBottom_toTopOf" -> return NelePropertyType.ID
      "layout_constraintCircle" -> return NelePropertyType.ID
      "layout_constraintCircleAngle" -> return NelePropertyType.INTEGER
      "layout_constraintCircleRadius" -> return NelePropertyType.DIMENSION
      "layout_constraintDimensionRatio" -> return NelePropertyType.STRING
      "layout_constraintEnd_toEndOf" -> return NelePropertyType.ID
      "layout_constraintEnd_toStartOf" -> return NelePropertyType.ID
      "layout_constraintGuide_begin" -> return NelePropertyType.DIMENSION
      "layout_constraintGuide_end" -> return NelePropertyType.DIMENSION
      "layout_constraintGuide_percent" -> return NelePropertyType.FRACTION
      "layout_constraintHeight_default" -> return NelePropertyType.ENUM
      "layout_constraintHeight_max" -> return NelePropertyType.DIMENSION
      "layout_constraintHeight_min" -> return NelePropertyType.DIMENSION
      "layout_constraintHeight_percent" -> return NelePropertyType.FRACTION
      "layout_constraintHorizontal_bias" -> return NelePropertyType.FRACTION
      "layout_constraintHorizontal_chainStyle" -> return NelePropertyType.ENUM
      "layout_constraintHorizontal_weight" -> return NelePropertyType.FLOAT
      "layout_constraintLeft_creator" -> return NelePropertyType.INTEGER
      "layout_constraintLeft_toLeftOf" -> return NelePropertyType.ID
      "layout_constraintLeft_toRightOf" -> return NelePropertyType.ID
      "layout_constraintRight_creator" -> return NelePropertyType.INTEGER
      "layout_constraintRight_toLeftOf" -> return NelePropertyType.ID
      "layout_constraintRight_toRightOf" -> return NelePropertyType.ID
      "layout_constraintStart_toEndOf" -> return NelePropertyType.ID
      "layout_constraintStart_toStartOf" -> return NelePropertyType.ID
      "layout_constraintTag" -> return NelePropertyType.STRING
      "layout_constraintTop_creator" -> return NelePropertyType.INTEGER
      "layout_constraintTop_toBottomOf" -> return NelePropertyType.ID
      "layout_constraintTop_toTopOf" -> return NelePropertyType.ID
      "layout_constraintVertical_bias" -> return NelePropertyType.FRACTION
      "layout_constraintVertical_chainStyle" -> return NelePropertyType.ENUM
      "layout_constraintVertical_weight" -> return NelePropertyType.FLOAT
      "layout_constraintWidth_default" -> return NelePropertyType.ENUM
      "layout_constraintWidth_max" -> return NelePropertyType.DIMENSION
      "layout_constraintWidth_min" -> return NelePropertyType.DIMENSION
      "layout_constraintWidth_percent" -> return NelePropertyType.FRACTION
      "layoutDescription" -> return NelePropertyType.XML
      "layout_editor_absoluteX" -> return NelePropertyType.DIMENSION
      "layout_editor_absoluteY" -> return NelePropertyType.DIMENSION
      "layout_goneMarginBottom" -> return NelePropertyType.DIMENSION
      "layout_goneMarginEnd" -> return NelePropertyType.DIMENSION
      "layout_goneMarginLeft" -> return NelePropertyType.DIMENSION
      "layout_goneMarginRight" -> return NelePropertyType.DIMENSION
      "layout_goneMarginStart" -> return NelePropertyType.DIMENSION
      "layout_goneMarginTop" -> return NelePropertyType.DIMENSION
      "layout_optimizationLevel" -> return NelePropertyType.FLAGS

      // AppCompat additions:
      "srcCompat" -> return NelePropertyType.DRAWABLE
      "drawableBottomCompat" -> return NelePropertyType.DRAWABLE
      "drawableEndCompat" -> return NelePropertyType.DRAWABLE
      "drawableLeftCompat" -> return NelePropertyType.DRAWABLE
      "drawableRightCompat" -> return NelePropertyType.DRAWABLE
      "drawableStartCompat" -> return NelePropertyType.DRAWABLE
      "drawableTopCompat" -> return NelePropertyType.DRAWABLE
      "titleMargins" -> return NelePropertyType.DIMENSION

      // tools attribute additions:
      "actionBarNavMode" -> return NelePropertyType.ENUM
      "context" -> return NelePropertyType.STRING
      "itemCount" -> return NelePropertyType.INTEGER
      "listfooter" -> return NelePropertyType.LAYOUT
      "listitem" -> return NelePropertyType.LAYOUT
      "listheader" -> return NelePropertyType.LAYOUT
      "showIn" -> return NelePropertyType.LAYOUT
      "targetApi" -> return NelePropertyType.STRING
      "viewBindingIgnore" -> return NelePropertyType.STRING

      // Hand edited overrides for framework attributes:
      "alignmentMode" -> return NelePropertyType.ENUM
      "amPmBackgroundColor" -> return NelePropertyType.COLOR_STATE_LIST
      "amPmTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "animationResolution" -> return NelePropertyType.INTEGER
      "autoLink" -> return NelePropertyType.FLAGS
      "autoSizePresetSizes" -> return NelePropertyType.ARRAY  // Dimension array
      "autoSizeTextType" -> return NelePropertyType.ENUM
      "backgroundTintMode" -> return NelePropertyType.ENUM
      "breakStrategy" -> return NelePropertyType.ENUM
      "bufferType" -> return NelePropertyType.ENUM
      "buttonGravity" -> return NelePropertyType.FLAGS
      "buttonTintMode" -> return NelePropertyType.ENUM
      "capitalize" -> return NelePropertyType.ENUM
      "calendarTextColor" -> return NelePropertyType.COLOR
      "checkMarkGravity" -> return NelePropertyType.FLAGS
      "checkMarkTintMode" -> return NelePropertyType.ENUM
      "choiceMode" -> return NelePropertyType.ENUM
      "commitIcon" -> return NelePropertyType.DRAWABLE
      "completionHintView" -> return NelePropertyType.LAYOUT
      "datePickerMode" -> return NelePropertyType.ENUM
      "dateTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "dayOfWeekBackground" -> return NelePropertyType.COLOR
      "dayOfWeekTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "descendantFocusability" -> return NelePropertyType.ENUM
      "drawableTintMode" -> return NelePropertyType.ENUM
      "drawingCacheQuality" -> return NelePropertyType.ENUM
      "ellipsize" -> return NelePropertyType.ENUM
      "fading" -> return NelePropertyType.FLAGS
      "fadingEdge" -> return NelePropertyType.FLAGS
      "fastScrollStyle" -> return NelePropertyType.STYLE
      "focusable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fontFamily" -> return NelePropertyType.FONT
      "foregroundGravity" -> return NelePropertyType.FLAGS
      "foregroundTintMode" -> return NelePropertyType.ENUM
      "gravity" -> return NelePropertyType.FLAGS
      "headerAmPmTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "headerMonthTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "headerDayOfMonthTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "headerTimeTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "headerYearTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "hyphenationFrequency" -> return NelePropertyType.ENUM
      "icon" -> return NelePropertyType.DRAWABLE
      "iconTintMode" -> return NelePropertyType.ENUM
      "ignoreGravity" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "imeOptions" -> return NelePropertyType.FLAGS
      "importantForAutofill" -> return NelePropertyType.FLAGS
      "importantForContentCapture" -> return NelePropertyType.FLAGS
      "inAnimation" -> return NelePropertyType.ANIM
      "indeterminateBehavior" -> return NelePropertyType.ENUM
      "indeterminateTintMode" -> return NelePropertyType.ENUM
      "inputType" -> return NelePropertyType.FLAGS
      "interpolator" -> return NelePropertyType.INTERPOLATOR
      "justificationMode" -> return NelePropertyType.ENUM
      "layout" -> return NelePropertyType.LAYOUT
      "layoutAnimation" -> return NelePropertyType.ANIM
      "layoutMode" -> return NelePropertyType.ENUM
      "layerType" -> return NelePropertyType.ENUM
      "layoutDirection" -> return NelePropertyType.ENUM
      "layout_gravity" -> return NelePropertyType.FLAGS
      "layout_height" -> return NelePropertyType.DIMENSION
      "layout_width" -> return NelePropertyType.DIMENSION
      "mode" -> return NelePropertyType.ENUM
      "monthTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "numeric" -> return NelePropertyType.FLAGS
      "orientation" -> return NelePropertyType.ENUM
      "outAnimation" -> return NelePropertyType.ANIM
      "outlineProvider" -> return NelePropertyType.ENUM
      "overScrollMode" -> return NelePropertyType.ENUM
      "persistentDrawingCache" -> return NelePropertyType.FLAGS
      "pointerIcon" -> return NelePropertyType.ENUM
      "popupTheme" -> return NelePropertyType.STYLE
      "progressTintMode" -> return NelePropertyType.ENUM
      "progressBackgroundTintMode" -> return NelePropertyType.ENUM
      "requiresFadingEdge" -> return NelePropertyType.FLAGS
      "secondaryProgressTintMode" -> return NelePropertyType.ENUM
      "scaleType" -> return NelePropertyType.ENUM
      "scrollbars" -> return NelePropertyType.FLAGS
      "scrollbarStyle" -> return NelePropertyType.ENUM
      "scrollIndicators" -> return NelePropertyType.FLAGS
      "showDividers" -> return NelePropertyType.FLAGS
      "spinnerMode" -> return NelePropertyType.ENUM
      "stateListAnimator" -> return NelePropertyType.ANIMATOR
      "stretchMode" -> return NelePropertyType.ENUM
      "subtitleTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "suggestionRowLayout" -> return NelePropertyType.LAYOUT
      "switchTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "textAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "textCursorDrawable" -> return NelePropertyType.DRAWABLE
      "textEditNoPasteWindowLayout" -> return NelePropertyType.LAYOUT
      "textEditPasteWindowLayout" -> return NelePropertyType.LAYOUT
      "textEditSideNoPasteWindowLayout" -> return NelePropertyType.LAYOUT
      "textEditSidePasteWindowLayout" -> return NelePropertyType.LAYOUT
      "textEditSuggestionItemLayout" -> return NelePropertyType.LAYOUT
      "textFontWeight" -> return NelePropertyType.INTEGER
      "textLocale" -> return NelePropertyType.STRING
      "textSelectHandle" -> return NelePropertyType.DRAWABLE
      "textSelectHandleLeft" -> return NelePropertyType.DRAWABLE
      "textSelectHandleRight" -> return NelePropertyType.DRAWABLE
      "textStyle" -> return NelePropertyType.FLAGS
      "theme" -> return NelePropertyType.STYLE
      "thumbTintMode" -> return NelePropertyType.ENUM
      "tickMarkTintMode" -> return NelePropertyType.ENUM
      "timePickerMode" -> return NelePropertyType.ENUM
      "tintMode" -> return NelePropertyType.ENUM
      "titleTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "trackTintMode" -> return NelePropertyType.ENUM
      "transcriptMode" -> return NelePropertyType.ENUM
      "typeface" -> return NelePropertyType.ENUM
      "verticalScrollbarPosition" -> return NelePropertyType.ENUM
      "visibility" -> return NelePropertyType.ENUM
      "weekDayTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "yearListItemTextAppearance" -> return NelePropertyType.TEXT_APPEARANCE
      "yearListSelectorColor" -> return NelePropertyType.COLOR

      // From generated file:
      "accessibilityEventTypes" -> return NelePropertyType.INTEGER
      "accessibilityFeedbackType" -> return NelePropertyType.INTEGER
      "accessibilityFlags" -> return NelePropertyType.INTEGER
      "accessibilityHeading" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "accessibilityLiveRegion" -> return NelePropertyType.INTEGER
      "accessibilityPaneTitle" -> return NelePropertyType.STRING
      "accessibilityTraversalAfter" -> return NelePropertyType.ID
      "accessibilityTraversalBefore" -> return NelePropertyType.ID
      "accountType" -> return NelePropertyType.STRING
      "action" -> return NelePropertyType.STRING
      "actionLayout" -> return NelePropertyType.ID
      "actionProviderClass" -> return NelePropertyType.STRING
      "actionViewClass" -> return NelePropertyType.STRING
      "activityOpenRemoteViewsEnterAnimation" -> return NelePropertyType.ID
      "addPrintersActivity" -> return NelePropertyType.STRING
      "addStatesFromChildren" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "adjustViewBounds" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "advancedPrintOptionsActivity" -> return NelePropertyType.STRING
      "allowBackup" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowClearUserData" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowEmbedded" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowParallelSyncs" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowSingleTap" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowTaskReparenting" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "allowUndo" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "alpha" -> return NelePropertyType.FLOAT
      "alphabeticModifiers" -> return NelePropertyType.INTEGER
      "alphabeticShortcut" -> return NelePropertyType.STRING
      "alwaysDrawnWithCache" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "alwaysFocusable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "alwaysRetainTaskState" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "ambientShadowAlpha" -> return NelePropertyType.FLOAT
      "animateFirstView" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "animateLayoutChanges" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "animateOnClick" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "animation" -> return NelePropertyType.ID
      "animationCache" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "animationDuration" -> return NelePropertyType.INTEGER
      "animationOrder" -> return NelePropertyType.INTEGER
      "anyDensity" -> return NelePropertyType.INTEGER
      "apduServiceBanner" -> return NelePropertyType.ID
      "appCategory" -> return NelePropertyType.INTEGER
      "appComponentFactory" -> return NelePropertyType.STRING
      "author" -> return NelePropertyType.ID
      "autoRemoveFromRecents" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "autoSizeMaxTextSize" -> return NelePropertyType.DIMENSION
      "autoSizeMinTextSize" -> return NelePropertyType.DIMENSION
      "autoSizeStepGranularity" -> return NelePropertyType.DIMENSION
      "autoStart" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "autoText" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "autoUrlDetect" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "autoVerify" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "autofillHints" -> return NelePropertyType.STRING
      "background" -> return NelePropertyType.DRAWABLE
      "backgroundDimAmount" -> return NelePropertyType.FLOAT
      "backgroundLeft" -> return NelePropertyType.ID
      "backgroundRight" -> return NelePropertyType.ID
      "backgroundTint" -> return NelePropertyType.COLOR_STATE_LIST
      "backupInForeground" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "banner" -> return NelePropertyType.ID
      "baseline" -> return NelePropertyType.DIMENSION
      "baselineAlignBottom" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "baselineAligned" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "baselineAlignedChildIndex" -> return NelePropertyType.INTEGER
      "bitmap" -> return NelePropertyType.ID
      "borderBottom" -> return NelePropertyType.DIMENSION
      "borderLeft" -> return NelePropertyType.DIMENSION
      "borderRight" -> return NelePropertyType.DIMENSION
      "borderTop" -> return NelePropertyType.DIMENSION
      "bottomOffset" -> return NelePropertyType.DIMENSION
      "button" -> return NelePropertyType.DRAWABLE
      "buttonTint" -> return NelePropertyType.COLOR_STATE_LIST
      "cacheColorHint" -> return NelePropertyType.COLOR
      "calendarViewMode" -> return NelePropertyType.INTEGER
      "calendarViewShown" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canControlMagnification" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canPerformGestures" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canRequestFilterKeyEvents" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canRequestFingerprintGestures" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canRequestTouchExplorationMode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "canRetrieveWindowContent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "cantSaveState" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "category" -> return NelePropertyType.STRING
      "centerColor" -> return NelePropertyType.COLOR
      "centerX" -> return NelePropertyType.FLOAT
      "centerY" -> return NelePropertyType.FLOAT
      "certDigest" -> return NelePropertyType.STRING
      "checkMark" -> return NelePropertyType.DRAWABLE
      "checkMarkTint" -> return NelePropertyType.COLOR_STATE_LIST
      "checkable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "checkableBehavior" -> return NelePropertyType.INTEGER
      "checked" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "checkedButton" -> return NelePropertyType.ID
      "childDivider" -> return NelePropertyType.DRAWABLE
      "childIndicator" -> return NelePropertyType.DRAWABLE
      "childIndicatorEnd" -> return NelePropertyType.DIMENSION
      "childIndicatorLeft" -> return NelePropertyType.DIMENSION
      "childIndicatorRight" -> return NelePropertyType.DIMENSION
      "childIndicatorStart" -> return NelePropertyType.DIMENSION
      "classLoader" -> return NelePropertyType.STRING
      "clearTaskOnLaunch" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "clickColor" -> return NelePropertyType.COLOR
      "clickable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "clipChildren" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "clipToPadding" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "closeIcon" -> return NelePropertyType.DRAWABLE
      "collapseColumns" -> return NelePropertyType.STRING
      "collapseContentDescription" -> return NelePropertyType.STRING
      "collapseIcon" -> return NelePropertyType.DRAWABLE
      "color" -> return NelePropertyType.COLOR
      "colorBackground" -> return NelePropertyType.COLOR
      "colorEdgeEffect" -> return NelePropertyType.COLOR
      "colorMode" -> return NelePropertyType.INTEGER
      "colorPrimary" -> return NelePropertyType.COLOR
      "columnCount" -> return NelePropertyType.INTEGER
      "columnOrderPreserved" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "columnWidth" -> return NelePropertyType.DIMENSION
      "compatibleWidthLimitDp" -> return NelePropertyType.INTEGER
      "compileSdkVersion" -> return NelePropertyType.INTEGER
      "completionHint" -> return NelePropertyType.STRING
      "completionThreshold" -> return NelePropertyType.INTEGER
      "configChanges" -> return NelePropertyType.INTEGER
      "content" -> return NelePropertyType.ID
      "contentAuthority" -> return NelePropertyType.STRING
      "contentDescription" -> return NelePropertyType.STRING
      "contentInsetEnd" -> return NelePropertyType.DIMENSION
      "contentInsetEndWithActions" -> return NelePropertyType.DIMENSION
      "contentInsetLeft" -> return NelePropertyType.DIMENSION
      "contentInsetRight" -> return NelePropertyType.DIMENSION
      "contentInsetStart" -> return NelePropertyType.DIMENSION
      "contentInsetStartWithNavigation" -> return NelePropertyType.DIMENSION
      "contextClickable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "contextDescription" -> return NelePropertyType.ID
      "contextUri" -> return NelePropertyType.ID
      "controlX1" -> return NelePropertyType.FLOAT
      "controlX2" -> return NelePropertyType.FLOAT
      "controlY1" -> return NelePropertyType.FLOAT
      "controlY2" -> return NelePropertyType.FLOAT
      "countDown" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "cropToPadding" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "cursorVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "cycles" -> return NelePropertyType.FLOAT
      "data" -> return NelePropertyType.STRING
      "daySelectorColor" -> return NelePropertyType.COLOR_STATE_LIST
      "debuggable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "defaultFocusHighlightEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "defaultHeight" -> return NelePropertyType.DIMENSION
      "defaultQueryHint" -> return NelePropertyType.STRING
      "defaultToDeviceProtectedStorage" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "defaultValue" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "defaultWidth" -> return NelePropertyType.DIMENSION
      "dependency" -> return NelePropertyType.STRING
      "detachWallpaper" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "dial" -> return NelePropertyType.DRAWABLE
      "dialogIcon" -> return NelePropertyType.DRAWABLE
      "dialogLayout" -> return NelePropertyType.ID
      "dialogMessage" -> return NelePropertyType.STRING
      "dialogMode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "dialogTitle" -> return NelePropertyType.STRING
      "digits" -> return NelePropertyType.STRING
      "directBootAware" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "direction" -> return NelePropertyType.INTEGER
      "directionPriority" -> return NelePropertyType.INTEGER
      "disableChildrenWhenDisabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "disableDependentsState" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "disabledAlpha" -> return NelePropertyType.FLOAT
      "divider" -> return NelePropertyType.DRAWABLE
      "dividerHeight" -> return NelePropertyType.DIMENSION
      "dividerPadding" -> return NelePropertyType.DIMENSION
      "documentLaunchMode" -> return NelePropertyType.INTEGER
      "drawSelectorOnTop" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "drawableAlpha" -> return NelePropertyType.INTEGER
      "drawableBottom" -> return NelePropertyType.DRAWABLE
      "drawableEnd" -> return NelePropertyType.DRAWABLE
      "drawableLeft" -> return NelePropertyType.DRAWABLE
      "drawablePadding" -> return NelePropertyType.DIMENSION
      "drawableRight" -> return NelePropertyType.DRAWABLE
      "drawableStart" -> return NelePropertyType.DRAWABLE
      "drawableTint" -> return NelePropertyType.COLOR_STATE_LIST
      "drawableTop" -> return NelePropertyType.DRAWABLE
      "dropDownAnchor" -> return NelePropertyType.ID
      "dropDownHeight" -> return NelePropertyType.DIMENSION
      "dropDownHorizontalOffset" -> return NelePropertyType.DIMENSION
      "dropDownSelector" -> return NelePropertyType.DRAWABLE
      "dropDownVerticalOffset" -> return NelePropertyType.DIMENSION
      "dropDownWidth" -> return NelePropertyType.DIMENSION
      "duplicateParentState" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "duration" -> return NelePropertyType.INTEGER
      "editable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "editorExtras" -> return NelePropertyType.ID
      "elegantTextHeight" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "elevation" -> return NelePropertyType.DIMENSION
      "ems" -> return NelePropertyType.INTEGER
      "enableVrMode" -> return NelePropertyType.STRING
      "enabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "endColor" -> return NelePropertyType.COLOR
      "endX" -> return NelePropertyType.FLOAT
      "endY" -> return NelePropertyType.FLOAT
      "endYear" -> return NelePropertyType.INTEGER
      "entries" -> return NelePropertyType.STRING_ARRAY
      "entryValues" -> return NelePropertyType.STRING_ARRAY
      "eventsInterceptionEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "excludeClass" -> return NelePropertyType.STRING
      "excludeFromRecents" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "excludeId" -> return NelePropertyType.ID
      "excludeName" -> return NelePropertyType.STRING
      "expandActivityOverflowButtonDrawable" -> return NelePropertyType.DRAWABLE
      "exported" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "externalRouteEnabledDrawable" -> return NelePropertyType.DRAWABLE
      "externalService" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "extraTension" -> return NelePropertyType.FLOAT
      "extractNativeLibs" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "factor" -> return NelePropertyType.FLOAT
      "fadeDuration" -> return NelePropertyType.INTEGER
      "fadeEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fadeOffset" -> return NelePropertyType.INTEGER
      "fadeScrollbars" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fadingEdgeLength" -> return NelePropertyType.DIMENSION
      "fadingMode" -> return NelePropertyType.INTEGER
      "fallbackLineSpacing" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fastScrollAlwaysVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fastScrollEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fillAfter" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fillBefore" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fillEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fillViewport" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "filterTouchesWhenObscured" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "finishOnCloseSystemDialogs" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "finishOnTaskLaunch" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "firstBaselineToTopHeight" -> return NelePropertyType.DIMENSION
      "firstDayOfWeek" -> return NelePropertyType.INTEGER
      "fitsSystemWindows" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "flipInterval" -> return NelePropertyType.INTEGER
      "focusableInTouchMode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "focusedByDefault" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "focusedMonthDateColor" -> return NelePropertyType.COLOR
      "font" -> return NelePropertyType.STRING
      "fontFeatureSettings" -> return NelePropertyType.STRING
      "fontProviderAuthority" -> return NelePropertyType.STRING
      "fontProviderCerts" -> return NelePropertyType.ID
      "fontProviderPackage" -> return NelePropertyType.STRING
      "fontProviderQuery" -> return NelePropertyType.STRING
      "fontStyle" -> return NelePropertyType.INTEGER
      "fontVariationSettings" -> return NelePropertyType.STRING
      "fontWeight" -> return NelePropertyType.INTEGER
      "footerDividersEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "forceDarkAllowed" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "forceHasOverlappingRendering" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "foreground" -> return NelePropertyType.DRAWABLE
      "foregroundInsidePadding" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "foregroundTint" -> return NelePropertyType.COLOR_STATE_LIST
      "format" -> return NelePropertyType.STRING
      "format12Hour" -> return NelePropertyType.STRING
      "format24Hour" -> return NelePropertyType.STRING
      "fraction" -> return NelePropertyType.FLOAT
      "fragment" -> return NelePropertyType.STRING
      "fragmentAllowEnterTransitionOverlap" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fragmentAllowReturnTransitionOverlap" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "freezesText" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "fromAlpha" -> return NelePropertyType.FLOAT
      "fromDegrees" -> return NelePropertyType.FLOAT
      "fromScene" -> return NelePropertyType.ID
      "fullBackupOnly" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "functionalTest" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "gestureColor" -> return NelePropertyType.COLOR
      "gestureStrokeAngleThreshold" -> return NelePropertyType.FLOAT
      "gestureStrokeLengthThreshold" -> return NelePropertyType.FLOAT
      "gestureStrokeSquarenessThreshold" -> return NelePropertyType.FLOAT
      "gestureStrokeType" -> return NelePropertyType.INTEGER
      "gestureStrokeWidth" -> return NelePropertyType.FLOAT
      "glEsVersion" -> return NelePropertyType.INTEGER
      "goIcon" -> return NelePropertyType.DRAWABLE
      "gradientRadius" -> return NelePropertyType.FLOAT
      "grantUriPermissions" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "groupIndicator" -> return NelePropertyType.DRAWABLE
      "hand_hour" -> return NelePropertyType.DRAWABLE
      "hand_minute" -> return NelePropertyType.DRAWABLE
      "handle" -> return NelePropertyType.ID
      "handleProfiling" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hapticFeedbackEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hardwareAccelerated" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hasCode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "headerBackground" -> return NelePropertyType.DRAWABLE
      "headerDividersEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "headerLayout" -> return NelePropertyType.LAYOUT
      "headerRemoveIconIfEmpty" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "headerTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "height" -> return NelePropertyType.DIMENSION
      "hideWheelUntilFocused" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "hint" -> return NelePropertyType.STRING
      "horizontalProgressLayout" -> return NelePropertyType.ID
      "horizontalSpacing" -> return NelePropertyType.DIMENSION
      "hotSpotX" -> return NelePropertyType.DIMENSION
      "hotSpotY" -> return NelePropertyType.DIMENSION
      "iconSpaceReserved" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "iconTint" -> return NelePropertyType.COLOR_STATE_LIST
      "iconifiedByDefault" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "id" -> return NelePropertyType.ID
      "imeActionId" -> return NelePropertyType.INTEGER
      "imeActionLabel" -> return NelePropertyType.STRING
      "imeFullscreenBackground" -> return NelePropertyType.DRAWABLE
      "immersive" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "importantForAccessibility" -> return NelePropertyType.INTEGER
      "includeFontPadding" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "includeInGlobalSearch" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "indeterminate" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "indeterminateDrawable" -> return NelePropertyType.DRAWABLE
      "indeterminateDuration" -> return NelePropertyType.INTEGER
      "indeterminateOnly" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "indeterminateTint" -> return NelePropertyType.COLOR_STATE_LIST
      "indicatorEnd" -> return NelePropertyType.DIMENSION
      "indicatorLeft" -> return NelePropertyType.DIMENSION
      "indicatorRight" -> return NelePropertyType.DIMENSION
      "indicatorStart" -> return NelePropertyType.DIMENSION
      "inflatedId" -> return NelePropertyType.ID
      "initOrder" -> return NelePropertyType.INTEGER
      "initialActivityCount" -> return NelePropertyType.INTEGER
      "inputMethod" -> return NelePropertyType.STRING
      "installLocation" -> return NelePropertyType.INTEGER
      "internalLayout" -> return NelePropertyType.ID
      "internalMaxHeight" -> return NelePropertyType.DIMENSION
      "internalMaxWidth" -> return NelePropertyType.DIMENSION
      "internalMinHeight" -> return NelePropertyType.DIMENSION
      "internalMinWidth" -> return NelePropertyType.DIMENSION
      "isAlwaysSyncable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isDefault" -> return NelePropertyType.ID
      "isGame" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isIndicator" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isScrollContainer" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isStatic" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isVrOnly" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isolatedProcess" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "isolatedSplits" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "itemColor" -> return NelePropertyType.COLOR
      "itemLayout" -> return NelePropertyType.ID
      "keepScreenOn" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "key" -> return NelePropertyType.STRING
      "keyBackground" -> return NelePropertyType.DRAWABLE
      "keyPreviewHeight" -> return NelePropertyType.DIMENSION
      "keyPreviewLayout" -> return NelePropertyType.ID
      "keyPreviewOffset" -> return NelePropertyType.DIMENSION
      "keyTextColor" -> return NelePropertyType.COLOR
      "keyTextSize" -> return NelePropertyType.DIMENSION
      "keyboardNavigationCluster" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "keycode" -> return NelePropertyType.INTEGER
      "killAfterRestore" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "label" -> return NelePropertyType.ID
      "labelFor" -> return NelePropertyType.ID
      "labelTextSize" -> return NelePropertyType.DIMENSION
      "largeHeap" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "largeScreens" -> return NelePropertyType.INTEGER
      "largestWidthLimitDp" -> return NelePropertyType.INTEGER
      "lastBaselineToBottomHeight" -> return NelePropertyType.DIMENSION
      "launchMode" -> return NelePropertyType.INTEGER
      "layout_above" -> return NelePropertyType.ID
      "layout_alignBaseline" -> return NelePropertyType.ID
      "layout_alignBottom" -> return NelePropertyType.ID
      "layout_alignEnd" -> return NelePropertyType.ID
      "layout_alignLeft" -> return NelePropertyType.ID
      "layout_alignParentBottom" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentEnd" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentLeft" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentRight" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentStart" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentTop" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_alignRight" -> return NelePropertyType.ID
      "layout_alignStart" -> return NelePropertyType.ID
      "layout_alignTop" -> return NelePropertyType.ID
      "layout_alignWithParentIfMissing" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_below" -> return NelePropertyType.ID
      "layout_centerHorizontal" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_centerInParent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_centerVertical" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_column" -> return NelePropertyType.INTEGER
      "layout_columnSpan" -> return NelePropertyType.INTEGER
      "layout_columnWeight" -> return NelePropertyType.FLOAT
      "layout_margin" -> return NelePropertyType.DIMENSION
      "layout_marginBottom" -> return NelePropertyType.DIMENSION
      "layout_marginEnd" -> return NelePropertyType.DIMENSION
      "layout_marginHorizontal" -> return NelePropertyType.DIMENSION
      "layout_marginLeft" -> return NelePropertyType.DIMENSION
      "layout_marginRight" -> return NelePropertyType.DIMENSION
      "layout_marginStart" -> return NelePropertyType.DIMENSION
      "layout_marginTop" -> return NelePropertyType.DIMENSION
      "layout_marginVertical" -> return NelePropertyType.DIMENSION
      "layout_removeBorders" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "layout_row" -> return NelePropertyType.INTEGER
      "layout_rowSpan" -> return NelePropertyType.INTEGER
      "layout_rowWeight" -> return NelePropertyType.FLOAT
      "layout_span" -> return NelePropertyType.INTEGER
      "layout_toEndOf" -> return NelePropertyType.ID
      "layout_toLeftOf" -> return NelePropertyType.ID
      "layout_toRightOf" -> return NelePropertyType.ID
      "layout_toStartOf" -> return NelePropertyType.ID
      "layout_weight" -> return NelePropertyType.FLOAT
      "layout_x" -> return NelePropertyType.DIMENSION
      "layout_y" -> return NelePropertyType.DIMENSION
      "legacyLayout" -> return NelePropertyType.ID
      "letterSpacing" -> return NelePropertyType.FLOAT
      "lightRadius" -> return NelePropertyType.DIMENSION
      "lightY" -> return NelePropertyType.DIMENSION
      "lightZ" -> return NelePropertyType.DIMENSION
      "lineHeight" -> return NelePropertyType.DIMENSION
      "lineSpacingExtra" -> return NelePropertyType.DIMENSION
      "lineSpacingMultiplier" -> return NelePropertyType.FLOAT
      "lines" -> return NelePropertyType.INTEGER
      "linksClickable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "listSelector" -> return NelePropertyType.DRAWABLE
      "lockTaskMode" -> return NelePropertyType.INTEGER
      "logo" -> return NelePropertyType.DRAWABLE
      "logoDescription" -> return NelePropertyType.STRING
      "longClickable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "loopViews" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "marqueeRepeatLimit" -> return NelePropertyType.INTEGER
      "matchOrder" -> return NelePropertyType.STRING
      "max" -> return NelePropertyType.INTEGER
      "maxAspectRatio" -> return NelePropertyType.FLOAT
      "maxButtonHeight" -> return NelePropertyType.DIMENSION
      "maxDate" -> return NelePropertyType.STRING
      "maxEms" -> return NelePropertyType.INTEGER
      "maxHeight" -> return NelePropertyType.DIMENSION
      "maxLength" -> return NelePropertyType.INTEGER
      "maxLines" -> return NelePropertyType.INTEGER
      "maxRecents" -> return NelePropertyType.INTEGER
      "maxWidth" -> return NelePropertyType.DIMENSION
      "maximumAngle" -> return NelePropertyType.FLOAT
      "measureAllChildren" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "measureWithLargestChild" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "mediaRouteTypes" -> return NelePropertyType.INTEGER
      "menuCategory" -> return NelePropertyType.INTEGER
      "mimeType" -> return NelePropertyType.STRING
      "min" -> return NelePropertyType.INTEGER
      "minDate" -> return NelePropertyType.STRING
      "minEms" -> return NelePropertyType.INTEGER
      "minHeight" -> return NelePropertyType.DIMENSION
      "minLines" -> return NelePropertyType.INTEGER
      "minWidth" -> return NelePropertyType.DIMENSION
      "minimumHorizontalAngle" -> return NelePropertyType.FLOAT
      "minimumVerticalAngle" -> return NelePropertyType.FLOAT
      "mirrorForRtl" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "multiArch" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "multiprocess" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "name" -> return NelePropertyType.STRING
      "navigationBarColor" -> return NelePropertyType.COLOR
      "navigationButtonStyle" -> return NelePropertyType.ID
      "navigationContentDescription" -> return NelePropertyType.STRING
      "navigationIcon" -> return NelePropertyType.DRAWABLE
      "negativeButtonText" -> return NelePropertyType.STRING
      "nestedScrollingEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "networkSecurityConfig" -> return NelePropertyType.ID
      "nextClusterForward" -> return NelePropertyType.ID
      "nextFocusDown" -> return NelePropertyType.ID
      "nextFocusForward" -> return NelePropertyType.ID
      "nextFocusLeft" -> return NelePropertyType.ID
      "nextFocusRight" -> return NelePropertyType.ID
      "nextFocusUp" -> return NelePropertyType.ID
      "noHistory" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "normalScreens" -> return NelePropertyType.INTEGER
      "notificationTimeout" -> return NelePropertyType.INTEGER
      "numColumns" -> return NelePropertyType.INTEGER
      "numStars" -> return NelePropertyType.INTEGER
      "numbersBackgroundColor" -> return NelePropertyType.COLOR
      "numbersInnerTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "numbersSelectorColor" -> return NelePropertyType.COLOR_STATE_LIST
      "numbersTextColor" -> return NelePropertyType.COLOR_STATE_LIST
      "numericModifiers" -> return NelePropertyType.INTEGER
      "numericShortcut" -> return NelePropertyType.STRING
      "offset" -> return NelePropertyType.FLOAT
      "onClick" -> return NelePropertyType.STRING
      "order" -> return NelePropertyType.INTEGER
      "orderInCategory" -> return NelePropertyType.INTEGER
      "ordering" -> return NelePropertyType.INTEGER
      "orderingFromXml" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "outlineAmbientShadowColor" -> return NelePropertyType.COLOR
      "outlineSpotShadowColor" -> return NelePropertyType.COLOR
      "overScrollFooter" -> return NelePropertyType.DRAWABLE
      "overScrollHeader" -> return NelePropertyType.DRAWABLE
      "overlapAnchor" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "packageNames" -> return NelePropertyType.STRING
      "padding" -> return NelePropertyType.DIMENSION
      "paddingBottom" -> return NelePropertyType.DIMENSION
      "paddingEnd" -> return NelePropertyType.DIMENSION
      "paddingHorizontal" -> return NelePropertyType.DIMENSION
      "paddingLeft" -> return NelePropertyType.DIMENSION
      "paddingRight" -> return NelePropertyType.DIMENSION
      "paddingStart" -> return NelePropertyType.DIMENSION
      "paddingTop" -> return NelePropertyType.DIMENSION
      "paddingVertical" -> return NelePropertyType.DIMENSION
      "password" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "pathData" -> return NelePropertyType.STRING
      "patternPathData" -> return NelePropertyType.STRING
      "permissionFlags" -> return NelePropertyType.INTEGER
      "permissionGroup" -> return NelePropertyType.STRING
      "permissionGroupFlags" -> return NelePropertyType.INTEGER
      "persistableMode" -> return NelePropertyType.INTEGER
      "persistent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "persistentWhenFeatureAvailable" -> return NelePropertyType.STRING
      "phoneNumber" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "popupAnimationStyle" -> return NelePropertyType.ID
      "popupBackground" -> return NelePropertyType.DRAWABLE
      "popupElevation" -> return NelePropertyType.DIMENSION
      "popupEnterTransition" -> return NelePropertyType.ID
      "popupExitTransition" -> return NelePropertyType.ID
      "popupLayout" -> return NelePropertyType.ID
      "position" -> return NelePropertyType.INTEGER
      "positiveButtonText" -> return NelePropertyType.STRING
      "priority" -> return NelePropertyType.INTEGER
      "privateImeOptions" -> return NelePropertyType.STRING
      "process" -> return NelePropertyType.STRING
      "progress" -> return NelePropertyType.INTEGER
      "progressBackgroundTint" -> return NelePropertyType.COLOR_STATE_LIST
      "progressDrawable" -> return NelePropertyType.DRAWABLE
      "progressLayout" -> return NelePropertyType.ID
      "progressTint" -> return NelePropertyType.COLOR_STATE_LIST
      "prompt" -> return NelePropertyType.STRING
      "propertyName" -> return NelePropertyType.STRING
      "propertyXName" -> return NelePropertyType.STRING
      "propertyYName" -> return NelePropertyType.STRING
      "protectionLevel" -> return NelePropertyType.INTEGER
      "queryActionMsg" -> return NelePropertyType.STRING
      "queryAfterZeroResults" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "queryBackground" -> return NelePropertyType.DRAWABLE
      "queryHint" -> return NelePropertyType.STRING
      "quickContactBadgeOverlay" -> return NelePropertyType.DRAWABLE
      "rating" -> return NelePropertyType.FLOAT
      "recognitionService" -> return NelePropertyType.STRING
      "recreateOnConfigChanges" -> return NelePropertyType.INTEGER
      "recycleEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "relinquishTaskIdentity" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "reparent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "reparentWithOverlay" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "repeatCount" -> return NelePropertyType.INTEGER
      "repeatMode" -> return NelePropertyType.INTEGER
      "reqFiveWayNav" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "reqHardKeyboard" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "reqKeyboardType" -> return NelePropertyType.INTEGER
      "reqNavigation" -> return NelePropertyType.INTEGER
      "reqTouchScreen" -> return NelePropertyType.INTEGER
      "request" -> return NelePropertyType.ID
      "requireDeviceUnlock" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "required" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "requiredAccountType" -> return NelePropertyType.STRING
      "requiredForAllUsers" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "requiredSystemPropertyName" -> return NelePropertyType.STRING
      "requiredSystemPropertyValue" -> return NelePropertyType.STRING
      "requiresSmallestWidthDp" -> return NelePropertyType.INTEGER
      "resOutColor" -> return NelePropertyType.COLOR
      "resizeClip" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "resizeable" -> return NelePropertyType.INTEGER
      "resizeableActivity" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "restoreAnyVersion" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "restrictedAccountType" -> return NelePropertyType.STRING
      "restrictionType" -> return NelePropertyType.INTEGER
      "resumeWhilePausing" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "revisionCode" -> return NelePropertyType.INTEGER
      "ringtoneType" -> return NelePropertyType.INTEGER
      "rotation" -> return NelePropertyType.FLOAT
      "rotationAnimation" -> return NelePropertyType.INTEGER
      "rotationX" -> return NelePropertyType.FLOAT
      "rotationY" -> return NelePropertyType.FLOAT
      "roundIcon" -> return NelePropertyType.ID
      "rowCount" -> return NelePropertyType.INTEGER
      "rowOrderPreserved" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "saveEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "scaleX" -> return NelePropertyType.FLOAT
      "scaleY" -> return NelePropertyType.FLOAT
      "screenLayout" -> return NelePropertyType.ID
      "screenOrientation" -> return NelePropertyType.INTEGER
      "screenReaderFocusable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "scrollHorizontally" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "scrollX" -> return NelePropertyType.DIMENSION
      "scrollY" -> return NelePropertyType.DIMENSION
      "scrollbarAlwaysDrawHorizontalTrack" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "scrollbarAlwaysDrawVerticalTrack" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "scrollbarDefaultDelayBeforeFade" -> return NelePropertyType.INTEGER
      "scrollbarFadeDuration" -> return NelePropertyType.INTEGER
      "scrollbarSize" -> return NelePropertyType.DIMENSION
      "scrollbarThumbHorizontal" -> return NelePropertyType.DRAWABLE
      "scrollbarThumbVertical" -> return NelePropertyType.DRAWABLE
      "scrollbarTrackHorizontal" -> return NelePropertyType.DRAWABLE
      "scrollbarTrackVertical" -> return NelePropertyType.DRAWABLE
      "scrollingCache" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "searchButtonText" -> return NelePropertyType.ID
      "searchHintIcon" -> return NelePropertyType.DRAWABLE
      "searchIcon" -> return NelePropertyType.DRAWABLE
      "searchKeyphrase" -> return NelePropertyType.STRING
      "searchKeyphraseId" -> return NelePropertyType.INTEGER
      "searchKeyphraseRecognitionFlags" -> return NelePropertyType.INTEGER
      "searchKeyphraseSupportedLocales" -> return NelePropertyType.STRING
      "searchMode" -> return NelePropertyType.INTEGER
      "searchSettingsDescription" -> return NelePropertyType.ID
      "searchSuggestAuthority" -> return NelePropertyType.STRING
      "searchSuggestIntentAction" -> return NelePropertyType.STRING
      "searchSuggestIntentData" -> return NelePropertyType.STRING
      "searchSuggestPath" -> return NelePropertyType.STRING
      "searchSuggestSelection" -> return NelePropertyType.STRING
      "searchSuggestThreshold" -> return NelePropertyType.INTEGER
      "secondaryProgress" -> return NelePropertyType.INTEGER
      "secondaryProgressTint" -> return NelePropertyType.COLOR_STATE_LIST
      "selectAllOnFocus" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "selectable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "selectedDateVerticalBar" -> return NelePropertyType.DRAWABLE
      "selectedWeekBackgroundColor" -> return NelePropertyType.COLOR
      "selectionDivider" -> return NelePropertyType.DRAWABLE
      "selectionDividerHeight" -> return NelePropertyType.DIMENSION
      "selectionDividersDistance" -> return NelePropertyType.DIMENSION
      "sessionService" -> return NelePropertyType.STRING
      "settingsActivity" -> return NelePropertyType.STRING
      "shadowColor" -> return NelePropertyType.COLOR
      "shadowDx" -> return NelePropertyType.FLOAT
      "shadowDy" -> return NelePropertyType.FLOAT
      "shadowRadius" -> return NelePropertyType.FLOAT
      "shareInterpolator" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "sharedUserLabel" -> return NelePropertyType.ID
      "shouldDisableView" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showAsAction" -> return NelePropertyType.INTEGER
      "showDefault" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showForAllUsers" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showMetadataInPreview" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showOnLockScreen" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showSilent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showText" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showWeekNumber" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "showWhenLocked" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "shownWeekCount" -> return NelePropertyType.INTEGER
      "shrinkColumns" -> return NelePropertyType.STRING
      "singleLine" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "singleLineTitle" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "singleUser" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "slideEdge" -> return NelePropertyType.INTEGER
      "smallScreens" -> return NelePropertyType.INTEGER
      "smoothScrollbar" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "solidColor" -> return NelePropertyType.COLOR
      "soundEffectsEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "spacing" -> return NelePropertyType.DIMENSION
      "spinnersShown" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "splitMotionEvents" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "splitTrack" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "spotShadowAlpha" -> return NelePropertyType.FLOAT
      "src" -> return NelePropertyType.DRAWABLE
      "stackFromBottom" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "startColor" -> return NelePropertyType.COLOR
      "startDelay" -> return NelePropertyType.INTEGER
      "startOffset" -> return NelePropertyType.INTEGER
      "startX" -> return NelePropertyType.FLOAT
      "startY" -> return NelePropertyType.FLOAT
      "startYear" -> return NelePropertyType.INTEGER
      "stateNotNeeded" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "statusBarColor" -> return NelePropertyType.COLOR
      "stepSize" -> return NelePropertyType.FLOAT
      "stopWithTask" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "streamType" -> return NelePropertyType.INTEGER
      "stretchColumns" -> return NelePropertyType.STRING
      "submitBackground" -> return NelePropertyType.DRAWABLE
      "subtitle" -> return NelePropertyType.STRING
      "subtitleTextColor" -> return NelePropertyType.COLOR
      "suggestActionMsg" -> return NelePropertyType.STRING
      "suggestActionMsgColumn" -> return NelePropertyType.STRING
      "summary" -> return NelePropertyType.STRING
      "summaryOff" -> return NelePropertyType.STRING
      "summaryOn" -> return NelePropertyType.STRING
      "supportsAmbientMode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsAssist" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsLaunchVoiceAssistFromKeyguard" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsLocalInteraction" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsPictureInPicture" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsRtl" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsSwitchingToNextInputMethod" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "supportsUploading" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "switchMinWidth" -> return NelePropertyType.DIMENSION
      "switchPadding" -> return NelePropertyType.DIMENSION
      "switchTextOff" -> return NelePropertyType.STRING
      "switchTextOn" -> return NelePropertyType.STRING
      "syncable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "systemUserOnly" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "tabLayout" -> return NelePropertyType.ID
      "tabStripEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "tabStripLeft" -> return NelePropertyType.DRAWABLE
      "tabStripRight" -> return NelePropertyType.DRAWABLE
      "tag" -> return NelePropertyType.STRING
      "targetClass" -> return NelePropertyType.STRING
      "targetId" -> return NelePropertyType.ID
      "targetName" -> return NelePropertyType.STRING
      "targetPackage" -> return NelePropertyType.STRING
      "targetProcesses" -> return NelePropertyType.STRING
      "targetSandboxVersion" -> return NelePropertyType.INTEGER
      "taskAffinity" -> return NelePropertyType.STRING
      "tension" -> return NelePropertyType.FLOAT
      "testOnly" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "text" -> return NelePropertyType.STRING
      "textAlignment" -> return NelePropertyType.INTEGER
      "textAllCaps" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "textColor" -> return NelePropertyType.COLOR_STATE_LIST
      "textColorHighlight" -> return NelePropertyType.COLOR
      "textColorHint" -> return NelePropertyType.COLOR_STATE_LIST
      "textColorLink" -> return NelePropertyType.COLOR_STATE_LIST
      "textDirection" -> return NelePropertyType.INTEGER
      "textEditSuggestionContainerLayout" -> return NelePropertyType.ID
      "textEditSuggestionHighlightStyle" -> return NelePropertyType.ID
      "textFilterEnabled" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "textIsSelectable" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "textOff" -> return NelePropertyType.STRING
      "textOn" -> return NelePropertyType.STRING
      "textScaleX" -> return NelePropertyType.FLOAT
      "textSize" -> return NelePropertyType.DIMENSION
      "textUnderlineColor" -> return NelePropertyType.COLOR
      "textUnderlineThickness" -> return NelePropertyType.DIMENSION
      "thumb" -> return NelePropertyType.DRAWABLE
      "thumbDrawable" -> return NelePropertyType.DRAWABLE
      "thumbMinHeight" -> return NelePropertyType.DIMENSION
      "thumbMinWidth" -> return NelePropertyType.DIMENSION
      "thumbOffset" -> return NelePropertyType.DIMENSION
      "thumbPosition" -> return NelePropertyType.INTEGER
      "thumbTextPadding" -> return NelePropertyType.DIMENSION
      "thumbTint" -> return NelePropertyType.COLOR_STATE_LIST
      "thumbnail" -> return NelePropertyType.ID
      "tickMark" -> return NelePropertyType.DRAWABLE
      "tickMarkTint" -> return NelePropertyType.COLOR_STATE_LIST
      "tileMode" -> return NelePropertyType.INTEGER
      "timeZone" -> return NelePropertyType.STRING
      "tint" -> return NelePropertyType.COLOR_STATE_LIST
      "title" -> return NelePropertyType.STRING
      "titleCondensed" -> return NelePropertyType.STRING
      "titleMargin" -> return NelePropertyType.DIMENSION
      "titleMarginBottom" -> return NelePropertyType.DIMENSION
      "titleMarginEnd" -> return NelePropertyType.DIMENSION
      "titleMarginStart" -> return NelePropertyType.DIMENSION
      "titleMarginTop" -> return NelePropertyType.DIMENSION
      "titleTextColor" -> return NelePropertyType.COLOR
      "toAlpha" -> return NelePropertyType.FLOAT
      "toDegrees" -> return NelePropertyType.FLOAT
      "toScene" -> return NelePropertyType.ID
      "tooltipText" -> return NelePropertyType.STRING
      "topOffset" -> return NelePropertyType.DIMENSION
      "touchscreenBlocksFocus" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "track" -> return NelePropertyType.DRAWABLE
      "trackDrawable" -> return NelePropertyType.DRAWABLE
      "trackTint" -> return NelePropertyType.COLOR_STATE_LIST
      "transformPivotX" -> return NelePropertyType.DIMENSION
      "transformPivotY" -> return NelePropertyType.DIMENSION
      "transition" -> return NelePropertyType.ID
      "transitionGroup" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "transitionName" -> return NelePropertyType.STRING
      "transitionOrdering" -> return NelePropertyType.INTEGER
      "transitionVisibilityMode" -> return NelePropertyType.INTEGER
      "translationX" -> return NelePropertyType.DIMENSION
      "translationY" -> return NelePropertyType.DIMENSION
      "translationZ" -> return NelePropertyType.DIMENSION
      "ttcIndex" -> return NelePropertyType.INTEGER
      "turnScreenOn" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "type" -> return NelePropertyType.INTEGER
      "uiOptions" -> return NelePropertyType.INTEGER
      "uncertainGestureColor" -> return NelePropertyType.COLOR
      "unfocusedMonthDateColor" -> return NelePropertyType.COLOR
      "unselectedAlpha" -> return NelePropertyType.FLOAT
      "useDefaultMargins" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "useDisabledAlpha" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "userVisible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "usesCleartextTraffic" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "value" -> return NelePropertyType.FLOAT
      "values" -> return NelePropertyType.ARRAY  // array of float for com.google.android.material.slider.RangeSlider
      "valueFrom" -> return NelePropertyType.FLOAT
      "valueTo" -> return NelePropertyType.FLOAT
      "valueType" -> return NelePropertyType.INTEGER
      "version" -> return NelePropertyType.INTEGER
      "versionCode" -> return NelePropertyType.INTEGER
      "versionCodeMajor" -> return NelePropertyType.INTEGER
      "versionMajor" -> return NelePropertyType.INTEGER
      "verticalCorrection" -> return NelePropertyType.DIMENSION
      "verticalSpacing" -> return NelePropertyType.DIMENSION
      "virtualButtonPressedDrawable" -> return NelePropertyType.DRAWABLE
      "visible" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "visibleToInstantApps" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "vmSafeMode" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "voiceIcon" -> return NelePropertyType.DRAWABLE
      "voiceLanguage" -> return NelePropertyType.ID
      "voiceLanguageModel" -> return NelePropertyType.ID
      "voiceMaxResults" -> return NelePropertyType.INTEGER
      "voicePromptText" -> return NelePropertyType.ID
      "voiceSearchMode" -> return NelePropertyType.INTEGER
      "weekNumberColor" -> return NelePropertyType.COLOR
      "weekSeparatorLineColor" -> return NelePropertyType.COLOR
      "weightSum" -> return NelePropertyType.FLOAT
      "widgetLayout" -> return NelePropertyType.ID
      "width" -> return NelePropertyType.DIMENSION
      "windowAnimationStyle" -> return NelePropertyType.ID
      "windowIsFloating" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "windowIsTranslucent" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "windowNoDisplay" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "windowSoftInputMode" -> return NelePropertyType.INTEGER
      "windowSwipeToDismiss" -> return NelePropertyType.THREE_STATE_BOOLEAN
      "xlargeScreens" -> return NelePropertyType.INTEGER
      "zAdjustment" -> return NelePropertyType.INTEGER
      else -> return NelePropertyType.UNKNOWN
    }
  }
}

