/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.ui

/*
List of the public issue tracker components for Android Studio.
These values are taken from go/as-components. Changes made there
must be reflected here.
 */

val FEEDBACK_COMPONENTS = listOf(
  "Android Platform Support (ASfP)",
  "Assistant Window",
  "Assistant Window > Connection Assistant",
  "Assistant Window > Connection Assistant > Automated reports",
  "Assistant Window > What's New Assistant",
  "Build Tools",
  "Build Tools > Dexer (D8)",
  "Build Tools > Lint",
  "Build Tools > Parcelize",
  "Build Tools > Shrinker (R8)",
  "Bundled Plugins",
  "Bundled Plugins > Firebase",
  "Bundled Plugins > Google Cloud",
  "Configuration",
  "Configuration > AVD Manager",
  "Configuration > Preferences",
  "Configuration > Project Structure",
  "Configuration > SDK Manager",
  "Configuration > Windows & Menus",
  "Core IDE (read only)",
  "Dependency Management",
  "Deployment",
  "Deployment > ADB",
  "Deployment > APK Debugging",
  "Deployment > Apply Changes",
  "Deployment > C++ Debugger",
  "Deployment > Debugger",
  "Deployment > Run",
  "Deployment > Slicer",
  "Design Tools",
  "Design Tools > AVD Preview",
  "Design Tools > Compose Preview",
  "Design Tools > Layout Editor",
  "Design Tools > Layout Inspector",
  "Design Tools > Motion Editor",
  "Design Tools > Navigation Editor",
  "Design Tools > Rendering",
  "Design Tools > Resource Manager",
  "Design Tools > Validation",
  "Documentation",
  "Editing",
  "Editing > AndroidX Refactor",
  "Editing > C++ Editor",
  "Editing > Code Analysis",
  "Editing > Code Editor",
  "Editing > Compose Editing",
  "Editing > Data Binding",
  "Editing > Find Usages",
  "Editing > Gradle Files Editor",
  "Editing > Indexing",
  "Editing > Java to Kotlin Refactor",
  "Editing > Live Edit",
  "Editing > Manifests",
  "Editing > ML Model Binding",
  "Editing > Modularize Refactor",
  "Editing > Move/Rename Code Refactor",
  "Editing > Open Project",
  "Editing > Remove Unused Resources Refactor",
  "Editing > Resources",
  "Editing > Search",
  "Editing > Translations Editor",
  "Editing > View Binding",
  "Emulator",
  "Emulator > Chrome OS",
  "Emulator > GPU",
  "Emulator > System Images",
  "Emulator > Emulator System Images",
  "Emulator > AR",
  "Emulator > Embedded Emulator",
  "Emulator >  UIautomator",
  "Emulator >  Wear",
  "Emulator > Wear",
  "Getting Started",
  "Getting Started > Feedback",
  "Getting Started > First Launch",
  "Getting Started > Installer",
  "Getting Started > New Code/Templates",
  "Getting Started > New Project Wizard",
  "Getting Started > System Requirements",
  "Getting Started > Tip of the day",
  "Getting Started > Updater",
  "Getting Started > Welcome Screen",
  "Getting Started > Wear Pairing Assistant",
  "gMaven",
  "Gradle",
  "Gradle > Android Gradle Plugin",
  "Gradle > Android Gradle Plugin > Android App Bundles",
  "Gradle > Android Gradle Plugin > API",
  "Gradle > Android Gradle Plugin > Lint integration",
  "Gradle > Android Gradle Plugin > Prefab Integration",
  "Gradle > C++ Build",
  "Gradle > C++ Import/Sync",
  "Gradle > Import/Sync",
  "Gradle > Offline Support",
  "Gradle > Release Bundle/APKs",
  "Gradle > Upgrade Assistant",
  "Help",
  "AOSP/Infrastructure",
  "IntelliJ",
  "IntelliJ > Kotlin Plugin",
  "JDK",
  "Profilers",
  "Profilers > CPU",
  "Profilers > Events",
  "Profilers > Memory",
  "Profilers > Network",
  "Testing",
  "Testing > Espresso Recorder",
  "Testing > Running Tests",
  "Third Party Plugins",
  "Tool Windows",
  "Tool Windows > APK Viewer",
  "Tool Windows > App Quality Insights",
  "Tool Windows > Background Task Inspector",
  "Tool Windows > Build Analyzer",
  "Tool Windows > Build Output",
  "Tool Windows > Build Variants",
  "Tool Windows > Database Inspector",
  "Tool Windows > Device File Explorer",
  "Tool Windows > Device Manager",
  "Tool Windows > Emulator",
  "Tool Windows > Logcat",
  "Tool Windows > Network Inspector",
  "Tool Windows > Project View",
  "Tool Windows > Gradle",
  "Tool Windows > Screenshot Editor",
  "Tool Windows > Structure",
  "Tool Windows > Terminal",
  "Tool Windows > Version Control",
  "App Development > Android Game Development Extension"
)
