load("//tools/adt/idea/studio:studio.bzl", "studio_data")
load("//tools/base/bazel:jvm_import.bzl", "jvm_import")

# managed by go/iml_to_build
jvm_import(
    name = "pepk",
    jars = ["pepk.jar"],
    visibility = ["//visibility:public"],
)
