/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service.snippets;

import com.android.tools.rpclib.binary.Decoder;
import com.android.tools.rpclib.binary.Encoder;
import com.google.common.collect.ImmutableMap;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;

public final class SymbolCategory {
  public static final SymbolCategory Global = new SymbolCategory(0, "Global");
  public static final int GlobalValue = 0;
  public static final SymbolCategory Local = new SymbolCategory(1, "Local");
  public static final int LocalValue = 1;
  public static final SymbolCategory Parameter = new SymbolCategory(2, "Parameter");
  public static final int ParameterValue = 2;

  private static final ImmutableMap<Integer, SymbolCategory> VALUES = ImmutableMap.<Integer, SymbolCategory>builder()
    .put(0, Global)
    .put(1, Local)
    .put(2, Parameter)
    .build();

  private final int myValue;
  private final String myName;

  private SymbolCategory(int v, String n) {
    myValue = v;
    myName = n;
  }

  public int getValue() {
    return myValue;
  }

  public String getName() {
    return myName;
  }

  public void encode(@NotNull Encoder e) throws IOException {
    e.int32(myValue);
  }

  public static SymbolCategory decode(@NotNull Decoder d) throws IOException {
    return findOrCreate(d.int32());
  }

  public static SymbolCategory find(int value) {
    return VALUES.get(value);
  }

  public static SymbolCategory findOrCreate(int value) {
    SymbolCategory result = VALUES.get(value);
    return (result == null) ? new SymbolCategory(value, null) : result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || !(o instanceof SymbolCategory)) return false;
    return myValue == ((SymbolCategory)o).myValue;
  }

  @Override
  public int hashCode() {
    return myValue;
  }

  @Override
  public String toString() {
    return (myName == null) ? "SymbolCategory(" + myValue + ")" : myName;
  }
}
