licenses(["notice"])

java_library(
    name = "vcs",
    srcs = glob(["*.java"]),
    visibility = ["//tools/adt/idea/aswb/shared:__subpackages__"],
    deps = [
        "@maven//:com.google.guava.guava",
    ],
)
