load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.gradle.dsl.something",
    srcs = ["src"],
    iml_files = ["intellij.android.gradle.dsl.something.iml"],
    visibility = ["//visibility:public"],
)
