/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.gradle.project.sync.runsIndexingWithGradlePhasedSync

import com.android.tools.idea.gradle.project.sync.snapshots.TestProject

internal object MiscConsistencyIssues {
  internal fun projectStructure(testProject: TestProject) =
    when (testProject) {
      // TODO(b/384022658): Info from KaptGradleModel is missing for phased sync entities for now
      TestProject.KOTLIN_KAPT,
      TestProject.NEW_SYNC_KOTLIN_TEST ->
        setOf(
          // TODO(b/384022658): Generated class libraries aren't supported yet
          "LIBRARY (Gradle: kaptGeneratedClasses [=])",
          // TODO(b/384022658): Module level libraries are set up differently in some cases
          "/LIBRARY (Gradle: org.jetbrains:annotations:13.0 [=])/LibraryLevel (module)",
          "/LIBRARY (Gradle: org.jetbrains:annotations:13.0 [=])/IsModuleLevel (true)",
        )

      TestProject.BUILD_CONFIG_AS_BYTECODE_ENABLED ->
        setOf(
          // TODO(b/384022658): Generated class libraries aren't supported
          "LIBRARY (Gradle: buildConfigGeneratedClasses [=])"
        )

      TestProject.TEST_SUITES ->
        setOf(
          // TODO(b/445376814): Understand why they are different
          "MODULE (project.app.second)/CONTENT_ENTRY"
        )

      else -> emptySet()
    }
}

internal object MiscResyncIssues {
  val filteredProjects =
    setOf(
      // TODO(b/384022658): There is an issue regarding the full sync regarding this project, it seems to create duplicate
      //  library dependencies for some modules. Probably has to do with module libraries.
      TestProject.KOTLIN_MULTIPLATFORM_WITHJS
    )

  internal fun projectStructure(testProject: TestProject) =
    when (testProject) {
      TestProject.TEST_SUITES ->
        setOf(
          // TODO(b/445376814): Understand why they are different
          "MODULE (project.app.second)/CONTENT_ENTRY"
        )
      // Phased sync creates these module level libraries as project level libraries whereas in data services we have them as
      // module level (or vice versa)
      TestProject.NEW_SYNC_KOTLIN_TEST,
      TestProject.KOTLIN_KAPT -> setOf("/LIBRARY (Gradle: org.jetbrains:annotations:13.0 [=])")

      else -> emptySet()
    }

  /** These are issues that are not resolved even after the full sync finishes. */
  internal fun fullResyncProjectStructure(testProject: TestProject) =
    when (testProject) {
      // TODO(b/384022658): There are consistency issues around how the JDK for the root project is set up.
      TestProject.SIMPLE_APPLICATION_NOT_AT_ROOT -> setOf("MODULE (gradle_project)/*isInherited")
      TestProject.SIMPLE_APPLICATION_MULTIPLE_ROOTS ->
        setOf("MODULE (gradle_project_name)/*isInherited", "MODULE (gradle_project_1)/*isInherited")
      else -> emptySet()
    }
}

internal object MiscReopenIssues {
  val filteredProjects =
    setOf(
      // TODO(b/384022658): We already fail to re-open these projects due to validation in startup activity failing to find missing
      // jar files that are generated by build. It's not clear whether this is phased sync behaviour or not.
      TestProject.NON_STANDARD_SOURCE_SET_DEPENDENCIES_MANUAL_TEST_FIXTURES_WORKAROUND,
      // TODO(b/384022658): This one fails to restore the full state and triggers a sync.
      TestProject.SIMPLE_APPLICATION_MULTIPLE_ROOTS,
    )
}

internal object GradleProjectPathConsistencyIssues {
  val filteredProjects =
    setOf(
      TestProject.KOTLIN_MULTIPLATFORM_MULTIPLE_SOURCE_SET_PER_ANDROID_COMPILATION, // GPP null for source-sets
      TestProject.KOTLIN_MULTIPLATFORM_WITHJS, // exclude 'jsModule'
      TestProject.KOTLIN_MULTIPLATFORM_JVM_KMPAPP_WITHINTERMEDIATE, // kmp source-sets not supported
      TestProject.NON_STANDARD_SOURCE_SET_DEPENDENCIES, // small subset of modules not included
      TestProject.KOTLIN_MULTIPLATFORM_JVM, // some source sets in module2 not included
      TestProject.NON_STANDARD_SOURCE_SET_DEPENDENCIES_MANUAL_TEST_FIXTURES_WORKAROUND, // some source sets not included
      TestProject.KOTLIN_MULTIPLATFORM_JVM_KMPAPP, // some source sets not included
      TestProject.KOTLIN_MULTIPLATFORM, // some source sets not included
      TestProject.KOTLIN_MULTIPLATFORM_IOS,
      TestProject.SIMPLE_APPLICATION_MULTIPLE_ROOTS,
    )
}

internal object UnactionableConsistencyIssues {
  fun projectStructure(testProject: TestProject) =
    when (testProject) {
      TestProject.MULTI_FLAVOR_SWITCH_VARIANT ->
        setOf(
          // This is stored in the facet but does actually change correctly when switching
          "/SelectedBuildVariant"
        )
      TestProject.MAIN_IN_ROOT ->
        setOf(
          // This is incorrectly populated as a content root(!) in old sync
          "project</>app</>AndroidManifest.xml",
          // This is incorrectly missing from the old sync content roots
          "project</>app</>src</>debug",
        )
      // TODO:(b/384022658): When syncing an already existing project with iml
      TestProject.COMPATIBILITY_TESTS_AS_36 ->
        setOf(
          //  1. Some external options metadata is different
          "/ExternalModuleGroup",
          "/ExternalModuleVersion",
          //  2. Holder modules have their directory as a content root (which should be incorrect)
          "MODULE (AS36.features)/CONTENT_ENTRY",
          "MODULE (AS36.libs)/CONTENT_ENTRY",
          "MODULE (AS36.libs.java_lib)/CONTENT_ENTRY",
          "MODULE (AS36.app)/CONTENT_ENTRY",
          "MODULE (AS36.features.dynamicfeature)/CONTENT_ENTRY",
          "MODULE (AS36.features.dynamicfeature2)/CONTENT_ENTRY",
          "MODULE (AS36.libs.android_library)/CONTENT_ENTRY",
        )
      else -> emptySet()
    }

  fun ideModels(testProject: TestProject) =
    when (testProject) {
      TestProject.MULTI_FLAVOR_SWITCH_VARIANT ->
        setOf(
          // TODO:(b/384022658): This is a quirk of this project where we have to capture the intermediate state switching variants
          // (essentially
          // a second sync). We don't normally expect the library table to be present but in this case it is because a full sync has
          // completed.
          "LIBRARY_TABLE"
        )
      // The models for phased sync is fetched too early and are missing this, but it's fine as we have the rest of the tasks for variants
      TestProject.PSD_SAMPLE_GROOVY -> setOf("/taskNames (testDebugUnitTest)")
      TestProject.TWO_JARS -> setOf("/taskNames (test)")
      else -> emptySet()
    }
}

internal object UnactionableResyncIssues {
  fun projectStructure(testProject: TestProject) =
    when (testProject) {
      TestProject.MAIN_IN_ROOT ->
        setOf(
          // This is incorrectly missing from the old sync content roots
          "project</>app</>src</>debug"
        )
      else -> emptySet()
    }
}
