/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.navigator.nodes.ndk.includes;

import java.util.ArrayList;
import java.util.List;
import org.jetbrains.annotations.NotNull;

public final class RealWorldExamples {

  public final static String[] NDK_R18_SXS_EXAMPLE = {
    "-I/usr/local/google/home/jomof/Android/Sdk/ndk/18.1.5063045/sysroot/usr/include",
    "-I/usr/local/google/home/jomof/Android/Sdk/ndk/18.1.5063045/sources/cxx-stl/llvm-libc++/include",
    "-I/usr/local/google/home/jomof/Android/Sdk/ndk/18.1.5063045/sources/android/support/include",
    "-I/usr/local/google/home/jomof/Android/Sdk/ndk/18.1.5063045/sources/cxx-stl/llvm-libc++abi/include",
    "-I/usr/local/google/home/jomof/Android/Sdk/ndk/18.1.5063045/sysroot/usr/include/i686-linux-android"
  };

  public final static String[] NDK_R19_LEGACY_EXAMPLE = {
    "--sysroot={ndkPath}/toolchains/llvm/prebuilt/darwin-x86_64/sysroot"
  };


  // This is an example from r19, there is only a single include header (sysroot)
  // So we need to be careful not to collapse that node. Otherwise, the user receives a
  // giant flat list of folders that makes less sense.
  public final static String[] NDK_R19_SXS_EXAMPLE = {
    "--sysroot=/usr/local/google/home/jomof/Android/Sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
  };

  public final static String[] NDK_R19_0_SXS_EXAMPLE = {
    "--sysroot=/usr/local/google/home/jomof/Android/Sdk/ndk/19.0.5345600/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
  };

  public final static String[] NDK_SPECIAL_PACKAGES_EXAMPLE =
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include", "-I{ndkPath}/sources/third_party/googletest/googletest/include"};
  public final static String[] COCOS_EXTERNAL_ROOT_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external",
  };
  public final static String[] COCOS_EDITOR_SUPPORT_ROOT_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support",
  };
  public final static String[] COCOS_EXTERNAL_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/xxhash",
  };
  public final static String[] DOLPHIN_EXAMPLE = { 
    "--sysroot=/path/to/ndk-bundle/sysroot",
    "-I../../../../../../../Externals/curl/include",
    "-I../../../../../../../Externals/SFML/include",
    "-I../../../../../../Core",
    "-I../../../../../",
    "-I../../../../../../../Externals/enet/include",
    "-I../../../../../../../External/minizip",
    "-I../../../../../../../Externals",
    "-I../../../../../../../Externals/mbedtls/include",
    "-I../../../../../../../Externals/libiconv-1.14/include",
    "-ISource/Core",
    "-isystem",
    "../../../../../../Core/Common/Compat",
    "-I../../../../../../../Externals/cubeb/include",
    "-Iexports",
    "-I../../../../../../../Externals/pugixml/.",
    "-I../../../../../../../Externals/cpp-optparse/.",
    "-I../../../../../../../Externals/minizip/.",
    "-isystem",
    "/path/to/ndk-bundle/sources/cxx-stl/llvm-libc++/include",
    "-isystem",
    "/path/to/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include",
    "-isystem",
    "/path/to/ndk-bundle/sysroot/usr/include/aarch64-linux-android"
  };

  public final static String[] CDEP_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/mathfu/1.1.0-rev3/mathfu-headers.zip/include",
    "-I/usr/local/google/home/jomof/third_party/OpenCV/include",
    "-I{ndkPath}/platforms/android-21/arch-x86_64",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/sdl2/2.0.5-rev26/headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/firebase/app/2.1.3-rev22/firebase-app-header.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/lua/5.3.4/lua-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/image_resize/0.0.0-rev6/stb-image_resize-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/herringbone_wang_tile/0.0.0-rev6/stb-herringbone_wang_tile-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/dxt/0.0.0-rev6/stb-dxt-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/c_lexer/0.0.0-rev6/stb-c_lexer-headers.zip/include",
    "-I{ndkPath}/platforms/android-15/arch-x86",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/image/0.0.0-rev6/stb-image-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/truetype/0.0.0-rev6/stb-truetype-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/tilemap_editor/0.0.0-rev6/stb-tilemap_editor-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/easy_font/0.0.0-rev6/stb-easy_font-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/sqlite/3.16.2-rev51/headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/textedit/0.0.0-rev6/stb-textedit-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/tinydir/0.0.0-rev8/tinydir-headers.zip/include",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/voxel_render/0.0.0-rev6/stb-voxel_render-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/perlin/0.0.0-rev6/stb-perlin-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/freetype/2.6.2-rev14/headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/connected_components/0.0.0-rev6/stb-connected_components-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/vectorial/0.0.0-rev21/vectorial-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/rect_pack/0.0.0-rev6/stb-rect_pack-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/leakcheck/0.0.0-rev6/stb-leakcheck-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/divide/0.0.0-rev6/stb-divide-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/protobuf/3.2.0-rev0/protobuf-android-cxx-platform-12.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/protobuf/3.2.0-rev0/protobuf-android-cxx-platform-21.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/image_write/0.0.0-rev6/stb-image_write-headers.zip/include",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof.cdep/boost/1.0.63/boost_1_63_0.zip/boost_1_63_0",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/stb/sprintf/0.0.0-rev6/stb-sprintf-headers.zip/include",
    "-I/usr/local/google/home/jomof/projects/cdep-android-studio-freetype-sample/build/cdep/exploded/com.github.jomof/re2/17.3.1-rev18/re2-headers.zip/include",
  };
  public final static String[] MINI_COCOS_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/poly2tri",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/poly2tri/sweep"};
  public final static String[] COCOS_EXAMPLE = {
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/ui",
    "-I{ndkPath}/platforms/android-21/arch-x86_64",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/flatbuffers",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/chipmunk/include/chipmunk",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/3d",
    "-I{ndkPath}/platforms/android-9/arch-arm",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external",
    "-I/usr/local/google/home/jomof/projects/Game/proj.android-studio/app/jni",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/audio/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support/cocostudio",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/curl/include/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support/spine",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/platform",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/nslog",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/poly2tri/common",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/poly2tri",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/zlib/include",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/include",
    "-I{ndkPath}/sources/android/cpufeatures",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/Box2D",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/tinyxml2",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/bullet",
    "-I{ndkPath}/platforms/android-9/arch-x86",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/poly2tri/sweep",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/extensions/GUI/CCScrollView",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/unzip",
    "-I{ndkPath}/platforms/android-9/arch-mips",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support/cocosbuilder",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/network",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/platform/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/freetype2/include/android",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/webp/include/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/tiff/include/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/edtaa3func",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/freetype2/include/android/freetype2",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/websockets/include/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/extensions",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support/cocostudio/WidgetReader",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/chipmunk/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/base",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/clipper",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/2d",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/ConvertUTF",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/recast",
    "-I{ndkPath}/platforms/android-21/arch-mips64",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/editor-support",
    "-I/usr/local/google/home/jomof/projects/Game/Classes",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/png/include/android",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/xxhash",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/external/jpeg/include/android",
    "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/extensions/GUI/CCControlExtension",
    "-I/usr/local/google/home/jomof/projects/Game/cocos2d/cocos/audio/android",
    "-I{ndkPath}/platforms/android-21/arch-arm64"};
  public final static String[] RENDERSCRIPT_EXAMPLE = {
    "-I{ndkPath}/toolchains/renderscript/prebuilt/{platform}-x86_64/lib/clang/3.5/include",
    "-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs/scriptc", "-I{ndkPath}/samples/HelloComputeNDK/jni"};
  public final static String[] TWO_INCLUDES_SAME_BASE_NAME = {
    "-I/project/include",
    "-I/project/subproject/include"};
  public final static String[] TWO_WINDOWS_INCLUDES_SAME_BASE_NAME = {
    "-ID:\\project\\include",
    "-ID:\\project\\subproject\\include"};
  public final static String[] TWO_WINDOWS_INCLUDES_SAME_BASE_NAME_DOUBLE_SLASHES = {
    "-ID:\\\\project\\\\include",
    "-ID:\\\\project\\\\subproject\\\\include"};
  public final static String[] TWO_IDENTICAL_INCLUDES = {
    "-I/project/include",
    "-I/project/include"};
  private final static String[] PACKAGING_EXPRESSION_EXAMPLE =
    {"-I../../../../cocos/editor-support/cocostudio/..", "-I../../../../cocos/editor-support/cocostudio/WidgetReader",
      "-I../../../../cocos/ui/../editor-support", "-I../../../../cocos/audio/android/../include", "-I../../../../external/flatbuffers/..",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../extensions/.", "-I../../../../extensions/..", "-I../../../../extensions/GUI/CCControlExtension",
      "-I../../../../extensions/GUI/CCScrollView", "-I../../../../cocos/audio/android/../include", "-I../../../../cocos/.",
      "-I../../../../cocos/./.", "-I../../../../cocos/./..", "-I../../../../cocos/./../external",
      "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/Box2D/..", "-I../../../../external/bullet/..",
      "-I../../../../cocos/network", "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures",
      "-I../../../../external/websockets/prebuilt/android/../../include/android", "-I../../../../cocos/editor-support/cocostudio",
      "-isystem", "{ndkPath}/platforms/android-9/arch-x86/usr/include"};
  /* A set of real world include flags gathered from various places. */
  public static final String[][] COMPILER_INCLUDE_FLAGS = {
    PACKAGING_EXPRESSION_EXAMPLE,
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-arm64"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-x86_64"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-mips64"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-arm"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-x86"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/sources/android/ndk_helper",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/Teapot/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/sources/android/native_app_glue",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/sources/android/ndk_helper", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-mips"},
    {"-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward", "-I{HOME}/projects/NdkBuildTestApplication/app/sample/jni",
      "-isystem", "{ndkPath}/platforms/android-23/arch-arm64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-23/arch-arm64"},
    {"-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I{ndkPath}/sources/third_party/googletest/googletest/include", "-I{HOME}/projects/NdkBuildTestApplication/app/sample/jni",
      "-isystem", "{ndkPath}/platforms/android-23/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/third_party/googletest/googletest/include", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I{ndkPath}/sources/third_party/googletest/googletest", "-isystem",
      "{ndkPath}/platforms/android-23/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/native-audio/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-arm"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-x86"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/native-codec/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-mips"},
    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},

    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-14/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-14/arch-arm"},
    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-14/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-14/arch-x86"},
    {"-I{ndkPath}/samples/native-media/jni", "-I{ndkPath}/platforms/android-14/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-14/arch-mips"},
    {"-I{ndkPath}/sources/android/cpufeatures",
      "-I/usr/local/google/home/jomof/projects/hello-neon1/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-isystem",
      "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-arm"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-plasma/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures",
      "-I/usr/local/google/home/jomof/projects/hello-neon1/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-23/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-isystem",
      "{ndkPath}/platforms/android-23/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-23/arch-arm"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-8/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-8/arch-arm"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/bitmap-plasma/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},

    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/native_app_glue", "-I{ndkPath}/samples/native-activity/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-21\\arch-arm64\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-21\\arch-arm64"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-21\\arch-x86_64\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-21\\arch-x86_64"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-21\\arch-mips64\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-21\\arch-mips64"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-4\\arch-arm\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-4\\arch-arm"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-9\\arch-x86\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-9\\arch-x86"},
    {"-Ic:\\{ndkPath}\\samples\\san-angeles\\jni", "-Ic:\\{ndkPath}\\platforms\\android-9\\arch-mips\\usr\\include"},
    {"--sysroot=c:\\{ndkPath}\\platforms\\android-9\\arch-mips"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-4/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-4/arch-arm"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/san-angeles/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{project}/jni/libjpeg-turbo/include", "-I{project}/jni/libjpeg-turbo/src", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I{project}/jni/processor", "-isystem", "{ndkPath}/platforms/android-23/arch-arm/usr/include"},
    {"-I{project}/jni/libjpeg-turbo/include", "-I{project}/jni/libjpeg-turbo/src", "-I{project}/jni/libjpeg-turbo", "-isystem",
      "{ndkPath}/platforms/android-23/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-23/arch-arm"},
    {"-I{ndkPath}/toolchains/renderscript/prebuilt/{platform}-x86_64/lib/clang/3.5/include",
      "-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs/scriptc", "-I{ndkPath}/samples/HelloComputeNDK/jni"},
    {"-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/armeabi-v7a/objs-debug/hellocomputendk",
      "-I{ndkPath}/sources/cxx-stl/stlport/stlport", "-I{ndkPath}/sources/cxx-stl//gabi++/include",
      "-I{ndkPath}/samples/HelloComputeNDK/jni", "-I{ndkPath}/platforms/android-19/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-19/arch-arm"},
    {"-I{ndkPath}/toolchains/renderscript/prebuilt/{platform}-x86_64/lib/clang/3.5/include",
      "-I{ndkPath}/platforms/android-19/arch-x86/usr/include/rs/scriptc", "-I{ndkPath}/samples/HelloComputeNDK/jni"},
    {"-I{ndkPath}/platforms/android-19/arch-x86/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-x86/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/x86/objs-debug/hellocomputendk", "-I{ndkPath}/sources/cxx-stl/stlport/stlport",
      "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/HelloComputeNDK/jni",
      "-I{ndkPath}/platforms/android-19/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-19/arch-x86"},
    {"-I{ndkPath}/toolchains/renderscript/prebuilt/{platform}-x86_64/lib/clang/3.5/include",
      "-I{ndkPath}/platforms/android-19/arch-mips/usr/include/rs/scriptc", "-I{ndkPath}/samples/HelloComputeNDK/jni"},
    {"-I{ndkPath}/platforms/android-19/arch-mips/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-mips/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/mips/objs-debug/hellocomputendk", "-I{ndkPath}/sources/cxx-stl/stlport/stlport",
      "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/HelloComputeNDK/jni",
      "-I{ndkPath}/platforms/android-19/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-19/arch-mips"},
    {"-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-arm/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/armeabi-v7a/objs/hellocomputendk", "-I{ndkPath}/sources/cxx-stl/stlport/stlport",
      "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/HelloComputeNDK/jni",
      "-I{ndkPath}/platforms/android-19/arch-arm/usr/include"},
    {"-I{ndkPath}/platforms/android-19/arch-x86/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-x86/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/x86/objs/hellocomputendk", "-I{ndkPath}/sources/cxx-stl/stlport/stlport",
      "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/HelloComputeNDK/jni",
      "-I{ndkPath}/platforms/android-19/arch-x86/usr/include"},
    {"-I{ndkPath}/platforms/android-19/arch-mips/usr/include/rs/cpp", "-I{ndkPath}/platforms/android-19/arch-mips/usr/include/rs",
      "-I{ndkPath}/samples/HelloComputeNDK/obj/local/mips/objs/hellocomputendk", "-I{ndkPath}/sources/cxx-stl/stlport/stlport",
      "-I{ndkPath}/sources/cxx-stl//gabi++/include", "-I{ndkPath}/samples/HelloComputeNDK/jni",
      "-I{ndkPath}/platforms/android-19/arch-mips/usr/include"},
    {"-I/usr/local/google/someuser/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/jni/../../../Classes",
      "-I/usr/local/google/someuser/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/jni/../../../../../extensions",
      "-I/usr/local/google/someuser/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/jni/../../../../..",
      "-I/usr/local/google/someuser/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/jni/../../../../../cocos/editor-support",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../cocos/editor-support/cocostudio/..", "-I../../../../cocos/editor-support/cocosbuilder/..", "-I../../../../cocos/3d/..",
      "-I../../../../cocos/editor-support/spine/..", "-I../../../../cocos/network", "-I../../../../cocos/audio/android/../include",
      "-I../../../../cocos/ui/../editor-support", "-I../../../../cocos/audio/android/../include", "-I../../../../external/flatbuffers/..",
      "-I../../../../extensions/.", "-I../../../../extensions/..", "-I../../../../extensions/GUI/CCControlExtension",
      "-I../../../../extensions/GUI/CCScrollView", "-I../../../../cocos/.", "-I../../../../cocos/./.", "-I../../../../cocos/./..",
      "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/websockets/prebuilt/android/../../include/android",
      "-I../../../../external/Box2D/..", "-I../../../../external/bullet/..",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures",
      "-I/usr/local/google/someuser/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/jni", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/editor-support/cocosbuilder/..", "-I../../../../cocos/editor-support/cocosbuilder/../../2d",
      "-I../../../../extensions/.", "-I../../../../extensions/..", "-I../../../../extensions/GUI/CCControlExtension",
      "-I../../../../extensions/GUI/CCScrollView",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward", "-I../../../../cocos/.",
      "-I../../../../cocos/./.", "-I../../../../cocos/./..", "-I../../../../cocos/./../external",
      "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/Box2D/..", "-I../../../../external/bullet/..",
      "-I../../../../cocos/network", "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures",
      "-I../../../../external/websockets/prebuilt/android/../../include/android", "-I../../../../cocos/editor-support/cocosbuilder",
      "-isystem", "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/3d/..", "-I../../../../cocos/.", "-I../../../../cocos/./.", "-I../../../../cocos/./..",
      "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../external/bullet/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures", "-I../../../../cocos/3d", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/editor-support/spine/..", "-I../../../../cocos/.", "-I../../../../cocos/./.", "-I../../../../cocos/./..",
      "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../external/bullet/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures", "-I../../../../cocos/editor-support/spine",
      "-isystem", "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/ui/../editor-support", "-I../../../../extensions/.", "-I../../../../extensions/..",
      "-I../../../../extensions/GUI/CCControlExtension", "-I../../../../extensions/GUI/CCScrollView",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward", "-I../../../../cocos/.",
      "-I../../../../cocos/./.", "-I../../../../cocos/./..", "-I../../../../cocos/./../external",
      "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/Box2D/..", "-I../../../../external/bullet/..",
      "-I../../../../cocos/network", "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures",
      "-I../../../../external/websockets/prebuilt/android/../../include/android", "-I../../../../cocos/ui", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/audio/android/../include", "-I../../../../cocos/audio/android/../..",
      "-I../../../../cocos/audio/android/../../platform/android", "-I../../../../cocos/audio/android/../include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../cocos/audio/android", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../external/flatbuffers/..",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/flatbuffers", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../extensions", "-I../../../../cocos/.", "-I../../../../cocos/./.", "-I../../../../cocos/./..",
      "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2", "-I../../../../cocos/./../external/unzip",
      "-I../../../../cocos/./../external/chipmunk/include/chipmunk", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/Box2D/..", "-I../../../../external/bullet/..",
      "-I../../../../cocos/network", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures",
      "-I../../../../external/websockets/prebuilt/android/../../include/android", "-I../../../../extensions", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/audio/android/../include", "-I../../../../cocos/audio/android/../..",
      "-I../../../../cocos/audio/android/../../platform/android",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../cocos/audio/android", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../external/Box2D/..", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/Box2D", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/network/../../external/curl/include/android",
      "-I../../../../cocos/network/../../external/websockets/include/android", "-I../../../../cocos/.", "-I../../../../cocos/./.",
      "-I../../../../cocos/./..", "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2",
      "-I../../../../cocos/./../external/unzip", "-I../../../../cocos/./../external/chipmunk/include/chipmunk",
      "-I../../../../cocos/./../external/xxhash", "-I../../../../cocos/./../external/nslog", "-I../../../../cocos/./../external/poly2tri",
      "-I../../../../cocos/./../external/poly2tri/common", "-I../../../../cocos/./../external/poly2tri/sweep",
      "-I../../../../cocos/./../external/clipper", "-I../../../../external/websockets/prebuilt/android/../../include/android",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../external/bullet/..", "-I../../../../cocos/platform/android",
      "-I{ndkPath}/sources/android/cpufeatures", "-I../../../../cocos/network", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/.", "-I../../../../cocos/./../external", "-I../../../../cocos/./../external/tinyxml2",
      "-I../../../../cocos/./../external/unzip", "-I../../../../cocos/./../external/chipmunk/include/chipmunk",
      "-I../../../../cocos/./../external/edtaa3func", "-I../../../../cocos/./../external/xxhash",
      "-I../../../../cocos/./../external/ConvertUTF", "-I../../../../cocos/./../external/nslog",
      "-I../../../../cocos/./../external/poly2tri", "-I../../../../cocos/./../external/poly2tri/common",
      "-I../../../../cocos/./../external/poly2tri/sweep", "-I../../../../cocos/./../external/clipper",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android",
      "-I../../../../external/freetype2/prebuilt/android/../../include/android/freetype2",
      "-I../../../../external/png/prebuilt/android/../../include/android",
      "-I../../../../external/jpeg/prebuilt/android/../../include/android",
      "-I../../../../external/tiff/prebuilt/android/../../include/android",
      "-I../../../../external/webp/prebuilt/android/../../include/android",
      "-I../../../../external/chipmunk/prebuilt/android/../../include", "-I../../../../external/zlib/prebuilt/android/../../include",
      "-I../../../../external/recast/..", "-I../../../../external/bullet/..",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../cocos/platform/android", "-I{ndkPath}/sources/android/cpufeatures",
      "-I../../../../cocos/.", "-isystem", "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../external/recast/..", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/recast", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../external/bullet/..", "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../external/bullet", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I../../../../cocos/platform/android", "-I../../../../cocos/platform/android/..", "-I../../../../cocos/platform/android/../..",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I../../../../cocos/platform/android", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/android/cpufeatures", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-x86"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-3/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-3/arch-arm"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/test-libstdc++/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-5/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-5/arch-arm"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/system/include", "-I{ndkPath}/samples/hello-gl2/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I/usr/local/google/home/jomof/projects/bug-214626/jni/../shared_cpp_code",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I/usr/local/google/home/jomof/projects/bug-214626/jni", "-isystem",
      "{ndkPath}/platforms/android-15/arch-arm/usr/include"},
    {"-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include",
      "-I{ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward",
      "-I/usr/local/google/home/jomof/projects/bug-214626/jni", "-isystem",
      "{ndkPath}/platforms/android-15/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-15/arch-arm"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-3/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/two-libs/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-arm64"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-x86_64"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-mips"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-mips64"},
    {"-Iinclude", "-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp", "-isystem",
      "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libapple", "-isystem",
      "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-Iinclude", "-I/usr/local/google/home/jomof/projects/repro-216676/probable-umbrella/app/src/main/cpp/libbanana", "-isystem",
      "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-3/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-3/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-3/arch-arm/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/foo", "-I{ndkPath}/samples/module-exports/jni",
      "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{ndkPath}/samples/module-exports/jni/bar", "-I{ndkPath}/samples/module-exports/jni/foo",
      "-I{ndkPath}/samples/module-exports/jni", "-I{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-21/arch-arm64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-arm64"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-21/arch-x86_64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-x86_64"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-21/arch-mips64/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-21/arch-mips64"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-9/arch-arm/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-arm"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-9/arch-x86/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-x86"},
    {"-I{project}/src/main/jni", "-isystem", "{ndkPath}/platforms/android-9/arch-mips/usr/include"},
    {"--sysroot={ndkPath}/platforms/android-9/arch-mips"},
    CDEP_EXAMPLE,
    COCOS_EXAMPLE
  };
  /* NDK folders present in COMPILER_INCLUDE_FLAGS */
  private static final String[] NDK_PATHS_IN_COMPILER_INCLUDE_FLAGS = {
    "c:\\{ndkPath}\\",
    "{ndkPath}/"
  };

  public static List<List<String>> getConcreteCompilerIncludeFlags(String pathToNdk) {
    List<List<String>> result = new ArrayList<>();
    for (String includes[] : COMPILER_INCLUDE_FLAGS) {
      List<String> flags = getConcreteCompilerIncludeFlags(pathToNdk, includes);
      result.add(flags);
    }
    return result;
  }

  @SuppressWarnings("DynamicRegexReplaceableByCompiledPattern")
  @NotNull
  public static List<String> getConcreteCompilerIncludeFlags(String pathToNdk, String[] includes) {
    List<String> flags = new ArrayList<>();

    for (String include : includes) {
      for (String ndkPathAlias : NDK_PATHS_IN_COMPILER_INCLUDE_FLAGS) {
        include = include.replace(ndkPathAlias, pathToNdk + "/");
      }
      include = include.replace("{HOME}/", "/usr/jomof/");
      include = include.replace("{project}/", "/usr/jomof/projects/my-project/");
      include = include.replace("{platform}", "android-21");
      if (include.contains("/cocos") && !include.contains("cocos2")) {
        include = include.replace("/cocos", "/cocos2d/cocos");
      }
      if (include.contains("/e/external/")) {
        include = include.replace("/e/external/", "/cocos2d/external/");
      }
      if (include.contains("{")) {
        throw new RuntimeException(include);
      }
      flags.add(include);
    }
    return flags;
  }
}
