java_library(
    name = "example",
    srcs = [
        "Class1.java",
        "Class2.java",
    ],
    deps = [
        "//generated_proto_files/project/java/com/example/lib:foo",
        "//generated_proto_files/project/java/com/example/lib:lib_java_proto",
    ],
)
