# This file is generated automatically. Do not modify.
SEARCHABLE_OPTIONS = {
    "canary": {
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-org.jetbrains.android-searchableOptions.json": "org.jetbrains.android",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.android.tools.ndk-searchableOptions.json": "com.android.tools.ndk",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.android.tools.design-searchableOptions.json": "com.android.tools.design",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-androidx.compose.plugins.idea-searchableOptions.json": "androidx.compose.plugins.idea",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.services.firebase-searchableOptions.json": "com.google.services.firebase",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.tools.ij.aiplugin-searchableOptions.json": "com.google.tools.ij.aiplugin",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.gct.directaccess-searchableOptions.json": "com.google.gct.directaccess",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.gct.test.recorder-searchableOptions.json": "com.google.gct.test.recorder",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.urlassistant-searchableOptions.json": "com.google.urlassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.google.targetsdkversionassistant-searchableOptions.json": "com.google.targetsdkversionassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/canary-searchable-options/p-com.android.tools.gradle.dcl-searchableOptions.json": "com.android.tools.gradle.dcl",
    },
    "nightly": {
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-org.jetbrains.android-searchableOptions.json": "org.jetbrains.android",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.android.tools.ndk-searchableOptions.json": "com.android.tools.ndk",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.android.tools.design-searchableOptions.json": "com.android.tools.design",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-androidx.compose.plugins.idea-searchableOptions.json": "androidx.compose.plugins.idea",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.services.firebase-searchableOptions.json": "com.google.services.firebase",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.tools.ij.aiplugin-searchableOptions.json": "com.google.tools.ij.aiplugin",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.gct.directaccess-searchableOptions.json": "com.google.gct.directaccess",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.gct.test.recorder-searchableOptions.json": "com.google.gct.test.recorder",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.urlassistant-searchableOptions.json": "com.google.urlassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.google.targetsdkversionassistant-searchableOptions.json": "com.google.targetsdkversionassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/nightly-searchable-options/p-com.android.tools.gradle.dcl-searchableOptions.json": "com.android.tools.gradle.dcl",
    },
    "stable": {
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-org.jetbrains.android-searchableOptions.json": "org.jetbrains.android",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.android.tools.ndk-searchableOptions.json": "com.android.tools.ndk",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.android.tools.design-searchableOptions.json": "com.android.tools.design",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-androidx.compose.plugins.idea-searchableOptions.json": "androidx.compose.plugins.idea",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.services.firebase-searchableOptions.json": "com.google.services.firebase",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.tools.ij.aiplugin-searchableOptions.json": "com.google.tools.ij.aiplugin",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.gct.directaccess-searchableOptions.json": "com.google.gct.directaccess",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.gct.test.recorder-searchableOptions.json": "com.google.gct.test.recorder",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.urlassistant-searchableOptions.json": "com.google.urlassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.google.targetsdkversionassistant-searchableOptions.json": "com.google.targetsdkversionassistant",
        "//tools/adt/idea/studio:searchable-options/android-studio/stable-searchable-options/p-com.android.tools.gradle.dcl-searchableOptions.json": "com.android.tools.gradle.dcl",
    },
}
