package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class AndroidIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, AndroidIcons.class);
  }

  public static final Icon Android = load("/icons/android.png"); // 16x16
  public static final Icon Android24 = load("/icons/android24.png"); // 24x24
  public static final Icon AndroidLarge = load("/icons/androidLarge.png"); // 64x64
  public static final Icon AndroidPreview = load("/icons/androidPreview.png"); // 16x16
  public static final Icon AndroidToolWindow = load("/icons/androidToolWindow.png"); // 13x13
  public static final Icon AttachDebugger = load("/icons/attachDebugger.png"); // 16x16
  public static final Icon ZoomActual = load("/icons/zoomActual.png"); // 16x16
  public static final Icon ZoomFit = load("/icons/zoomFit.png"); // 16x16
  public static final Icon ZoomIn = load("/icons/zoomIn.png"); // 16x16
  public static final Icon ZoomOut = load("/icons/zoomOut.png"); // 16x16
  public static final Icon Renderscript = load("/icons/renderscript.png"); // 16x16
  public static final Icon ErrorBadge = load("/icons/error-badge.png"); // 16x16
  public static final Icon WarningBadge = load("/icons/warning-badge.png"); // 16x16

  public static final Icon ArrowDown = load("/icons/comboArrow.png"); // 16x16

  public static final Icon Globe = load("/icons/globe.png"); // 16x16
  public static final Icon Square = load("/icons/square.png"); // 16x16
  public static final Icon Landscape = load("/icons/landscape.png"); // 16x16
  public static final Icon Portrait = load("/icons/portrait.png"); // 16x16
  public static final Icon FlipLandscape = load("/icons/flip_landscape.png"); // 16x16
  public static final Icon FlipPortrait = load("/icons/flip_portrait.png"); // 16x16
  public static final Icon Display = load("/icons/display.png"); // 16x16
  public static final Icon Themes = load("/icons/themes.png"); // 16x16
  public static final Icon DockMode = load("/icons/dockmode.png"); // 16x16
  public static final Icon Nightmode = load("/icons/nightmode.png"); // 16x16

  public static final Icon EmptyFlag = load("/icons/flags/flag_empty.png"); // 16x16
}
