load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.projectSystem.gradle.upgrade.tests",
    iml_files = ["intellij.android.projectSystem.gradle.upgrade.tests.iml"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.projectSystem.gradle.upgrade",
    iml_files = ["intellij.android.projectSystem.gradle.upgrade.iml"],
    visibility = ["//visibility:public"],
)
