load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "adt-branding",
    srcs = ["src"],
    visibility = ["//visibility:public"],
    deps = ["//tools:idea.platform-impl_and_others[module]"],
)
