load("//tools/adt/idea/aswb/testing:test_defs.bzl", "aswb_test")

aswb_test(
    name = "DeployTasksHelperTest",
    size = "small",
    srcs = ["DeployTasksHelperTest.kt"],
    test_class = "com.android.tools.idea.run.tasks.DeployTasksHelperTest",
    deps = [
        "//tools/adt/idea/aswb/aswb:aswb_lib",
        "//tools/adt/idea/aswb/base:integration_test_utils",
        "@maven//:junit.junit",
    ],
)
