/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.uibuilder.property.testutils

import com.android.tools.idea.uibuilder.property.NlPropertyType

/**
 * This file has data from analyzing the framework code in Android S (API 31).
 * The result were incomplete such that a number of attributes
 * had to be remapped by hand (from the online documentation).
 *
 * This file is assumed to be the truth about the attribute
 * types used in the framework. Use this file to verify any
 * type mappings of android framework attributes.
 *
 * Note: when adding attribute names to this list after updating the framework
 * or a library please look up the code that is reading the attribute.
 * Examples:
 *
 * | Function                         | Type                            | Notes                                 |
 * | -------------------------------- | ------------------------------- | --------------------------------------|
 * | TypedArray.getDrawable           | NlPropertyType.DRAWABLE         |                                       |
 * | TypedArray.getColor              | NlPropertyType.COLOR            | Make sure this is not a color list !! |
 * | TypedArray.getColorStateList     | NlPropertyType.COLOR_STATE_LIST |                                       |
 * | TypedArray.getDimensionPixelSize | NlPropertyType.DIMENSION        |                                       |
 * | TypedArray.getResourceId         | NlPropertyType.ID               |                                       |
 * | TypedArray.getInt                | NlPropertyType.ENUM             | If attrs.xml defines this as an enum  |
 * |                                  | NlPropertyType.INTEGER          | If this is not an enum                |
 */
object AndroidAttributeFact {

  fun lookup(name: String): NlPropertyType {
    when (name) {
      // Material Design additions
      "boxStrokeErrorColor" -> return NlPropertyType.COLOR_STATE_LIST
      "boxStrokeWidthFocused" -> return NlPropertyType.DIMENSION
      "checkedChip" -> return NlPropertyType.ID
      "checkedIcon" -> return NlPropertyType.DRAWABLE
      "checkedIconEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "checkedIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "checkedIconVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "chipBackgroundColor" -> return NlPropertyType.COLOR_STATE_LIST
      "chipCornerRadius" -> return NlPropertyType.DIMENSION
      "chipEndPadding" -> return NlPropertyType.DIMENSION
      "chipIcon" -> return NlPropertyType.DRAWABLE
      "chipIconEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "chipIconSize" -> return NlPropertyType.DIMENSION
      "chipIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "chipIconVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "chipMinHeight" -> return NlPropertyType.DIMENSION
      "chipMinTouchTargetSize" -> return NlPropertyType.DIMENSION
      "chipSpacing" -> return NlPropertyType.DIMENSION
      "chipSpacingHorizontal" -> return NlPropertyType.DIMENSION
      "chipSpacingVertical" -> return NlPropertyType.DIMENSION
      "chipStartPadding" -> return NlPropertyType.DIMENSION
      "chipStrokeColor" -> return NlPropertyType.COLOR_STATE_LIST
      "chipStrokeWidth" -> return NlPropertyType.DIMENSION
      "chipSurfaceColor" -> return NlPropertyType.COLOR_STATE_LIST
      "closeIconEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "closeIconEndPadding" -> return NlPropertyType.DIMENSION
      "closeIconSize" -> return NlPropertyType.DIMENSION
      "closeIconStartPadding" -> return NlPropertyType.DIMENSION
      "closeIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "closeIconVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "collapsedSize" -> return NlPropertyType.DIMENSION
      "collapsedTitleTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "contentPadding" -> return NlPropertyType.DIMENSION
      "contentPaddingBottom" -> return NlPropertyType.DIMENSION
      "contentPaddingEnd" -> return NlPropertyType.DIMENSION
      "contentPaddingLeft" -> return NlPropertyType.DIMENSION
      "contentPaddingRight" -> return NlPropertyType.DIMENSION
      "contentPaddingStart" -> return NlPropertyType.DIMENSION
      "contentPaddingTop" -> return NlPropertyType.DIMENSION
      "cornerRadius" -> return NlPropertyType.DIMENSION
      "counterOverflowTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "counterTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "dividerInsetStart" -> return NlPropertyType.DIMENSION
      "dividerInsetEnd" -> return NlPropertyType.DIMENSION
      "drawerLayoutCornerSize" -> return NlPropertyType.DIMENSION
      "endIconCheckable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "endIconContentDescription" -> return NlPropertyType.STRING
      "endIconDrawable" -> return NlPropertyType.DRAWABLE
      "endIconMode" -> return NlPropertyType.ENUM
      "endIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "endIconTintMode" -> return NlPropertyType.ENUM
      "ensureMinTouchTargetSize" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "emojiCompatEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "errorContentDescription" -> return NlPropertyType.STRING
      "errorIconDrawable" -> return NlPropertyType.DRAWABLE
      "errorIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "errorIconTintMode" -> return NlPropertyType.ENUM
      "errorTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "expandedHintEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "expandedTitleTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "extendMotionSpec" -> return NlPropertyType.ANIMATOR
      "extraMultilineHeightEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fabAlignmentMode" -> return NlPropertyType.ENUM
      "fabAnimationMode" -> return NlPropertyType.ENUM
      "fabCradleMargin" -> return NlPropertyType.DIMENSION
      "fabCradleRoundedCornerRadius" -> return NlPropertyType.DIMENSION
      "fabCradleVerticalOffset" -> return NlPropertyType.DIMENSION
      "forceApplySystemWindowInsetTop" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "haloColor" -> return NlPropertyType.COLOR_STATE_LIST
      "haloRadius" -> return NlPropertyType.DIMENSION
      "helperTextTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "hideAnimationBehavior" -> return NlPropertyType.ENUM
      "hideOnScroll" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hintTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "iconEndPadding" -> return NlPropertyType.DIMENSION
      "iconStartPadding" -> return NlPropertyType.DIMENSION
      "iconGravity" -> return NlPropertyType.FLAGS
      "iconPadding" -> return NlPropertyType.DIMENSION
      "iconSize" -> return NlPropertyType.DIMENSION
      "insetBottom" -> return NlPropertyType.DIMENSION
      "indeterminateAnimationType" -> return NlPropertyType.ENUM
      "indicatorColor" -> return NlPropertyType.COLOR
      "indicatorDirectionCircular" -> return NlPropertyType.ENUM
      "indicatorDirectionLinear" -> return NlPropertyType.ENUM
      "indicatorInset" -> return NlPropertyType.DIMENSION
      "indicatorSize" -> return NlPropertyType.DIMENSION
      "insetLeft" -> return NlPropertyType.DIMENSION
      "insetRight" -> return NlPropertyType.DIMENSION
      "insetTop" -> return NlPropertyType.DIMENSION
      "itemActiveIndicatorStyle" -> return NlPropertyType.STYLE
      "itemMaxLines" -> return NlPropertyType.INTEGER
      "itemMinHeight" -> return NlPropertyType.DIMENSION
      "itemRippleColor" -> return NlPropertyType.COLOR_STATE_LIST
      "itemShapeAppearance" -> return NlPropertyType.STYLE
      "itemShapeAppearanceOverlay" -> return NlPropertyType.STYLE
      "itemShapeFillColor" -> return NlPropertyType.COLOR_STATE_LIST
      "itemShapeInsetBottom" -> return NlPropertyType.DIMENSION
      "itemShapeInsetEnd" -> return NlPropertyType.DIMENSION
      "itemShapeInsetStart" -> return NlPropertyType.DIMENSION
      "itemShapeInsetTop" -> return NlPropertyType.DIMENSION
      "itemSpacing" -> return NlPropertyType.DIMENSION
      "itemPaddingBottom" -> return NlPropertyType.DIMENSION
      "itemPaddingTop" -> return NlPropertyType.DIMENSION
      "labelBehavior" -> return NlPropertyType.ENUM
      "labelStyle" -> return NlPropertyType.STYLE
      "layout_collapseMode" -> return NlPropertyType.ENUM
      "layout_collapseParallaxMultiplier" -> return NlPropertyType.FLOAT
      "layout_scrollEffect" -> return NlPropertyType.ENUM
      "layout_scrollFlags" -> return NlPropertyType.FLAGS
      "layout_scrollInterpolator" -> return NlPropertyType.INTERPOLATOR
      "liftOnScrollTargetViewId" -> return NlPropertyType.ID
      "lineSpacing" -> return NlPropertyType.DIMENSION
      "lineBreakStyle" -> return NlPropertyType.STYLE
      "lineBreakWordStyle" -> return NlPropertyType.STYLE
      "menuGravity" -> return NlPropertyType.ENUM
      "minHideDelay" -> return NlPropertyType.INTEGER
      "minSeparation" -> return NlPropertyType.DIMENSION
      "navigationIconTint" -> return NlPropertyType.COLOR
      "paddingBottomSystemWindowInsets" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "paddingLeftSystemWindowInsets" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "paddingRightSystemWindowInsets" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "placeholderText" -> return NlPropertyType.STRING
      "placeholderTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "placeholderTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "prefixText" -> return NlPropertyType.STRING
      "prefixTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "prefixTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "selectionRequired" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "shapeAppearance" -> return NlPropertyType.STYLE
      "shapeAppearanceOverlay" -> return NlPropertyType.STYLE
      "showAnimationBehavior" -> return NlPropertyType.ENUM
      "showDelay" -> return NlPropertyType.INTEGER
      "shrinkMotionSpec" -> return NlPropertyType.ANIMATOR
      "singleSelection" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "startIconCheckable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "startIconContentDescription" -> return NlPropertyType.STRING
      "startIconDrawable" -> return NlPropertyType.DRAWABLE
      "startIconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "startIconTintMode" -> return NlPropertyType.ENUM
      "statusBarForeground" -> return NlPropertyType.DRAWABLE
      "strokeColor" -> return NlPropertyType.COLOR_STATE_LIST
      "strokeWidth" -> return NlPropertyType.DIMENSION
      "subheaderColor" -> return NlPropertyType.COLOR_STATE_LIST
      "subheaderInsetEnd" -> return NlPropertyType.DIMENSION
      "subheaderInsetStart" -> return NlPropertyType.DIMENSION
      "subheaderTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "subtitleCentered" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "suffixText" -> return NlPropertyType.STRING
      "suffixTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "suffixTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "tabBackground" -> return NlPropertyType.DRAWABLE
      "tabContentStart" -> return NlPropertyType.DIMENSION
      "tabGravity" -> return NlPropertyType.ENUM
      "tabIconTint" -> return NlPropertyType.DRAWABLE
      "tabIconTintMode" -> return NlPropertyType.ENUM
      "tabIndicator" -> return NlPropertyType.DRAWABLE
      "tabIndicatorAnimationDuration" -> return NlPropertyType.INTEGER
      "tabIndicatorAnimationMode" -> return NlPropertyType.ENUM
      "tabIndicatorColor" -> return NlPropertyType.COLOR
      "tabIndicatorFullWidth" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "tabIndicatorGravity" -> return NlPropertyType.ENUM
      "tabIndicatorHeight" -> return NlPropertyType.DIMENSION
      "tabInlineLabel" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "tabMaxWidth" -> return NlPropertyType.DIMENSION
      "tabMinWidth" -> return NlPropertyType.DIMENSION
      "tabMode" -> return NlPropertyType.ENUM
      "tabPadding" -> return NlPropertyType.DIMENSION
      "tabPaddingBottom" -> return NlPropertyType.DIMENSION
      "tabPaddingEnd" -> return NlPropertyType.DIMENSION
      "tabPaddingStart" -> return NlPropertyType.DIMENSION
      "tabPaddingTop" -> return NlPropertyType.DIMENSION
      "tabRippleColor" -> return NlPropertyType.COLOR
      "tabSelectedTextColor" -> return NlPropertyType.COLOR
      "tabTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "tabTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "tabUnboundedRipple" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "tickColor" -> return NlPropertyType.COLOR_STATE_LIST
      "tickColorActive" -> return NlPropertyType.COLOR_STATE_LIST
      "tickColorInactive" -> return NlPropertyType.COLOR_STATE_LIST
      "titleCentered" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "titleCollapseMode" -> return NlPropertyType.ENUM
      "textEndPadding" -> return NlPropertyType.DIMENSION
      "textInputLayoutFocusedRectEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "textStartPadding" -> return NlPropertyType.DIMENSION
      "thumbColor" -> return NlPropertyType.COLOR_STATE_LIST
      "thumbElevation" -> return NlPropertyType.DIMENSION
      "thumbRadius" -> return NlPropertyType.DIMENSION
      "thumbStrokeColor" -> return NlPropertyType.COLOR_STATE_LIST
      "thumbStrokeWidth" -> return NlPropertyType.DIMENSION
      "tickVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "topInsetScrimEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "trackColor" -> return NlPropertyType.COLOR_STATE_LIST
      "trackColorActive" -> return NlPropertyType.COLOR_STATE_LIST
      "trackColorInactive" -> return NlPropertyType.COLOR_STATE_LIST
      "trackCornerRadius" -> return NlPropertyType.DIMENSION
      "trackHeight" -> return NlPropertyType.DIMENSION
      "trackThickness" -> return NlPropertyType.DIMENSION
      "useMaterialThemeColors" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "expanded" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "liftOnScroll" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "insetForeground" -> return NlPropertyType.DRAWABLE
      "itemBackground" -> return NlPropertyType.DRAWABLE
      "itemHorizontalPadding" -> return NlPropertyType.DIMENSION
      "itemIconPadding" -> return NlPropertyType.DIMENSION
      "itemIconTint" -> return NlPropertyType.DRAWABLE
      "itemTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "itemTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "itemVerticalPadding" -> return NlPropertyType.DIMENSION
      "menu" -> return NlPropertyType.MENU
      "boxBackgroundColor" -> return NlPropertyType.COLOR
      "boxBackgroundMode" -> return NlPropertyType.ENUM
      "boxCollapsedPaddingTop" -> return NlPropertyType.DIMENSION
      "boxCornerRadiusBottomEnd" -> return NlPropertyType.DIMENSION
      "boxCornerRadiusBottomStart" -> return NlPropertyType.DIMENSION
      "boxCornerRadiusTopEnd" -> return NlPropertyType.DIMENSION
      "boxCornerRadiusTopStart" -> return NlPropertyType.DIMENSION
      "boxStrokeColor" -> return NlPropertyType.COLOR
      "boxStrokeWidth" -> return NlPropertyType.DIMENSION
      "counterEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "counterMaxLength" -> return NlPropertyType.INTEGER
      "counterOverflowTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "counterTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "errorEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "errorTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "helperText" -> return NlPropertyType.STRING
      "helperTextEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "helperTextTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "hintAnimationEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hintEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hintTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "passwordToggleContentDescription" -> return NlPropertyType.STRING
      "passwordToggleDrawable" -> return NlPropertyType.DRAWABLE
      "passwordToggleEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "passwordToggleTint" -> return NlPropertyType.COLOR_STATE_LIST
      "passwordToggleTintMode" -> return NlPropertyType.ENUM
      "itemHorizontalTranslationEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "itemIconSize" -> return NlPropertyType.DIMENSION
      "itemTextAppearanceActive" -> return NlPropertyType.TEXT_APPEARANCE
      "itemTextAppearanceInactive" -> return NlPropertyType.TEXT_APPEARANCE
      "labelVisibilityMode" -> return NlPropertyType.ENUM
      "borderWidth" -> return NlPropertyType.DIMENSION
      "fabCustomSize" -> return NlPropertyType.DIMENSION
      "fabSize" -> return NlPropertyType.ENUM
      "hideMotionSpec" -> return NlPropertyType.ANIM
      "hoveredFocusedTranslationZ" -> return NlPropertyType.DIMENSION
      "maxImageSize" -> return NlPropertyType.DIMENSION
      "pressedTranslationZ" -> return NlPropertyType.DIMENSION
      "rippleColor" -> return NlPropertyType.COLOR_STATE_LIST
      "showMotionSpec" -> return NlPropertyType.ANIM
      "useCompatPadding" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "collapsedTitleGravity" -> return NlPropertyType.FLAGS
      "collapsedTitleTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "contentScrim" -> return NlPropertyType.DRAWABLE
      "expandedTitleGravity" -> return NlPropertyType.FLAGS
      "expandedTitleMargin" -> return NlPropertyType.DIMENSION
      "expandedTitleMarginBottom" -> return NlPropertyType.DIMENSION
      "expandedTitleMarginEnd" -> return NlPropertyType.DIMENSION
      "expandedTitleMarginStart" -> return NlPropertyType.DIMENSION
      "expandedTitleMarginTop" -> return NlPropertyType.DIMENSION
      "expandedTitleTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "scrimAnimationDuration" -> return NlPropertyType.INTEGER
      "scrimVisibleHeightTrigger" -> return NlPropertyType.DIMENSION
      "statusBarScrim" -> return NlPropertyType.DRAWABLE
      "titleEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "titlePositionInterpolator" -> return NlPropertyType.INTERPOLATOR
      "toolbarId" -> return NlPropertyType.ID

      // RecyclerView additions
      "fastScrollHorizontalThumbDrawable" -> return NlPropertyType.DRAWABLE
      "fastScrollHorizontalTrackDrawable" -> return NlPropertyType.DRAWABLE
      "fastScrollVerticalThumbDrawable" -> return NlPropertyType.DRAWABLE
      "fastScrollVerticalTrackDrawable" -> return NlPropertyType.DRAWABLE
      "layoutManager" -> return NlPropertyType.STRING // actually a class name
      "reverseLayout" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "spanCount" -> return NlPropertyType.INTEGER
      "stackFromEnd" -> return NlPropertyType.THREE_STATE_BOOLEAN

      // ConstraintLayout additions
      "barrierAllowsGoneWidgets" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "barrierDirection" -> return NlPropertyType.ENUM
      "barrierMargin" -> return NlPropertyType.DIMENSION
      "chainUseRtl" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "constraintSet" -> return NlPropertyType.ID
      "constraint_referenced_ids" -> return NlPropertyType.STRING
      "constraint_referenced_tags" -> return NlPropertyType.STRING
      "flow_firstHorizontalBias" -> return NlPropertyType.FLOAT
      "flow_firstHorizontalStyle" -> return NlPropertyType.ENUM
      "flow_firstVerticalBias" -> return NlPropertyType.FLOAT
      "flow_firstVerticalStyle" -> return NlPropertyType.ENUM
      "flow_horizontalAlign" -> return NlPropertyType.ENUM
      "flow_horizontalBias" -> return NlPropertyType.FLOAT
      "flow_horizontalGap" -> return NlPropertyType.DIMENSION
      "flow_horizontalStyle" -> return NlPropertyType.ENUM
      "flow_lastHorizontalBias" -> return NlPropertyType.FLOAT
      "flow_lastHorizontalStyle" -> return NlPropertyType.ENUM
      "flow_lastVerticalBias" -> return NlPropertyType.FLOAT
      "flow_lastVerticalStyle" -> return NlPropertyType.ENUM
      "flow_maxElementsWrap" -> return NlPropertyType.INTEGER
      "flow_verticalAlign" -> return NlPropertyType.ENUM
      "flow_verticalBias" -> return NlPropertyType.FLOAT
      "flow_verticalGap" -> return NlPropertyType.DIMENSION
      "flow_verticalStyle" -> return NlPropertyType.ENUM
      "flow_wrapMode" -> return NlPropertyType.ENUM
      "layout_constrainedHeight" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_constrainedWidth" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_constraintBaseline_creator" -> return NlPropertyType.INTEGER
      "layout_constraintBaseline_toBaselineOf" -> return NlPropertyType.ID
      "layout_constraintBottom_creator" -> return NlPropertyType.INTEGER
      "layout_constraintBottom_toBottomOf" -> return NlPropertyType.ID
      "layout_constraintBottom_toTopOf" -> return NlPropertyType.ID
      "layout_constraintCircle" -> return NlPropertyType.ID
      "layout_constraintCircleAngle" -> return NlPropertyType.INTEGER
      "layout_constraintCircleRadius" -> return NlPropertyType.DIMENSION
      "layout_constraintDimensionRatio" -> return NlPropertyType.STRING
      "layout_constraintEnd_toEndOf" -> return NlPropertyType.ID
      "layout_constraintEnd_toStartOf" -> return NlPropertyType.ID
      "layout_constraintGuide_begin" -> return NlPropertyType.DIMENSION
      "layout_constraintGuide_end" -> return NlPropertyType.DIMENSION
      "layout_constraintGuide_percent" -> return NlPropertyType.FRACTION
      "layout_constraintHeight_default" -> return NlPropertyType.ENUM
      "layout_constraintHeight_max" -> return NlPropertyType.DIMENSION
      "layout_constraintHeight_min" -> return NlPropertyType.DIMENSION
      "layout_constraintHeight_percent" -> return NlPropertyType.FRACTION
      "layout_constraintHorizontal_bias" -> return NlPropertyType.FRACTION
      "layout_constraintHorizontal_chainStyle" -> return NlPropertyType.ENUM
      "layout_constraintHorizontal_weight" -> return NlPropertyType.FLOAT
      "layout_constraintLeft_creator" -> return NlPropertyType.INTEGER
      "layout_constraintLeft_toLeftOf" -> return NlPropertyType.ID
      "layout_constraintLeft_toRightOf" -> return NlPropertyType.ID
      "layout_constraintRight_creator" -> return NlPropertyType.INTEGER
      "layout_constraintRight_toLeftOf" -> return NlPropertyType.ID
      "layout_constraintRight_toRightOf" -> return NlPropertyType.ID
      "layout_constraintStart_toEndOf" -> return NlPropertyType.ID
      "layout_constraintStart_toStartOf" -> return NlPropertyType.ID
      "layout_constraintTag" -> return NlPropertyType.STRING
      "layout_constraintTop_creator" -> return NlPropertyType.INTEGER
      "layout_constraintTop_toBottomOf" -> return NlPropertyType.ID
      "layout_constraintTop_toTopOf" -> return NlPropertyType.ID
      "layout_constraintVertical_bias" -> return NlPropertyType.FRACTION
      "layout_constraintVertical_chainStyle" -> return NlPropertyType.ENUM
      "layout_constraintVertical_weight" -> return NlPropertyType.FLOAT
      "layout_constraintWidth_default" -> return NlPropertyType.ENUM
      "layout_constraintWidth_max" -> return NlPropertyType.DIMENSION
      "layout_constraintWidth_min" -> return NlPropertyType.DIMENSION
      "layout_constraintWidth_percent" -> return NlPropertyType.FRACTION
      "layoutDescription" -> return NlPropertyType.XML
      "layout_editor_absoluteX" -> return NlPropertyType.DIMENSION
      "layout_editor_absoluteY" -> return NlPropertyType.DIMENSION
      "layout_goneMarginBottom" -> return NlPropertyType.DIMENSION
      "layout_goneMarginEnd" -> return NlPropertyType.DIMENSION
      "layout_goneMarginLeft" -> return NlPropertyType.DIMENSION
      "layout_goneMarginRight" -> return NlPropertyType.DIMENSION
      "layout_goneMarginStart" -> return NlPropertyType.DIMENSION
      "layout_goneMarginTop" -> return NlPropertyType.DIMENSION
      "layout_optimizationLevel" -> return NlPropertyType.FLAGS

      // AppCompat additions:
      "srcCompat" -> return NlPropertyType.DRAWABLE
      "drawableBottomCompat" -> return NlPropertyType.DRAWABLE
      "drawableEndCompat" -> return NlPropertyType.DRAWABLE
      "drawableLeftCompat" -> return NlPropertyType.DRAWABLE
      "drawableRightCompat" -> return NlPropertyType.DRAWABLE
      "drawableStartCompat" -> return NlPropertyType.DRAWABLE
      "drawableTopCompat" -> return NlPropertyType.DRAWABLE
      "titleMargins" -> return NlPropertyType.DIMENSION

      // tools attribute additions:
      "actionBarNavMode" -> return NlPropertyType.ENUM
      "context" -> return NlPropertyType.STRING
      "itemCount" -> return NlPropertyType.INTEGER
      "listfooter" -> return NlPropertyType.LAYOUT
      "listitem" -> return NlPropertyType.LAYOUT
      "listheader" -> return NlPropertyType.LAYOUT
      "showIn" -> return NlPropertyType.LAYOUT
      "targetApi" -> return NlPropertyType.STRING
      "viewBindingIgnore" -> return NlPropertyType.STRING
      "viewBindingType" -> return NlPropertyType.STRING
      "ignore" -> return NlPropertyType.STRING

      // Hand edited overrides for framework attributes:
      "alignmentMode" -> return NlPropertyType.ENUM
      "allowClickWhenDisabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "amPmBackgroundColor" -> return NlPropertyType.COLOR_STATE_LIST
      "amPmTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "animationResolution" -> return NlPropertyType.INTEGER
      "autoLink" -> return NlPropertyType.FLAGS
      "autoSizePresetSizes" -> return NlPropertyType.ARRAY  // Dimension array
      "autoSizeTextType" -> return NlPropertyType.ENUM
      "backgroundTintMode" -> return NlPropertyType.ENUM
      "breakStrategy" -> return NlPropertyType.ENUM
      "bufferType" -> return NlPropertyType.ENUM
      "buttonGravity" -> return NlPropertyType.FLAGS
      "buttonTintMode" -> return NlPropertyType.ENUM
      "capitalize" -> return NlPropertyType.ENUM
      "calendarTextColor" -> return NlPropertyType.COLOR
      "checkMarkGravity" -> return NlPropertyType.FLAGS
      "checkMarkTintMode" -> return NlPropertyType.ENUM
      "choiceMode" -> return NlPropertyType.ENUM
      "commitIcon" -> return NlPropertyType.DRAWABLE
      "completionHintView" -> return NlPropertyType.LAYOUT
      "clipToOutline" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "datePickerMode" -> return NlPropertyType.ENUM
      "dateTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "dayOfWeekBackground" -> return NlPropertyType.COLOR
      "dayOfWeekTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "descendantFocusability" -> return NlPropertyType.ENUM
      "drawableTintMode" -> return NlPropertyType.ENUM
      "drawingCacheQuality" -> return NlPropertyType.ENUM
      "ellipsize" -> return NlPropertyType.ENUM
      "fading" -> return NlPropertyType.FLAGS
      "fadingEdge" -> return NlPropertyType.FLAGS
      "fastScrollStyle" -> return NlPropertyType.STYLE
      "focusable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fontFamily" -> return NlPropertyType.FONT
      "foregroundGravity" -> return NlPropertyType.FLAGS
      "foregroundTintMode" -> return NlPropertyType.ENUM
      "gravity" -> return NlPropertyType.FLAGS
      "headerAmPmTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "headerMonthTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "headerDayOfMonthTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "headerTimeTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "headerYearTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "hyphenationFrequency" -> return NlPropertyType.ENUM
      "icon" -> return NlPropertyType.DRAWABLE
      "iconTintMode" -> return NlPropertyType.ENUM
      "ignoreGravity" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "imeOptions" -> return NlPropertyType.FLAGS
      "importantForAutofill" -> return NlPropertyType.FLAGS
      "importantForContentCapture" -> return NlPropertyType.FLAGS
      "inAnimation" -> return NlPropertyType.ANIM
      "indeterminateBehavior" -> return NlPropertyType.ENUM
      "indeterminateTintMode" -> return NlPropertyType.ENUM
      "inputType" -> return NlPropertyType.FLAGS
      "interpolator" -> return NlPropertyType.INTERPOLATOR
      "justificationMode" -> return NlPropertyType.ENUM
      "layout" -> return NlPropertyType.LAYOUT
      "layoutAnimation" -> return NlPropertyType.ANIM
      "layoutMode" -> return NlPropertyType.ENUM
      "layerType" -> return NlPropertyType.ENUM
      "layoutDirection" -> return NlPropertyType.ENUM
      "layout_gravity" -> return NlPropertyType.FLAGS
      "layout_height" -> return NlPropertyType.DIMENSION
      "layout_width" -> return NlPropertyType.DIMENSION
      "mode" -> return NlPropertyType.ENUM
      "monthTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "numeric" -> return NlPropertyType.FLAGS
      "orientation" -> return NlPropertyType.ENUM
      "outAnimation" -> return NlPropertyType.ANIM
      "outlineProvider" -> return NlPropertyType.ENUM
      "overScrollMode" -> return NlPropertyType.ENUM
      "persistentDrawingCache" -> return NlPropertyType.FLAGS
      "pointerIcon" -> return NlPropertyType.ENUM
      "popupTheme" -> return NlPropertyType.STYLE
      "progressTintMode" -> return NlPropertyType.ENUM
      "progressBackgroundTintMode" -> return NlPropertyType.ENUM
      "requiresFadingEdge" -> return NlPropertyType.FLAGS
      "secondaryProgressTintMode" -> return NlPropertyType.ENUM
      "scaleType" -> return NlPropertyType.ENUM
      "scrollbars" -> return NlPropertyType.FLAGS
      "scrollbarStyle" -> return NlPropertyType.ENUM
      "scrollIndicators" -> return NlPropertyType.FLAGS
      "showDividers" -> return NlPropertyType.FLAGS
      "spinnerMode" -> return NlPropertyType.ENUM
      "stateListAnimator" -> return NlPropertyType.ANIMATOR
      "stretchMode" -> return NlPropertyType.ENUM
      "subtitleTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "suggestionRowLayout" -> return NlPropertyType.LAYOUT
      "switchTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "textAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "textCursorDrawable" -> return NlPropertyType.DRAWABLE
      "textEditNoPasteWindowLayout" -> return NlPropertyType.LAYOUT
      "textEditPasteWindowLayout" -> return NlPropertyType.LAYOUT
      "textEditSideNoPasteWindowLayout" -> return NlPropertyType.LAYOUT
      "textEditSidePasteWindowLayout" -> return NlPropertyType.LAYOUT
      "textEditSuggestionItemLayout" -> return NlPropertyType.LAYOUT
      "textFontWeight" -> return NlPropertyType.INTEGER
      "textLocale" -> return NlPropertyType.STRING
      "textSelectHandle" -> return NlPropertyType.DRAWABLE
      "textSelectHandleLeft" -> return NlPropertyType.DRAWABLE
      "textSelectHandleRight" -> return NlPropertyType.DRAWABLE
      "textStyle" -> return NlPropertyType.FLAGS
      "theme" -> return NlPropertyType.STYLE
      "thumbTintMode" -> return NlPropertyType.ENUM
      "tickMarkTintMode" -> return NlPropertyType.ENUM
      "timePickerMode" -> return NlPropertyType.ENUM
      "tintMode" -> return NlPropertyType.ENUM
      "titleTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "trackTintMode" -> return NlPropertyType.ENUM
      "transcriptMode" -> return NlPropertyType.ENUM
      "typeface" -> return NlPropertyType.ENUM
      "verticalScrollbarPosition" -> return NlPropertyType.ENUM
      "visibility" -> return NlPropertyType.ENUM
      "weekDayTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "yearListItemTextAppearance" -> return NlPropertyType.TEXT_APPEARANCE
      "yearListSelectorColor" -> return NlPropertyType.COLOR

      // From generated file:
      "accessibilityEventTypes" -> return NlPropertyType.INTEGER
      "accessibilityFeedbackType" -> return NlPropertyType.INTEGER
      "accessibilityFlags" -> return NlPropertyType.INTEGER
      "accessibilityHeading" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "accessibilityLiveRegion" -> return NlPropertyType.INTEGER
      "accessibilityPaneTitle" -> return NlPropertyType.STRING
      "accessibilityTraversalAfter" -> return NlPropertyType.ID
      "accessibilityTraversalBefore" -> return NlPropertyType.ID
      "accountType" -> return NlPropertyType.STRING
      "action" -> return NlPropertyType.STRING
      "actionLayout" -> return NlPropertyType.ID
      "actionProviderClass" -> return NlPropertyType.STRING
      "actionViewClass" -> return NlPropertyType.STRING
      "activityOpenRemoteViewsEnterAnimation" -> return NlPropertyType.ID
      "addPrintersActivity" -> return NlPropertyType.STRING
      "addStatesFromChildren" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "adjustViewBounds" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "advancedPrintOptionsActivity" -> return NlPropertyType.STRING
      "allowBackup" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowClearUserData" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowEmbedded" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowParallelSyncs" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowSingleTap" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowTaskReparenting" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "allowUndo" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "alpha" -> return NlPropertyType.FLOAT
      "alphabeticModifiers" -> return NlPropertyType.INTEGER
      "alphabeticShortcut" -> return NlPropertyType.STRING
      "alwaysDrawnWithCache" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "alwaysFocusable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "alwaysRetainTaskState" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "ambientShadowAlpha" -> return NlPropertyType.FLOAT
      "animateFirstView" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "animateLayoutChanges" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "animateOnClick" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "animation" -> return NlPropertyType.ID
      "animationCache" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "animationDuration" -> return NlPropertyType.INTEGER
      "animationOrder" -> return NlPropertyType.INTEGER
      "anyDensity" -> return NlPropertyType.INTEGER
      "apduServiceBanner" -> return NlPropertyType.ID
      "appCategory" -> return NlPropertyType.INTEGER
      "appComponentFactory" -> return NlPropertyType.STRING
      "author" -> return NlPropertyType.ID
      "autoHandwritingEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autoRemoveFromRecents" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autoSizeMaxTextSize" -> return NlPropertyType.DIMENSION
      "autoSizeMinTextSize" -> return NlPropertyType.DIMENSION
      "autoSizeStepGranularity" -> return NlPropertyType.DIMENSION
      "autoStart" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autoText" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autoUrlDetect" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autoVerify" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "autofillHints" -> return NlPropertyType.STRING
      "background" -> return NlPropertyType.DRAWABLE
      "backgroundDimAmount" -> return NlPropertyType.FLOAT
      "backgroundLeft" -> return NlPropertyType.ID
      "backgroundRight" -> return NlPropertyType.ID
      "backgroundTint" -> return NlPropertyType.COLOR_STATE_LIST
      "backupInForeground" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "banner" -> return NlPropertyType.ID
      "baseline" -> return NlPropertyType.DIMENSION
      "baselineAlignBottom" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "baselineAligned" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "baselineAlignedChildIndex" -> return NlPropertyType.INTEGER
      "bitmap" -> return NlPropertyType.ID
      "borderBottom" -> return NlPropertyType.DIMENSION
      "borderLeft" -> return NlPropertyType.DIMENSION
      "borderRight" -> return NlPropertyType.DIMENSION
      "borderTop" -> return NlPropertyType.DIMENSION
      "bottomInsetScrimEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "bottomOffset" -> return NlPropertyType.DIMENSION
      "button" -> return NlPropertyType.DRAWABLE
      "buttonTint" -> return NlPropertyType.COLOR_STATE_LIST
      "cacheColorHint" -> return NlPropertyType.COLOR
      "calendarViewMode" -> return NlPropertyType.INTEGER
      "calendarViewShown" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canControlMagnification" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canPerformGestures" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canRequestFilterKeyEvents" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canRequestFingerprintGestures" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canRequestTouchExplorationMode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "canRetrieveWindowContent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "cantSaveState" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "category" -> return NlPropertyType.STRING
      "centerColor" -> return NlPropertyType.COLOR
      "centerX" -> return NlPropertyType.FLOAT
      "centerY" -> return NlPropertyType.FLOAT
      "certDigest" -> return NlPropertyType.STRING
      "checkMark" -> return NlPropertyType.DRAWABLE
      "checkMarkTint" -> return NlPropertyType.COLOR_STATE_LIST
      "checkable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "checkableBehavior" -> return NlPropertyType.INTEGER
      "checked" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "checkedButton" -> return NlPropertyType.ID
      "childDivider" -> return NlPropertyType.DRAWABLE
      "childIndicator" -> return NlPropertyType.DRAWABLE
      "childIndicatorEnd" -> return NlPropertyType.DIMENSION
      "childIndicatorLeft" -> return NlPropertyType.DIMENSION
      "childIndicatorRight" -> return NlPropertyType.DIMENSION
      "childIndicatorStart" -> return NlPropertyType.DIMENSION
      "classLoader" -> return NlPropertyType.STRING
      "clearTaskOnLaunch" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "clickColor" -> return NlPropertyType.COLOR
      "clickable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "clipChildren" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "clipToPadding" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "closeIcon" -> return NlPropertyType.DRAWABLE
      "collapseColumns" -> return NlPropertyType.STRING
      "collapseContentDescription" -> return NlPropertyType.STRING
      "collapseIcon" -> return NlPropertyType.DRAWABLE
      "color" -> return NlPropertyType.COLOR
      "colorBackground" -> return NlPropertyType.COLOR
      "colorEdgeEffect" -> return NlPropertyType.COLOR
      "colorMode" -> return NlPropertyType.INTEGER
      "colorPrimary" -> return NlPropertyType.COLOR
      "columnCount" -> return NlPropertyType.INTEGER
      "columnOrderPreserved" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "columnWidth" -> return NlPropertyType.DIMENSION
      "compatibleWidthLimitDp" -> return NlPropertyType.INTEGER
      "compileSdkVersion" -> return NlPropertyType.INTEGER
      "completionHint" -> return NlPropertyType.STRING
      "completionThreshold" -> return NlPropertyType.INTEGER
      "configChanges" -> return NlPropertyType.INTEGER
      "content" -> return NlPropertyType.ID
      "contentAuthority" -> return NlPropertyType.STRING
      "contentDescription" -> return NlPropertyType.STRING
      "contentInsetEnd" -> return NlPropertyType.DIMENSION
      "contentInsetEndWithActions" -> return NlPropertyType.DIMENSION
      "contentInsetLeft" -> return NlPropertyType.DIMENSION
      "contentInsetRight" -> return NlPropertyType.DIMENSION
      "contentInsetStart" -> return NlPropertyType.DIMENSION
      "contentInsetStartWithNavigation" -> return NlPropertyType.DIMENSION
      "contextClickable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "contextDescription" -> return NlPropertyType.ID
      "contextUri" -> return NlPropertyType.ID
      "controlX1" -> return NlPropertyType.FLOAT
      "controlX2" -> return NlPropertyType.FLOAT
      "controlY1" -> return NlPropertyType.FLOAT
      "controlY2" -> return NlPropertyType.FLOAT
      "countDown" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "cropToPadding" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "cursorVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "cycles" -> return NlPropertyType.FLOAT
      "data" -> return NlPropertyType.STRING
      "daySelectorColor" -> return NlPropertyType.COLOR_STATE_LIST
      "debuggable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "defaultFocusHighlightEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "defaultHeight" -> return NlPropertyType.DIMENSION
      "defaultQueryHint" -> return NlPropertyType.STRING
      "defaultToDeviceProtectedStorage" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "defaultValue" -> return NlPropertyType.LAYOUT
      "defaultWidth" -> return NlPropertyType.DIMENSION
      "dependency" -> return NlPropertyType.STRING
      "detachWallpaper" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "dial" -> return NlPropertyType.DRAWABLE
      "dialTint" -> return NlPropertyType.COLOR_STATE_LIST
      "dialTintMode" -> return NlPropertyType.ENUM
      "dialogIcon" -> return NlPropertyType.DRAWABLE
      "dialogLayout" -> return NlPropertyType.LAYOUT
      "dialogMessage" -> return NlPropertyType.STRING
      "dialogMode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "dialogTitle" -> return NlPropertyType.STRING
      "digits" -> return NlPropertyType.STRING
      "directBootAware" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "direction" -> return NlPropertyType.INTEGER
      "directionPriority" -> return NlPropertyType.INTEGER
      "disableChildrenWhenDisabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "disableDependentsState" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "disabledAlpha" -> return NlPropertyType.FLOAT
      "divider" -> return NlPropertyType.DRAWABLE
      "dividerColor" -> return NlPropertyType.COLOR_STATE_LIST
      "dividerHeight" -> return NlPropertyType.DIMENSION
      "dividerPadding" -> return NlPropertyType.DIMENSION
      "dividerThickness" -> return NlPropertyType.DIMENSION
      "documentLaunchMode" -> return NlPropertyType.INTEGER
      "drawSelectorOnTop" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "drawableAlpha" -> return NlPropertyType.INTEGER
      "drawableBottom" -> return NlPropertyType.DRAWABLE
      "drawableEnd" -> return NlPropertyType.DRAWABLE
      "drawableLeft" -> return NlPropertyType.DRAWABLE
      "drawablePadding" -> return NlPropertyType.DIMENSION
      "drawableRight" -> return NlPropertyType.DRAWABLE
      "drawableStart" -> return NlPropertyType.DRAWABLE
      "drawableTint" -> return NlPropertyType.COLOR_STATE_LIST
      "drawableTop" -> return NlPropertyType.DRAWABLE
      "dropDownAnchor" -> return NlPropertyType.ID
      "dropDownHeight" -> return NlPropertyType.DIMENSION
      "dropDownHorizontalOffset" -> return NlPropertyType.DIMENSION
      "dropDownSelector" -> return NlPropertyType.DRAWABLE
      "dropDownVerticalOffset" -> return NlPropertyType.DIMENSION
      "dropDownWidth" -> return NlPropertyType.DIMENSION
      "duplicateParentState" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "duration" -> return NlPropertyType.INTEGER
      "editable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "editorExtras" -> return NlPropertyType.ID
      "elegantTextHeight" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "elevation" -> return NlPropertyType.DIMENSION
      "ems" -> return NlPropertyType.INTEGER
      "enableVrMode" -> return NlPropertyType.STRING
      "enabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "endColor" -> return NlPropertyType.COLOR
      "endX" -> return NlPropertyType.FLOAT
      "endY" -> return NlPropertyType.FLOAT
      "endYear" -> return NlPropertyType.INTEGER
      "entries" -> return NlPropertyType.STRING_ARRAY
      "entryValues" -> return NlPropertyType.STRING_ARRAY
      "eventsInterceptionEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "excludeClass" -> return NlPropertyType.STRING
      "excludeFromRecents" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "excludeId" -> return NlPropertyType.ID
      "excludeName" -> return NlPropertyType.STRING
      "expandActivityOverflowButtonDrawable" -> return NlPropertyType.DRAWABLE
      "exported" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "externalRouteEnabledDrawable" -> return NlPropertyType.DRAWABLE
      "externalService" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "extraTension" -> return NlPropertyType.FLOAT
      "extractNativeLibs" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "factor" -> return NlPropertyType.FLOAT
      "fadeDuration" -> return NlPropertyType.INTEGER
      "fadeEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fadeOffset" -> return NlPropertyType.INTEGER
      "fadeScrollbars" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fadingEdgeLength" -> return NlPropertyType.DIMENSION
      "fadingMode" -> return NlPropertyType.INTEGER
      "fallbackLineSpacing" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fastScrollAlwaysVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fastScrollEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fillAfter" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fillBefore" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fillEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fillViewport" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "filterTouchesWhenObscured" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "finishOnCloseSystemDialogs" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "finishOnTaskLaunch" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "firstBaselineToTopHeight" -> return NlPropertyType.DIMENSION
      "firstDayOfWeek" -> return NlPropertyType.INTEGER
      "fitsSystemWindows" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "flipInterval" -> return NlPropertyType.INTEGER
      "focusableInTouchMode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "focusedByDefault" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "focusedMonthDateColor" -> return NlPropertyType.COLOR
      "font" -> return NlPropertyType.STRING
      "fontFeatureSettings" -> return NlPropertyType.STRING
      "fontProviderAuthority" -> return NlPropertyType.STRING
      "fontProviderCerts" -> return NlPropertyType.ID
      "fontProviderPackage" -> return NlPropertyType.STRING
      "fontProviderQuery" -> return NlPropertyType.STRING
      "fontStyle" -> return NlPropertyType.INTEGER
      "fontVariationSettings" -> return NlPropertyType.STRING
      "fontWeight" -> return NlPropertyType.INTEGER
      "footerDividersEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "forceDarkAllowed" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "forceHasOverlappingRendering" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "foreground" -> return NlPropertyType.DRAWABLE
      "foregroundInsidePadding" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "foregroundTint" -> return NlPropertyType.COLOR_STATE_LIST
      "format" -> return NlPropertyType.STRING
      "format12Hour" -> return NlPropertyType.STRING
      "format24Hour" -> return NlPropertyType.STRING
      "fraction" -> return NlPropertyType.FLOAT
      "fragment" -> return NlPropertyType.STRING
      "fragmentAllowEnterTransitionOverlap" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fragmentAllowReturnTransitionOverlap" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "freezesText" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "fromAlpha" -> return NlPropertyType.FLOAT
      "fromDegrees" -> return NlPropertyType.FLOAT
      "fromScene" -> return NlPropertyType.ID
      "fullBackupOnly" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "functionalTest" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "gestureColor" -> return NlPropertyType.COLOR
      "gestureStrokeAngleThreshold" -> return NlPropertyType.FLOAT
      "gestureStrokeLengthThreshold" -> return NlPropertyType.FLOAT
      "gestureStrokeSquarenessThreshold" -> return NlPropertyType.FLOAT
      "gestureStrokeType" -> return NlPropertyType.INTEGER
      "gestureStrokeWidth" -> return NlPropertyType.FLOAT
      "glEsVersion" -> return NlPropertyType.INTEGER
      "goIcon" -> return NlPropertyType.DRAWABLE
      "gradientRadius" -> return NlPropertyType.FLOAT
      "grantUriPermissions" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "groupIndicator" -> return NlPropertyType.DRAWABLE
      "hand_hour" -> return NlPropertyType.DRAWABLE
      "hand_hourTint" -> return NlPropertyType.COLOR_STATE_LIST
      "hand_hourTintMode" -> return NlPropertyType.ENUM
      "hand_minute" -> return NlPropertyType.DRAWABLE
      "hand_minuteTint" -> return NlPropertyType.COLOR_STATE_LIST
      "hand_minuteTintMode" -> return NlPropertyType.ENUM
      "hand_second" -> return NlPropertyType.DRAWABLE
      "hand_secondTint" -> return NlPropertyType.COLOR_STATE_LIST
      "hand_secondTintMode" -> return NlPropertyType.ENUM
      "handle" -> return NlPropertyType.ID
      "handleProfiling" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hapticFeedbackEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hardwareAccelerated" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hasCode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "headerBackground" -> return NlPropertyType.DRAWABLE
      "headerDividersEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "headerLayout" -> return NlPropertyType.LAYOUT
      "headerRemoveIconIfEmpty" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "headerTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "height" -> return NlPropertyType.DIMENSION
      "hideWheelUntilFocused" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "hint" -> return NlPropertyType.STRING
      "horizontalProgressLayout" -> return NlPropertyType.ID
      "horizontalSpacing" -> return NlPropertyType.DIMENSION
      "hotSpotX" -> return NlPropertyType.DIMENSION
      "hotSpotY" -> return NlPropertyType.DIMENSION
      "iconSpaceReserved" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "iconTint" -> return NlPropertyType.COLOR_STATE_LIST
      "iconifiedByDefault" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "id" -> return NlPropertyType.ID
      "imeActionId" -> return NlPropertyType.INTEGER
      "imeActionLabel" -> return NlPropertyType.STRING
      "imeFullscreenBackground" -> return NlPropertyType.DRAWABLE
      "immersive" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "importantForAccessibility" -> return NlPropertyType.INTEGER
      "includeFontPadding" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "includeInGlobalSearch" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "indeterminate" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "indeterminateDrawable" -> return NlPropertyType.DRAWABLE
      "indeterminateDuration" -> return NlPropertyType.INTEGER
      "indeterminateOnly" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "indeterminateTint" -> return NlPropertyType.COLOR_STATE_LIST
      "indicatorEnd" -> return NlPropertyType.DIMENSION
      "indicatorLeft" -> return NlPropertyType.DIMENSION
      "indicatorRight" -> return NlPropertyType.DIMENSION
      "indicatorStart" -> return NlPropertyType.DIMENSION
      "inflatedId" -> return NlPropertyType.ID
      "initOrder" -> return NlPropertyType.INTEGER
      "initialActivityCount" -> return NlPropertyType.INTEGER
      "inputMethod" -> return NlPropertyType.STRING
      "installLocation" -> return NlPropertyType.INTEGER
      "internalLayout" -> return NlPropertyType.ID
      "internalMaxHeight" -> return NlPropertyType.DIMENSION
      "internalMaxWidth" -> return NlPropertyType.DIMENSION
      "internalMinHeight" -> return NlPropertyType.DIMENSION
      "internalMinWidth" -> return NlPropertyType.DIMENSION
      "isAlwaysSyncable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isDefault" -> return NlPropertyType.ID
      "isGame" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isIndicator" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isScrollContainer" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isStatic" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isVrOnly" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isolatedProcess" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "isolatedSplits" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "itemColor" -> return NlPropertyType.COLOR
      "itemLayout" -> return NlPropertyType.ID
      "keepScreenOn" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "key" -> return NlPropertyType.STRING
      "keyBackground" -> return NlPropertyType.DRAWABLE
      "keyPreviewHeight" -> return NlPropertyType.DIMENSION
      "keyPreviewLayout" -> return NlPropertyType.ID
      "keyPreviewOffset" -> return NlPropertyType.DIMENSION
      "keyTextColor" -> return NlPropertyType.COLOR
      "keyTextSize" -> return NlPropertyType.DIMENSION
      "keyboardNavigationCluster" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "keycode" -> return NlPropertyType.INTEGER
      "killAfterRestore" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "label" -> return NlPropertyType.ID
      "labelFor" -> return NlPropertyType.ID
      "labelTextSize" -> return NlPropertyType.DIMENSION
      "largeHeap" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "largeScreens" -> return NlPropertyType.INTEGER
      "largestWidthLimitDp" -> return NlPropertyType.INTEGER
      "lastBaselineToBottomHeight" -> return NlPropertyType.DIMENSION
      "launchMode" -> return NlPropertyType.INTEGER
      "layout_above" -> return NlPropertyType.ID
      "layout_alignBaseline" -> return NlPropertyType.ID
      "layout_alignBottom" -> return NlPropertyType.ID
      "layout_alignEnd" -> return NlPropertyType.ID
      "layout_alignLeft" -> return NlPropertyType.ID
      "layout_alignParentBottom" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentEnd" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentLeft" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentRight" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentStart" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignParentTop" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_alignRight" -> return NlPropertyType.ID
      "layout_alignStart" -> return NlPropertyType.ID
      "layout_alignTop" -> return NlPropertyType.ID
      "layout_alignWithParentIfMissing" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_below" -> return NlPropertyType.ID
      "layout_centerHorizontal" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_centerInParent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_centerVertical" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_column" -> return NlPropertyType.INTEGER
      "layout_columnSpan" -> return NlPropertyType.INTEGER
      "layout_columnWeight" -> return NlPropertyType.FLOAT
      "layout_margin" -> return NlPropertyType.DIMENSION
      "layout_marginBottom" -> return NlPropertyType.DIMENSION
      "layout_marginEnd" -> return NlPropertyType.DIMENSION
      "layout_marginHorizontal" -> return NlPropertyType.DIMENSION
      "layout_marginLeft" -> return NlPropertyType.DIMENSION
      "layout_marginRight" -> return NlPropertyType.DIMENSION
      "layout_marginStart" -> return NlPropertyType.DIMENSION
      "layout_marginTop" -> return NlPropertyType.DIMENSION
      "layout_marginVertical" -> return NlPropertyType.DIMENSION
      "layout_removeBorders" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "layout_row" -> return NlPropertyType.INTEGER
      "layout_rowSpan" -> return NlPropertyType.INTEGER
      "layout_rowWeight" -> return NlPropertyType.FLOAT
      "layout_span" -> return NlPropertyType.INTEGER
      "layout_toEndOf" -> return NlPropertyType.ID
      "layout_toLeftOf" -> return NlPropertyType.ID
      "layout_toRightOf" -> return NlPropertyType.ID
      "layout_toStartOf" -> return NlPropertyType.ID
      "layout_weight" -> return NlPropertyType.FLOAT
      "layout_x" -> return NlPropertyType.DIMENSION
      "layout_y" -> return NlPropertyType.DIMENSION
      "legacyLayout" -> return NlPropertyType.ID
      "letterSpacing" -> return NlPropertyType.FLOAT
      "lightRadius" -> return NlPropertyType.DIMENSION
      "lightY" -> return NlPropertyType.DIMENSION
      "lightZ" -> return NlPropertyType.DIMENSION
      "lineHeight" -> return NlPropertyType.DIMENSION
      "lineSpacingExtra" -> return NlPropertyType.DIMENSION
      "lineSpacingMultiplier" -> return NlPropertyType.FLOAT
      "lines" -> return NlPropertyType.INTEGER
      "linksClickable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "listSelector" -> return NlPropertyType.DRAWABLE
      "lockTaskMode" -> return NlPropertyType.INTEGER
      "logo" -> return NlPropertyType.DRAWABLE
      "logoDescription" -> return NlPropertyType.STRING
      "longClickable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "loopViews" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "marqueeRepeatLimit" -> return NlPropertyType.INTEGER
      "matchOrder" -> return NlPropertyType.STRING
      "max" -> return NlPropertyType.INTEGER
      "maxAspectRatio" -> return NlPropertyType.FLOAT
      "maxButtonHeight" -> return NlPropertyType.DIMENSION
      "maxDate" -> return NlPropertyType.STRING
      "maxEms" -> return NlPropertyType.INTEGER
      "maxHeight" -> return NlPropertyType.DIMENSION
      "maxLength" -> return NlPropertyType.INTEGER
      "maxLines" -> return NlPropertyType.INTEGER
      "maxRecents" -> return NlPropertyType.INTEGER
      "maxWidth" -> return NlPropertyType.DIMENSION
      "maximumAngle" -> return NlPropertyType.FLOAT
      "measureAllChildren" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "measureWithLargestChild" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "mediaRouteTypes" -> return NlPropertyType.INTEGER
      "menuCategory" -> return NlPropertyType.INTEGER
      "mimeType" -> return NlPropertyType.STRING
      "min" -> return NlPropertyType.INTEGER
      "minDate" -> return NlPropertyType.STRING
      "minEms" -> return NlPropertyType.INTEGER
      "minHeight" -> return NlPropertyType.DIMENSION
      "minLines" -> return NlPropertyType.INTEGER
      "minWidth" -> return NlPropertyType.DIMENSION
      "minimumHorizontalAngle" -> return NlPropertyType.FLOAT
      "minimumVerticalAngle" -> return NlPropertyType.FLOAT
      "mirrorForRtl" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "multiArch" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "multiprocess" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "name" -> return NlPropertyType.STRING
      "navigationBarColor" -> return NlPropertyType.COLOR
      "navigationButtonStyle" -> return NlPropertyType.ID
      "navigationContentDescription" -> return NlPropertyType.STRING
      "navigationIcon" -> return NlPropertyType.DRAWABLE
      "negativeButtonText" -> return NlPropertyType.STRING
      "nestedScrollingEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "networkSecurityConfig" -> return NlPropertyType.ID
      "nextClusterForward" -> return NlPropertyType.ID
      "nextFocusDown" -> return NlPropertyType.ID
      "nextFocusForward" -> return NlPropertyType.ID
      "nextFocusLeft" -> return NlPropertyType.ID
      "nextFocusRight" -> return NlPropertyType.ID
      "nextFocusUp" -> return NlPropertyType.ID
      "noHistory" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "normalScreens" -> return NlPropertyType.INTEGER
      "notificationTimeout" -> return NlPropertyType.INTEGER
      "numColumns" -> return NlPropertyType.INTEGER
      "numStars" -> return NlPropertyType.INTEGER
      "numbersBackgroundColor" -> return NlPropertyType.COLOR
      "numbersInnerTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "numbersSelectorColor" -> return NlPropertyType.COLOR_STATE_LIST
      "numbersTextColor" -> return NlPropertyType.COLOR_STATE_LIST
      "numericModifiers" -> return NlPropertyType.INTEGER
      "numericShortcut" -> return NlPropertyType.STRING
      "offset" -> return NlPropertyType.FLOAT
      "onClick" -> return NlPropertyType.STRING
      "order" -> return NlPropertyType.INTEGER
      "orderInCategory" -> return NlPropertyType.INTEGER
      "ordering" -> return NlPropertyType.INTEGER
      "orderingFromXml" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "outlineAmbientShadowColor" -> return NlPropertyType.COLOR
      "outlineSpotShadowColor" -> return NlPropertyType.COLOR
      "overScrollFooter" -> return NlPropertyType.DRAWABLE
      "overScrollHeader" -> return NlPropertyType.DRAWABLE
      "overlapAnchor" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "packageNames" -> return NlPropertyType.STRING
      "padding" -> return NlPropertyType.DIMENSION
      "paddingBottom" -> return NlPropertyType.DIMENSION
      "paddingEnd" -> return NlPropertyType.DIMENSION
      "paddingHorizontal" -> return NlPropertyType.DIMENSION
      "paddingLeft" -> return NlPropertyType.DIMENSION
      "paddingRight" -> return NlPropertyType.DIMENSION
      "paddingStart" -> return NlPropertyType.DIMENSION
      "paddingTop" -> return NlPropertyType.DIMENSION
      "paddingVertical" -> return NlPropertyType.DIMENSION
      "password" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "pathData" -> return NlPropertyType.STRING
      "patternPathData" -> return NlPropertyType.STRING
      "permissionFlags" -> return NlPropertyType.INTEGER
      "permissionGroup" -> return NlPropertyType.STRING
      "permissionGroupFlags" -> return NlPropertyType.INTEGER
      "persistableMode" -> return NlPropertyType.INTEGER
      "persistent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "persistentWhenFeatureAvailable" -> return NlPropertyType.STRING
      "phoneNumber" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "popupAnimationStyle" -> return NlPropertyType.ID
      "popupBackground" -> return NlPropertyType.DRAWABLE
      "popupElevation" -> return NlPropertyType.DIMENSION
      "popupEnterTransition" -> return NlPropertyType.ID
      "popupExitTransition" -> return NlPropertyType.ID
      "popupLayout" -> return NlPropertyType.ID
      "position" -> return NlPropertyType.INTEGER
      "positiveButtonText" -> return NlPropertyType.STRING
      "preferKeepClear" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "priority" -> return NlPropertyType.INTEGER
      "privateImeOptions" -> return NlPropertyType.STRING
      "process" -> return NlPropertyType.STRING
      "progress" -> return NlPropertyType.INTEGER
      "progressBackgroundTint" -> return NlPropertyType.COLOR_STATE_LIST
      "progressDrawable" -> return NlPropertyType.DRAWABLE
      "progressLayout" -> return NlPropertyType.ID
      "progressTint" -> return NlPropertyType.COLOR_STATE_LIST
      "prompt" -> return NlPropertyType.STRING
      "propertyName" -> return NlPropertyType.STRING
      "propertyXName" -> return NlPropertyType.STRING
      "propertyYName" -> return NlPropertyType.STRING
      "protectionLevel" -> return NlPropertyType.INTEGER
      "queryActionMsg" -> return NlPropertyType.STRING
      "queryAfterZeroResults" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "queryBackground" -> return NlPropertyType.DRAWABLE
      "queryHint" -> return NlPropertyType.STRING
      "quickContactBadgeOverlay" -> return NlPropertyType.DRAWABLE
      "rating" -> return NlPropertyType.FLOAT
      "recognitionService" -> return NlPropertyType.STRING
      "recreateOnConfigChanges" -> return NlPropertyType.INTEGER
      "recycleEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "relinquishTaskIdentity" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "reparent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "reparentWithOverlay" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "repeatCount" -> return NlPropertyType.INTEGER
      "repeatMode" -> return NlPropertyType.INTEGER
      "reqFiveWayNav" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "reqHardKeyboard" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "reqKeyboardType" -> return NlPropertyType.INTEGER
      "reqNavigation" -> return NlPropertyType.INTEGER
      "reqTouchScreen" -> return NlPropertyType.INTEGER
      "request" -> return NlPropertyType.ID
      "requireDeviceUnlock" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "required" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "requiredAccountType" -> return NlPropertyType.STRING
      "requiredForAllUsers" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "requiredSystemPropertyName" -> return NlPropertyType.STRING
      "requiredSystemPropertyValue" -> return NlPropertyType.STRING
      "requiresSmallestWidthDp" -> return NlPropertyType.INTEGER
      "resOutColor" -> return NlPropertyType.COLOR
      "resizeClip" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "resizeable" -> return NlPropertyType.INTEGER
      "resizeableActivity" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "restoreAnyVersion" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "restrictedAccountType" -> return NlPropertyType.STRING
      "restrictionType" -> return NlPropertyType.INTEGER
      "resumeWhilePausing" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "revisionCode" -> return NlPropertyType.INTEGER
      "ringtoneType" -> return NlPropertyType.FLAGS
      "rotation" -> return NlPropertyType.FLOAT
      "rotationAnimation" -> return NlPropertyType.INTEGER
      "rotationX" -> return NlPropertyType.FLOAT
      "rotationY" -> return NlPropertyType.FLOAT
      "roundIcon" -> return NlPropertyType.ID
      "rowCount" -> return NlPropertyType.INTEGER
      "rowOrderPreserved" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "saveEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "scaleX" -> return NlPropertyType.FLOAT
      "scaleY" -> return NlPropertyType.FLOAT
      "screenLayout" -> return NlPropertyType.ID
      "screenOrientation" -> return NlPropertyType.INTEGER
      "screenReaderFocusable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "scrollHorizontally" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "scrollX" -> return NlPropertyType.DIMENSION
      "scrollY" -> return NlPropertyType.DIMENSION
      "scrollbarAlwaysDrawHorizontalTrack" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "scrollbarAlwaysDrawVerticalTrack" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "scrollbarDefaultDelayBeforeFade" -> return NlPropertyType.INTEGER
      "scrollbarFadeDuration" -> return NlPropertyType.INTEGER
      "scrollbarSize" -> return NlPropertyType.DIMENSION
      "scrollbarThumbHorizontal" -> return NlPropertyType.DRAWABLE
      "scrollbarThumbVertical" -> return NlPropertyType.DRAWABLE
      "scrollbarTrackHorizontal" -> return NlPropertyType.DRAWABLE
      "scrollbarTrackVertical" -> return NlPropertyType.DRAWABLE
      "scrollingCache" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "searchButtonText" -> return NlPropertyType.ID
      "searchHintIcon" -> return NlPropertyType.DRAWABLE
      "searchIcon" -> return NlPropertyType.DRAWABLE
      "searchKeyphrase" -> return NlPropertyType.STRING
      "searchKeyphraseId" -> return NlPropertyType.INTEGER
      "searchKeyphraseRecognitionFlags" -> return NlPropertyType.INTEGER
      "searchKeyphraseSupportedLocales" -> return NlPropertyType.STRING
      "searchMode" -> return NlPropertyType.INTEGER
      "searchSettingsDescription" -> return NlPropertyType.ID
      "searchSuggestAuthority" -> return NlPropertyType.STRING
      "searchSuggestIntentAction" -> return NlPropertyType.STRING
      "searchSuggestIntentData" -> return NlPropertyType.STRING
      "searchSuggestPath" -> return NlPropertyType.STRING
      "searchSuggestSelection" -> return NlPropertyType.STRING
      "searchSuggestThreshold" -> return NlPropertyType.INTEGER
      "secondaryProgress" -> return NlPropertyType.INTEGER
      "secondaryProgressTint" -> return NlPropertyType.COLOR_STATE_LIST
      "selectAllOnFocus" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "selectable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "selectedDateVerticalBar" -> return NlPropertyType.DRAWABLE
      "selectedWeekBackgroundColor" -> return NlPropertyType.COLOR
      "selectionDivider" -> return NlPropertyType.DRAWABLE
      "selectionDividerHeight" -> return NlPropertyType.DIMENSION
      "selectionDividersDistance" -> return NlPropertyType.DIMENSION
      "sessionService" -> return NlPropertyType.STRING
      "settingsActivity" -> return NlPropertyType.STRING
      "shadowColor" -> return NlPropertyType.COLOR
      "shadowDx" -> return NlPropertyType.FLOAT
      "shadowDy" -> return NlPropertyType.FLOAT
      "shadowRadius" -> return NlPropertyType.FLOAT
      "shareInterpolator" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "sharedUserLabel" -> return NlPropertyType.ID
      "shouldDisableView" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showAsAction" -> return NlPropertyType.INTEGER
      "showDefault" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showForAllUsers" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showMetadataInPreview" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showOnLockScreen" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showSilent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showText" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showWeekNumber" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "showWhenLocked" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "shownWeekCount" -> return NlPropertyType.INTEGER
      "shrinkColumns" -> return NlPropertyType.STRING
      "singleLine" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "singleLineTitle" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "singleUser" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "slideEdge" -> return NlPropertyType.INTEGER
      "smallScreens" -> return NlPropertyType.INTEGER
      "smoothScrollbar" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "solidColor" -> return NlPropertyType.COLOR
      "soundEffectsEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "spacing" -> return NlPropertyType.DIMENSION
      "spinnersShown" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "splitMotionEvents" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "splitTrack" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "spotShadowAlpha" -> return NlPropertyType.FLOAT
      "src" -> return NlPropertyType.DRAWABLE
      "stackFromBottom" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "startColor" -> return NlPropertyType.COLOR
      "startDelay" -> return NlPropertyType.INTEGER
      "startOffset" -> return NlPropertyType.INTEGER
      "startX" -> return NlPropertyType.FLOAT
      "startY" -> return NlPropertyType.FLOAT
      "startYear" -> return NlPropertyType.INTEGER
      "stateNotNeeded" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "statusBarColor" -> return NlPropertyType.COLOR
      "stepSize" -> return NlPropertyType.FLOAT
      "stopWithTask" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "streamType" -> return NlPropertyType.INTEGER
      "stretchColumns" -> return NlPropertyType.STRING
      "submitBackground" -> return NlPropertyType.DRAWABLE
      "subtitle" -> return NlPropertyType.STRING
      "subtitleTextColor" -> return NlPropertyType.COLOR
      "suggestActionMsg" -> return NlPropertyType.STRING
      "suggestActionMsgColumn" -> return NlPropertyType.STRING
      "summary" -> return NlPropertyType.STRING
      "summaryOff" -> return NlPropertyType.STRING
      "summaryOn" -> return NlPropertyType.STRING
      "supportsAmbientMode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsAssist" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsLaunchVoiceAssistFromKeyguard" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsLocalInteraction" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsPictureInPicture" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsRtl" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsSwitchingToNextInputMethod" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "supportsUploading" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "switchMinWidth" -> return NlPropertyType.DIMENSION
      "switchPadding" -> return NlPropertyType.DIMENSION
      "switchTextOff" -> return NlPropertyType.STRING
      "switchTextOn" -> return NlPropertyType.STRING
      "syncable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "systemUserOnly" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "tabLayout" -> return NlPropertyType.ID
      "tabStripEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "tabStripLeft" -> return NlPropertyType.DRAWABLE
      "tabStripRight" -> return NlPropertyType.DRAWABLE
      "tag" -> return NlPropertyType.STRING
      "targetClass" -> return NlPropertyType.STRING
      "targetId" -> return NlPropertyType.ID
      "targetName" -> return NlPropertyType.STRING
      "targetPackage" -> return NlPropertyType.STRING
      "targetProcesses" -> return NlPropertyType.STRING
      "targetSandboxVersion" -> return NlPropertyType.INTEGER
      "taskAffinity" -> return NlPropertyType.STRING
      "tension" -> return NlPropertyType.FLOAT
      "testOnly" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "text" -> return NlPropertyType.STRING
      "textAlignment" -> return NlPropertyType.INTEGER
      "textAllCaps" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "textColor" -> return NlPropertyType.COLOR_STATE_LIST
      "textColorHighlight" -> return NlPropertyType.COLOR
      "textColorHint" -> return NlPropertyType.COLOR_STATE_LIST
      "textColorLink" -> return NlPropertyType.COLOR_STATE_LIST
      "textDirection" -> return NlPropertyType.INTEGER
      "textEditSuggestionContainerLayout" -> return NlPropertyType.ID
      "textEditSuggestionHighlightStyle" -> return NlPropertyType.ID
      "textFilterEnabled" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "textIsSelectable" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "textOff" -> return NlPropertyType.STRING
      "textOn" -> return NlPropertyType.STRING
      "textScaleX" -> return NlPropertyType.FLOAT
      "textSize" -> return NlPropertyType.DIMENSION
      "textUnderlineColor" -> return NlPropertyType.COLOR
      "textUnderlineThickness" -> return NlPropertyType.DIMENSION
      "thumb" -> return NlPropertyType.DRAWABLE
      "thumbDrawable" -> return NlPropertyType.DRAWABLE
      "thumbMinHeight" -> return NlPropertyType.DIMENSION
      "thumbMinWidth" -> return NlPropertyType.DIMENSION
      "thumbOffset" -> return NlPropertyType.DIMENSION
      "thumbPosition" -> return NlPropertyType.INTEGER
      "thumbTextPadding" -> return NlPropertyType.DIMENSION
      "thumbTint" -> return NlPropertyType.COLOR_STATE_LIST
      "thumbnail" -> return NlPropertyType.ID
      "tickMark" -> return NlPropertyType.DRAWABLE
      "tickMarkTint" -> return NlPropertyType.COLOR_STATE_LIST
      "tileMode" -> return NlPropertyType.INTEGER
      "timeZone" -> return NlPropertyType.STRING
      "tint" -> return NlPropertyType.COLOR_STATE_LIST
      "title" -> return NlPropertyType.STRING
      "titleCondensed" -> return NlPropertyType.STRING
      "titleMargin" -> return NlPropertyType.DIMENSION
      "titleMarginBottom" -> return NlPropertyType.DIMENSION
      "titleMarginEnd" -> return NlPropertyType.DIMENSION
      "titleMarginStart" -> return NlPropertyType.DIMENSION
      "titleMarginTop" -> return NlPropertyType.DIMENSION
      "titleTextColor" -> return NlPropertyType.COLOR
      "toAlpha" -> return NlPropertyType.FLOAT
      "toDegrees" -> return NlPropertyType.FLOAT
      "toScene" -> return NlPropertyType.ID
      "tooltipText" -> return NlPropertyType.STRING
      "topOffset" -> return NlPropertyType.DIMENSION
      "touchscreenBlocksFocus" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "track" -> return NlPropertyType.DRAWABLE
      "trackDrawable" -> return NlPropertyType.DRAWABLE
      "trackTint" -> return NlPropertyType.COLOR_STATE_LIST
      "transformPivotX" -> return NlPropertyType.DIMENSION
      "transformPivotY" -> return NlPropertyType.DIMENSION
      "transition" -> return NlPropertyType.ID
      "transitionGroup" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "transitionName" -> return NlPropertyType.STRING
      "transitionOrdering" -> return NlPropertyType.INTEGER
      "transitionVisibilityMode" -> return NlPropertyType.INTEGER
      "translationX" -> return NlPropertyType.DIMENSION
      "translationY" -> return NlPropertyType.DIMENSION
      "translationZ" -> return NlPropertyType.DIMENSION
      "ttcIndex" -> return NlPropertyType.INTEGER
      "turnScreenOn" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "type" -> return NlPropertyType.INTEGER
      "uiOptions" -> return NlPropertyType.INTEGER
      "uncertainGestureColor" -> return NlPropertyType.COLOR
      "unfocusedMonthDateColor" -> return NlPropertyType.COLOR
      "unselectedAlpha" -> return NlPropertyType.FLOAT
      "useDefaultMargins" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "useDisabledAlpha" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "userVisible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "usesCleartextTraffic" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "value" -> return NlPropertyType.FLOAT
      "values" -> return NlPropertyType.ARRAY  // array of float for com.google.android.material.slider.RangeSlider
      "valueFrom" -> return NlPropertyType.FLOAT
      "valueTo" -> return NlPropertyType.FLOAT
      "valueType" -> return NlPropertyType.INTEGER
      "version" -> return NlPropertyType.INTEGER
      "versionCode" -> return NlPropertyType.INTEGER
      "versionCodeMajor" -> return NlPropertyType.INTEGER
      "versionMajor" -> return NlPropertyType.INTEGER
      "verticalCorrection" -> return NlPropertyType.DIMENSION
      "verticalSpacing" -> return NlPropertyType.DIMENSION
      "virtualButtonPressedDrawable" -> return NlPropertyType.DRAWABLE
      "visible" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "visibleToInstantApps" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "vmSafeMode" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "voiceIcon" -> return NlPropertyType.DRAWABLE
      "voiceLanguage" -> return NlPropertyType.ID
      "voiceLanguageModel" -> return NlPropertyType.ID
      "voiceMaxResults" -> return NlPropertyType.INTEGER
      "voicePromptText" -> return NlPropertyType.ID
      "voiceSearchMode" -> return NlPropertyType.INTEGER
      "weekNumberColor" -> return NlPropertyType.COLOR
      "weekSeparatorLineColor" -> return NlPropertyType.COLOR
      "weightSum" -> return NlPropertyType.FLOAT
      "widgetLayout" -> return NlPropertyType.LAYOUT
      "width" -> return NlPropertyType.DIMENSION
      "windowAnimationStyle" -> return NlPropertyType.ID
      "windowIsFloating" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "windowIsTranslucent" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "windowNoDisplay" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "windowSoftInputMode" -> return NlPropertyType.INTEGER
      "windowSwipeToDismiss" -> return NlPropertyType.THREE_STATE_BOOLEAN
      "xlargeScreens" -> return NlPropertyType.INTEGER
      "zAdjustment" -> return NlPropertyType.INTEGER
      else -> return NlPropertyType.UNKNOWN
    }
  }
}

