java_import(
    name = "commons-io-2.4",
    jars = ["commons-io-2.4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "juniversalchardet-1.0.3",
    jars = ["juniversalchardet-1.0.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "antlr4-runtime-4.5.3",
    jars = ["antlr4-runtime-4.5.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "asm-5.0.3",
    jars = ["asm-5.0.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "asm-analysis-5.0.3",
    jars = ["asm-analysis-5.0.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "asm-tree-5.0.3",
    jars = ["asm-tree-5.0.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jarutils",
    jars = ["jarutils.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jsr305-1.3.9",
    jars = ["jsr305-1.3.9.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "spantable",
    jars = ["spantable.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jgraphx-3.4.0.1",
    jars = ["jgraphx-3.4.0.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all",
    jars = ["jogl-all.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all-natives-linux-amd64",
    jars = ["jogl-all-natives-linux-amd64.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all-natives-linux-i586",
    jars = ["jogl-all-natives-linux-i586.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all-natives-macosx-universal",
    jars = ["jogl-all-natives-macosx-universal.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all-natives-windows-amd64",
    jars = ["jogl-all-natives-windows-amd64.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jogl-all-natives-windows-i586",
    jars = ["jogl-all-natives-windows-i586.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt",
    jars = ["gluegen-rt.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt-natives-linux-amd64",
    jars = ["gluegen-rt-natives-linux-amd64.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt-natives-linux-i586",
    jars = ["gluegen-rt-natives-linux-i586.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt-natives-macosx-universal",
    jars = ["gluegen-rt-natives-macosx-universal.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt-natives-windows-amd64",
    jars = ["gluegen-rt-natives-windows-amd64.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gluegen-rt-natives-windows-i586",
    jars = ["gluegen-rt-natives-windows-i586.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "libwebp",
    jars = ["libwebp.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "dexlib2-2.0.8-dev",
    jars = ["dexlib2-2.0.8-dev.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "dexlib2-util-2.0.8-dev",
    jars = ["dexlib2-util-2.0.8-dev.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
