load("//tools/base/bazel:proto.bzl", "studio_java_proto_library")

studio_java_proto_library(
    name = "gemini_java_proto",
    srcs = glob(["**/gemini/*.proto"]),
    visibility = ["//visibility:public"],
)
