load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.preview-fast-compile",
    srcs = ["src"],
    iml_files = ["intellij.android.preview-fast-compile.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "@intellij//:intellij-sdk",
        "//tools/base/environment-services:studio.intellij.android.environment-services[module]",
    ],
)
