syntax = "proto3";

package google.play.publishingapi.v3;

option java_package = "com.google.play.publishingapi.v3";
option java_multiple_files = true;
option java_outer_classname = "DevelopersServiceProto";

// Service for developers.
service DevelopersService {
  // Returns the list of all developers.
  rpc ListDevelopers(ListDevelopersRequest) returns (ListDevelopersResponse) {
  }
}

// Representation of a developer.
message Developer {
  // The developer id.
  int64 developer_id = 1;

  // The  business name of the developer.
  string business_name = 2;
}

// Request for listing developer.
message ListDevelopersRequest {}

// Response listing all developers.
message ListDevelopersResponse {
  // List of developers.
  repeated Developer developers = 1;
}