/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.gradle.service.notification

import com.android.tools.idea.gradle.project.build.output.JavaLanguageLevelDeprecationOutputParser
import com.intellij.openapi.externalSystem.model.ProjectSystemId
import com.intellij.openapi.externalSystem.service.notification.ExternalSystemNotificationExtension
import org.jetbrains.plugins.gradle.util.GradleConstants

/**
 * This class is added to implement [isInternalError] for failures that we want to attribute directly to the failed tasks.
 *
 * This class is added to suppress top-level failures generated from build exceptions that instead should be
 * attributed to failed tasks. This filter stops exception from being converted to the Failure object and shown as a build error
 * on the top level in Build Output.
 *
 * Examples of such failures generated by AGP:
 *  - "Java compiler version 7 has removed support for compiling with source/target version 21." error.
 */
class AGPMessagesNotificationExtension: ExternalSystemNotificationExtension {

  override fun getTargetExternalSystemId(): ProjectSystemId = GradleConstants.SYSTEM_ID

  override fun isInternalError(error: Throwable): Boolean {
    val firstLine = error.message?.lineSequence()?.firstOrNull()
    return firstLine != null && JavaLanguageLevelDeprecationOutputParser.javaVersionRemovedPattern.matcher(firstLine).matches()
  }
}