cc_library(
    name = "cc",
    srcs = ["TestClass.cc"],
    hdrs = ["TestClass.h"],
    copts = ["-w"],
    visibility = ["//tools/adt/idea/aswb/querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
)
