java_library(
    name = "externaldep",
    srcs = ["TestClassExternalDep.java"],
    visibility = ["//tools/adt/idea/aswb/querysync/javatests/com/google/idea/blaze/qsync/testdata:__subpackages__"],
    deps = ["@maven//:com.google.guava.guava"],
)
