workspace(name = "aswb_test_projects")

# Temporarily needed as rules_jvm_external doe snot yet support rules_android via MODULE.
load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()
