load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.completion",
    srcs = ["src"],
    iml_files = ["intellij.android.completion.iml"],
    visibility = ["//visibility:public"],
    deps = ["@intellij//:intellij-sdk"],
)
