/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable lawtor agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.idea.testartifacts.instrumented.testsuite.view

enum class ScreenshotViewType(val displayText: String) {
  /** Displays all three images (New, Diff, and Reference) in a side-by-side view. */
  ALL("All"),
  /** Displays only the new image generated by the test run. */
  NEW("New"),
  /** Displays the difference between the new and reference images. */
  DIFF("Diff"),
  /** Displays the original reference (or "golden") image. */
  REFERENCE("Reference")
}
