load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//ijar_analysis_suppressing:__subpackages__"])

java_library(
    name = "project",
    srcs = ["java/com/example/project/Class1.java"],
    deps = [
        "//ijar_analysis_suppressing/external",
    ],
)
