filegroup(
    name = "testData",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "simpleApplication",
    srcs = glob(["projects/simpleApplication/**"]),
    visibility = ["//visibility:public"],
)
