# managed by go/iml_to_build
java_import(
    name = "libwebp",
    jars = ["libwebp.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.libwebp",
    jars = ["libwebp.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)
