# managed by go/iml_to_build
java_import(
    name = "truth",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:truth_files",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:truth_files",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "javax-inject",
    jars = ["//prebuilts/tools/common/m2/repository/javax/inject/javax.inject/1:javax-inject_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "equalsverifier",
    jars = ["//prebuilts/tools/common/m2/repository/nl/jqno/equalsverifier/equalsverifier/3.4.1:equalsverifier_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "mockito",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/mockito/mockito-core/3.4.6:mockito_files",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy/1.10.13:mockito_files",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy-agent/1.10.13:mockito_files",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "compile-testing",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/testing/compile/compile-testing/0.16:compile-testing_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jimfs",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/jimfs/jimfs/1.1:jimfs_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "dexlib2",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/smali/dexlib2/2.2.4:dexlib2_files",
        "//prebuilts/tools/common/m2/repository/org/smali/util/2.2.4:dexlib2_files",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "truth-java8-extension",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/truth/extensions/truth-java8-extension/0.42:truth-java8-extension_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "studio-grpc",
    jars = ["//tools/base/bazel:studio-grpc.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "studio-proto",
    jars = ["//tools/base/bazel:studio-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "kxml2",
    jars = ["//prebuilts/tools/common/m2/repository/net/sf/kxml/kxml2/2.3.0:kxml2_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "easymock",
    jars = ["//prebuilts/tools/common/m2/repository/org/easymock/easymock/4.0.2:easymock_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "libam-instrumentation-data-proto",
    jars = ["//tools/base/ddmlib:libam-instrumentation-data-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "aapt-proto",
    jars = ["//prebuilts/tools/common/m2/repository/com/android/tools/build/aapt2-proto/0.3.1:aapt-proto_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "studio-analytics-proto",
    jars = ["//tools/analytics-library/protos/src/main/proto:libstudio.proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "aia-proto",
    jars = ["//tools/base/sdk-common/aia-manifest-jar-generator:proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "sqlite",
    jars = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.34.0:sqlite_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "baksmali",
    jars = ["//prebuilts/tools/common/m2/repository/org/smali/baksmali/2.2.4:baksmali_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "zxing-core",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/zxing/core/3.4.0:zxing-core_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "assertJ",
    jars = ["//prebuilts/tools/common/m2/repository/org/assertj/assertj-core/3.13.2:assertJ_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "transport-proto",
    jars = ["//tools/base/transport/proto:transport_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "emulator-proto",
    jars = ["//tools/base/emulator/proto:emulator_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "perfetto-proto",
    jars = ["//tools/base/profiler:perfetto-protos.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "sqlite-inspector-proto",
    jars = ["//prebuilts/tools/common/app-inspection/androidx/sqlite:sqlite_inspector_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "kotlinx-coroutines-guava",
    jars = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-guava/1.3.9:kotlinx-coroutines-guava_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "guava-testlib",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/guava/guava-testlib/25.1-jre:guava-testlib_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "tightvnc",
    jars = ["//prebuilts/tools/common/tightvnc:tightvnc_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "layoutinspector-skia-proto",
    jars = ["//tools/base/dynamic-layout-inspector/skia/proto:layout_inspector_skia_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "layoutinspector-view-proto",
    jars = ["//tools/base/dynamic-layout-inspector/agent/appinspection/proto:layout_inspector_view_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "layoutinspector-compose-proto",
    jars = ["//prebuilts/tools/common/app-inspection/androidx/compose/ui:layout_inspector_compose_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "android-test-plugin-host-device-info-proto",
    jars = ["//tools/base/utp/android-test-plugin-host-device-info-proto:libstudio.android-test-plugin-host-device-info-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "asm-tools",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/ow2/asm/asm-analysis/7.0:asm-tools_files",
        "//prebuilts/tools/common/m2/repository/org/ow2/asm/asm-tree/7.0:asm-tools_files",
        "//prebuilts/tools/common/m2/repository/org/ow2/asm/asm/7.0:asm-tools_files",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "network_inspector_java_proto",
    jars = ["//tools/base/app-inspection/inspectors/network:network_inspector_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "layoutlib",
    jars = ["//prebuilts/studio/layoutlib/data:layoutlib_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "libapp-processes-proto",
    jars = ["//tools/base/ddmlib:libapp-processes-proto.jar"],
    visibility = ["//visibility:public"],
)
