# managed by go/iml_to_build [unb]
java_import(
    name = "unb.kotlin-stdlib-jdk8",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.0:unb.kotlin-stdlib-jdk8_files",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.0:unb.kotlin-stdlib-jdk8_files",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.0:unb.kotlin-stdlib-jdk8_files",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.0:unb.kotlin-stdlib-jdk8_files",
    ],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.truth",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:unb.truth_files",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:unb.truth_files",
    ],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.Guava",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/com/google/guava/guava/28.2-jre:unb.Guava_files",
        "//prebuilts/tools/common/m2/repository/com/google/guava/failureaccess/1.0.1:unb.Guava_files",
        "//prebuilts/tools/common/m2/repository/com/google/j2objc/j2objc-annotations/1.3:unb.Guava_files",
    ],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.javax-inject",
    jars = ["//prebuilts/tools/common/m2/repository/javax/inject/javax.inject/1:unb.javax-inject_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.equalsverifier",
    jars = ["//prebuilts/tools/common/m2/repository/nl/jqno/equalsverifier/equalsverifier/3.4.1:unb.equalsverifier_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.mockito",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/mockito/mockito-core/3.0.0:unb.mockito_files",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy/1.9.10:unb.mockito_files",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy-agent/1.9.10:unb.mockito_files",
    ],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.compile-testing",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/testing/compile/compile-testing/0.16:unb.compile-testing_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.jimfs",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/jimfs/jimfs/1.1:unb.jimfs_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.studio-grpc",
    jars = ["//tools/base/bazel:studio-grpc.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.studio-proto",
    jars = ["//tools/base/bazel:studio-proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.dexlib2",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/m2/repository/org/smali/dexlib2/2.2.4:unb.dexlib2_files",
        "//prebuilts/tools/common/m2/repository/org/smali/util/2.2.4:unb.dexlib2_files",
    ],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.asm-tools",
    jars = ["//tools/adt/idea/android/lib:unb.asm-tools_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.truth-java8-extension",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/truth/extensions/truth-java8-extension/0.42:unb.truth-java8-extension_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.kxml2",
    jars = ["//prebuilts/tools/common/m2/repository/net/sf/kxml/kxml2/2.3.0:unb.kxml2_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.easymock",
    jars = ["//prebuilts/tools/common/m2/repository/org/easymock/easymock/4.0.2:unb.easymock_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.protobuf",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.5.1:unb.protobuf_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.libam-instrumentation-data-proto",
    jars = ["//tools/base/ddmlib:libam-instrumentation-data-proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.sqlite",
    jars = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.21.0.1:unb.sqlite_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.aapt-proto",
    jars = ["//prebuilts/tools/common/m2/repository/com/android/tools/build/aapt2-proto/0.3.1:unb.aapt-proto_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.studio-analytics-proto",
    jars = ["//tools/analytics-library/protos/src/main/proto:libstudio.proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.aia-proto",
    jars = ["//tools/base/sdk-common/aia-manifest-jar-generator:proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.baksmali",
    jars = ["//prebuilts/tools/common/m2/repository/org/smali/baksmali/2.2.4:unb.baksmali_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.zxing-core",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/zxing/core/3.4.0:unb.zxing-core_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.transport-proto",
    jars = ["//tools/base/transport/proto:transport_java_proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.emulator-proto",
    jars = ["//tools/base/emulator/proto:emulator_java_proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.perfetto-proto",
    jars = ["//tools/base/profiler:perfetto-protos.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.sqlite-inspector-proto",
    jars = ["//prebuilts/tools/common/app-inspection/androidx/sqlite:sqlite_inspector_proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.kotlinx-coroutines-guava",
    jars = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-guava/1.2.1:unb.kotlinx-coroutines-guava_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.layoutinspector-proto",
    jars = ["//tools/base/dynamic-layout-inspector/proto:layout_inspector_java_proto.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.guava-testlib",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/guava/guava-testlib/25.1-jre:unb.guava-testlib_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.auto-value-annotations",
    jars = ["//prebuilts/tools/common/m2/repository/com/google/auto/value/auto-value-annotations/1.6.2:unb.auto-value-annotations_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.tightvnc",
    jars = ["//prebuilts/tools/common/tightvnc:unb.tightvnc_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.assertJ",
    jars = ["//prebuilts/tools/common/m2/repository/org/assertj/assertj-core/3.13.2:unb.assertJ_files"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)
