load("//tools/base/bazel:jvm_import.bzl", "jvm_import")

# managed by go/iml_to_build
jvm_import(
    name = "truth",
    # do not sort: must match IML order
    jars = ["//prebuilts/tools/common/m2:truth_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "javax-inject",
    jars = ["//prebuilts/tools/common/m2:javax-inject_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "equalsverifier",
    jars = ["//prebuilts/tools/common/m2:equalsverifier_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "mockito",
    # do not sort: must match IML order
    jars = ["//prebuilts/tools/common/m2:mockito_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "compile-testing",
    jars = ["//prebuilts/tools/common/m2:compile-testing_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "HdrHistogram",
    jars = ["//prebuilts/tools/common/m2:HdrHistogram_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "jimfs",
    jars = ["//prebuilts/tools/common/m2:jimfs_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "dexlib2",
    # do not sort: must match IML order
    jars = ["//prebuilts/tools/common/m2:dexlib2_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "truth-java8-extension",
    jars = ["//prebuilts/tools/common/m2:truth-java8-extension_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "studio-grpc",
    jars = ["//tools/base/bazel:studio-grpc.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "studio-proto",
    jars = ["//tools/base/bazel:studio-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "kxml2",
    jars = ["//prebuilts/tools/common/m2:kxml2_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "easymock",
    jars = ["//prebuilts/tools/common/m2:easymock_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "libam-instrumentation-data-proto",
    jars = ["//tools/base/ddmlib:libam-instrumentation-data-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "aapt-proto",
    jars = ["//prebuilts/tools/common/m2:aapt-proto_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "studio-analytics-proto",
    jars = ["//tools/analytics-library/protos/src/main/proto:libstudio.proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "aia-proto",
    jars = ["//tools/base/sdk-common/aia-manifest-jar-generator:proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "sqlite",
    jars = ["//prebuilts/tools/common/m2:sqlite_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "baksmali",
    jars = ["//prebuilts/tools/common/m2:baksmali_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "zxing-core",
    jars = ["//prebuilts/tools/common/m2:zxing-core_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "transport-proto",
    jars = ["//tools/base/transport/proto:transport_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "emulator-proto",
    jars = ["//tools/base/emulator/proto:emulator_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "perfetto-proto",
    jars = ["//tools/base/profiler:perfetto-protos.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "sqlite-inspector-proto",
    jars = ["//prebuilts/tools/common/app-inspection/androidx/sqlite:sqlite_inspector_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "kotlinx-coroutines-guava",
    jars = ["//prebuilts/tools/common/m2:kotlinx-coroutines-guava_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "guava-testlib",
    jars = ["//prebuilts/tools/common/m2:guava-testlib_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "tightvnc",
    jars = ["//prebuilts/tools/common/tightvnc:tightvnc_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "android-test-plugin-host-device-info-proto",
    jars = ["//tools/base/utp/android-test-plugin-host-device-info-proto:libstudio.android-test-plugin-host-device-info-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "asm-tools",
    # do not sort: must match IML order
    jars = ["//prebuilts/tools/common/m2:asm-tools_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "network_inspector_java_proto",
    jars = ["//tools/base/app-inspection/inspectors/network:network_inspector_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "layoutlib",
    jars = ["//prebuilts/studio/layoutlib/data:layoutlib_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "libapp-processes-proto",
    jars = ["//tools/base/ddmlib:libapp-processes-proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "layoutinspector-view-proto",
    # do not sort: must match IML order
    jars = [
        "//prebuilts/tools/common/app-inspection/androidx/compose/ui:layout_inspector_compose_java_proto.jar",
        "//tools/base/dynamic-layout-inspector/agent/appinspection/proto:layout_inspector_view_java_proto.jar",
        "//tools/adt/idea/layout-inspector/src/proto:layout_inspector_snapshot_java_proto.jar",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "layoutinspector-skia-proto",
    jars = ["//tools/base/dynamic-layout-inspector/skia/proto:layout_inspector_skia_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "ffmpeg",
    jars = ["//prebuilts/tools/common/m2:ffmpeg_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "ffmpeg-platform",
    jars = ["//prebuilts/tools/common/m2:ffmpeg-platform_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "kotlin-test",
    jars = ["//prebuilts/tools/common/m2:kotlin-test_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "jetbrains.kotlinx.coroutines.test",
    jars = ["//prebuilts/tools/common/m2:jetbrains.kotlinx.coroutines.test_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "firebase_java_proto",
    jars = ["//tools/vendor/google/firebase/src/proto:firebase_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "utp-core-proto-jarjar",
    # do not sort: must match IML order
    jars = ["//tools/base/bazel:utp-core-proto-jarjar.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "directaccess_client_proto",
    jars = ["//tools/vendor/google/directaccess-client/proto:ftl_client_java_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "adb_proxy_proto",
    jars = ["//tools/base/adb-proxy/proto:adb_proxy_studio_proto.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "gson",
    jars = ["//prebuilts/tools/common/m2:gson_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "oauth2",
    jars = ["//prebuilts/tools/common/m2:oauth2_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "google-dexlib2",
    jars = ["//prebuilts/tools/common/m2:google-dexlib2_files"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
jvm_import(
    name = "google-baksmali",
    jars = ["//prebuilts/tools/common/m2:google-baksmali_files"],
    visibility = ["//visibility:public"],
)
