plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'template.test.in'
    compileSdk {
        version = release(35)
    }

    defaultConfig {
        applicationId "template.test.in"
        minSdk 30
        targetSdk 35
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    implementation platform(libs.compose.bom)
    implementation libs.activity.compose
    implementation libs.compose.foundation
    implementation libs.compose.material3
    implementation libs.compose.ui.tooling
    implementation libs.core.splashscreen
    implementation libs.guava
    implementation libs.play.services.wearable
    implementation libs.protolayout
    implementation libs.protolayout.material3
    implementation libs.tiles
    implementation libs.tiles.tooling.preview
    implementation libs.ui
    implementation libs.ui.graphics
    implementation libs.ui.tooling.preview
    implementation libs.watchface.complications.data.source.ktx
    implementation libs.wear.tooling.preview
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.ui.test.junit4
    debugImplementation libs.tiles.renderer
    debugImplementation libs.tiles.tooling
    debugImplementation libs.ui.test.manifest
    debugImplementation libs.ui.tooling
}