load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.bleak-config",
    iml_files = ["intellij.android.bleak-config.iml"],
    test_srcs = ["testSrc"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/adt/idea/bleak:intellij.android.bleak[module]",
        "@intellij//:intellij-sdk",
        "@intellij//:com.intellij.java",
    ],
)
