{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "lib",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-Beta"
          }
        }
      ],
      "files": [
        {
          "name": "lib-3.0.aar",
          "url": "lib-3.0.aar",
          "size": 1630,
          "sha512": "8dbd3282d8253cba14e5afbcd356c3b8e877829d8221f2a3a959584c8169d4b499d303daee90cc4ef7d5325471bda3edfd4b1ed842674a7f4f792cd42500a411",
          "sha256": "0bc8c87764422e43ce52e071d69a5d7dae107236e56d4d8bc4a94149e3389c76",
          "sha1": "800d1ca86d58083b55568cd644a74c3d019f5a72",
          "md5": "db4b70b94ea43db23a2332b2abff4241"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-Beta"
          }
        }
      ],
      "files": [
        {
          "name": "lib-3.0.aar",
          "url": "lib-3.0.aar",
          "size": 1630,
          "sha512": "8dbd3282d8253cba14e5afbcd356c3b8e877829d8221f2a3a959584c8169d4b499d303daee90cc4ef7d5325471bda3edfd4b1ed842674a7f4f792cd42500a411",
          "sha256": "0bc8c87764422e43ce52e071d69a5d7dae107236e56d4d8bc4a94149e3389c76",
          "sha1": "800d1ca86d58083b55568cd644a74c3d019f5a72",
          "md5": "db4b70b94ea43db23a2332b2abff4241"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-3.0-sources.jar",
          "url": "lib-3.0-sources.jar",
          "size": 477,
          "sha512": "e286bf226ac25e4be2c07bbd5e94aac0fc8f76dca94385de8dae0837607004df50584af42228622bc87aff8e0f4361aeb14f733782b393514197f7c25d8c454a",
          "sha256": "f003f3bcb0bdad83c471997e30da1f3b0c0921c31a8bab64749a0193977300f3",
          "sha1": "101b594578582916cdddc5244908b676163d2e59",
          "md5": "217d0ef64b3ab27df1f35fdcd9be474b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-3.0-javadoc.jar",
          "url": "lib-3.0-javadoc.jar",
          "size": 259680,
          "sha512": "cf42f8fd278d4430c0a35afc5a3af9b243a77d1174d8f6aae71b7a22077b660a215081df573240da41bdfbf20509f2f63792414dc1c76ff8ee07ac1f4ae17f56",
          "sha256": "aa7125705d28a933b01eb4232c8972be4d94116bf84edb3721869bd53b213f97",
          "sha1": "9f4ddfe1e2cea91ebe357abfad3ec6dd91a9bb0a",
          "md5": "6eff76fae3d4a40fbebd8fd7c52b0e2b"
        }
      ]
    },
    {
      "name": "samplessources",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "samplessources"
      },
      "files": [
        {
          "name": "lib-3.0-samplesources.jar",
          "url": "lib-3.0-samplesources.jar",
          "size": 706,
          "sha512": "df874a3b57e78291fa7832028795d33617a08f8e4cf2607aa4bb704ee68ae67542d780f4d28da50a53813f823d1a4425f0c862783e52f6779bad13ccc89b864d",
          "sha256": "44b980f2f33d2303a035818d8c120a4ac180d62786566094482a6fb837b89bf8",
          "sha1": "83d14763d328fb33d717cd1d5b20487652a5c191",
          "md5": "741c40832492c371c300f013c3bf2f60"
        }
      ]
    }
  ]
}
