load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.profilers.atrace",
    # do not sort: must match IML order
    srcs = [
        "src/core/common/src/main/kotlin",
        "src/core/model/src/main/kotlin",
    ],
    iml_files = ["intellij.android.profilers.atrace.iml"],
    lint_baseline = "//tools/base/lint:studio-checks/empty_baseline.xml",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:kotlin-stdlib-jdk8",
        "//tools/idea/.idea/libraries:kotlin-reflect",
    ],
)

# managed by go/iml_to_build [unb]
iml_module(
    name = "intellij.android.profilers.atrace",
    # do not sort: must match IML order
    srcs = [
        "src/core/common/src/main/kotlin",
        "src/core/model/src/main/kotlin",
    ],
    iml_files = ["intellij.android.profilers.atrace.iml"],
    lint_baseline = "//tools/base/lint:studio-checks/empty_baseline.xml",
    project = "unb",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/studio/intellij-sdk:studio-sdk",
        "//tools/adt/idea/.idea/libraries:unb.kotlin-stdlib-jdk8",
    ],
)
