load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.inspectors-common.api",
    iml_files = ["intellij.android.inspectors-common.api.iml"],
    visibility = ["//visibility:public"],
)
