/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_tools_memory_usage_LightweightHeapTraverse */

#ifndef _Included_com_android_tools_memory_usage_LightweightHeapTraverse
#define _Included_com_android_tools_memory_usage_LightweightHeapTraverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_tools_memory_usage_LightweightHeapTraverse
 * Method:    collectReport
 */
JNIEXPORT jobject JNICALL Java_com_android_tools_memory_usage_LightweightHeapTraverse_collectReport
  (JNIEnv *, jclass, jboolean collectHeapObjectInfo,
                     jboolean collectReachableObjectsInfo,
                     jboolean collectStrongReferencedObjectsInfo);

#ifdef __cplusplus
}
#endif
#endif
