licenses(["notice"])

java_library(
    name = "exception",
    srcs = glob(["*.java"]),
    visibility = [
        "//tools/adt/idea/aswb/base:__subpackages__",
        "//tools/adt/idea/aswb/shared:__subpackages__",
    ],
)
