#Represents the version of 'org.gradle.toolchains.foojay-resolver-convention' which was
#used to generate the different 'gradle-daemon-jvm-X.properties' template files.
#Fri Oct 24 12:04:46 UTC 2025
foojayPluginVersion=1.0.0
