package(default_visibility = ["//tools/adt/idea/emulator/integration/event-logger:__pkg__"])

android_library(
    name = "event_logging_activity",
    srcs = ["EventLoggingActivity.java"],
    tags = ["no_windows"],
)
