/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service.vertex;

import org.jetbrains.annotations.NotNull;

import com.android.tools.rpclib.binary.*;
import com.android.tools.rpclib.schema.*;
import com.android.tools.idea.editors.gfxtrace.service.vertex.VertexProtos.SemanticType;

import java.io.IOException;

public final class Semantic implements BinaryObject {
  //<<<Start:Java.ClassBody:1>>>
  private SemanticType myType;
  private byte myIndex;

  // Constructs a default-initialized {@link Semantic}.
  public Semantic() {}


  public SemanticType getType() {
    return myType;
  }

  public Semantic setType(SemanticType v) {
    myType = v;
    return this;
  }

  public byte getIndex() {
    return myIndex;
  }

  public Semantic setIndex(byte v) {
    myIndex = v;
    return this;
  }

  @Override @NotNull
  public BinaryClass klass() { return Klass.INSTANCE; }


  private static final Entity ENTITY = new Entity("vertex", "Semantic", "", "");

  static {
    ENTITY.setFields(new Field[]{
      new Field("Type", new Primitive("SemanticType", Method.Int32)),
      new Field("Index", new Primitive("uint8", Method.Uint8)),
    });
    Namespace.register(Klass.INSTANCE);
  }
  public static void register() {}
  //<<<End:Java.ClassBody:1>>>
  public enum Klass implements BinaryClass {
    //<<<Start:Java.KlassBody:2>>>
    INSTANCE;

    @Override @NotNull
    public Entity entity() { return ENTITY; }

    @Override @NotNull
    public BinaryObject create() { return new Semantic(); }

    @Override
    public void encode(@NotNull Encoder e, BinaryObject obj) throws IOException {
      Semantic o = (Semantic)obj;
      e.int32(o.myType.getNumber());
      e.uint8(o.myIndex);
    }

    @Override
    public void decode(@NotNull Decoder d, BinaryObject obj) throws IOException {
      Semantic o = (Semantic)obj;
      o.myType = SemanticType.valueOf(d.int32());
      o.myIndex = d.uint8();
    }
    //<<<End:Java.KlassBody:2>>>
  }
}
