load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.adddevicedialog.tests",
    iml_files = ["intellij.android.adddevicedialog.tests.iml"],
    test_srcs = ["src"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/studio/intellij-sdk:studio-sdk",
        "//tools/adt/idea/intellij.android.adddevicedialog[module, test]",
    ],
)
