load("//tools/base/bazel:proto.bzl", "android_java_proto_library")

android_java_proto_library(
    name = "build-analysis-results-proto",
    srcs = glob(["**/*.proto"]),
    visibility = ["//visibility:public"],
)
