edition = "2024";

import option "google/protobuf/java_features.proto";

package proto1_project;

option java_package = "com.example.lib";

message LibMessageEdition2024DisableMultiFile {
  option features.(pb.java).nest_in_file_class = YES;
  string message = 1;
}

message LibMessageEdition2024EnableMultiFile {
  string message = 1;

  enum LibEnum {
    DEFAULT = 0;
    VALUE_A = 1;
    VALUE_B = 2;
  }
  LibEnum lib_enum = 2;

  repeated string repeated_strings = 3;

  oneof choice {
    string choice_a = 4;
    int32 choice_b = 5;
  }

  message NestedMessage {
    string nested_content = 1;
  }
  NestedMessage nested_message = 6;
  repeated NestedMessage repeated_nested_messages = 7;
}
