/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service;

import com.android.tools.idea.editors.gfxtrace.service.path.AtomPath;
import com.android.tools.idea.editors.gfxtrace.service.path.DevicePath;
import com.android.tools.rpclib.binary.*;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;

final class CallGetFramebufferDepth implements BinaryObject {
  //<<<Start:Java.ClassBody:1>>>
  private DevicePath myDevice;
  private AtomPath myAfter;

  // Constructs a default-initialized {@link CallGetFramebufferDepth}.
  public CallGetFramebufferDepth() {}


  public DevicePath getDevice() {
    return myDevice;
  }

  public CallGetFramebufferDepth setDevice(DevicePath v) {
    myDevice = v;
    return this;
  }

  public AtomPath getAfter() {
    return myAfter;
  }

  public CallGetFramebufferDepth setAfter(AtomPath v) {
    myAfter = v;
    return this;
  }

  @Override @NotNull
  public BinaryClass klass() { return Klass.INSTANCE; }

  private static final byte[] IDBytes = {-106, 38, -72, 36, 57, 91, -60, 83, -44, -3, 13, -93, 84, -68, -6, 120, -81, -46, -10, -99, };
  public static final BinaryID ID = new BinaryID(IDBytes);

  static {
    Namespace.register(ID, Klass.INSTANCE);
  }
  public static void register() {}
  //<<<End:Java.ClassBody:1>>>
  public enum Klass implements BinaryClass {
    //<<<Start:Java.KlassBody:2>>>
    INSTANCE;

    @Override @NotNull
    public BinaryID id() { return ID; }

    @Override @NotNull
    public BinaryObject create() { return new CallGetFramebufferDepth(); }

    @Override
    public void encode(@NotNull Encoder e, BinaryObject obj) throws IOException {
      CallGetFramebufferDepth o = (CallGetFramebufferDepth)obj;
      e.object(o.myDevice);
      e.object(o.myAfter);
    }

    @Override
    public void decode(@NotNull Decoder d, BinaryObject obj) throws IOException {
      CallGetFramebufferDepth o = (CallGetFramebufferDepth)obj;
      o.myDevice = (DevicePath)d.object();
      o.myAfter = (AtomPath)d.object();
    }
    //<<<End:Java.KlassBody:2>>>
  }
}
