/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service;

import com.android.tools.idea.editors.gfxtrace.service.stringtable.StringTable;
import com.android.tools.rpclib.rpccore.RpcException;
import org.jetbrains.annotations.NotNull;

import com.android.tools.rpclib.binary.*;
import com.android.tools.rpclib.schema.*;
import com.android.tools.idea.editors.gfxtrace.service.msg.Msg;

import java.io.IOException;

public final class ErrInvalidArgument extends RpcException implements BinaryObject {
  //<<<Start:Java.ClassBody:1>>>
  private Msg myReason;

  // Constructs a default-initialized {@link ErrInvalidArgument}.
  public ErrInvalidArgument() {}


  public Msg getReason() {
    return myReason;
  }

  public ErrInvalidArgument setReason(Msg v) {
    myReason = v;
    return this;
  }

  @Override @NotNull
  public BinaryClass klass() { return Klass.INSTANCE; }


  private static final Entity ENTITY = new Entity("service", "ErrInvalidArgument", "", "");

  static {
    ENTITY.setFields(new Field[]{
      new Field("Reason", new Pointer(new Struct(Msg.Klass.INSTANCE.entity()))),
    });
    Namespace.register(Klass.INSTANCE);
  }
  public static void register() {}
  //<<<End:Java.ClassBody:1>>>

  @Override
  public String getMessage() {
    return myReason.getString();
  }

  public enum Klass implements BinaryClass {
    //<<<Start:Java.KlassBody:2>>>
    INSTANCE;

    @Override @NotNull
    public Entity entity() { return ENTITY; }

    @Override @NotNull
    public BinaryObject create() { return new ErrInvalidArgument(); }

    @Override
    public void encode(@NotNull Encoder e, BinaryObject obj) throws IOException {
      ErrInvalidArgument o = (ErrInvalidArgument)obj;
      e.object(o.myReason);
    }

    @Override
    public void decode(@NotNull Decoder d, BinaryObject obj) throws IOException {
      ErrInvalidArgument o = (ErrInvalidArgument)obj;
      o.myReason = (Msg)d.object();
    }
    //<<<End:Java.KlassBody:2>>>
  }
}
