/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service;

public final class Factory {
  public static void register() {
    com.android.tools.rpclib.rpccore.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.atom.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.gfxapi.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.image.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.memory.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.msg.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.path.Factory.register();
    com.android.tools.idea.editors.gfxtrace.service.stringtable.Factory.register();
    //<<<Start:Java.FactoryBody:2>>>
    AtomRangeTimer.register();
    AtomTimer.register();
    Capture.register();
    Device.register();
    ErrDataUnavailable.register();
    ErrInvalidArgument.register();
    ErrInvalidPath.register();
    MemoryInfo.register();
    RenderSettings.register();
    ReportItem.register();
    Report.register();
    ResourceInfo.register();
    Resources.register();
    TimingInfo.register();
    CallFollow.register();
    CallGet.register();
    CallGetAvailableStringTables.register();
    CallGetCaptures.register();
    CallGetDevices.register();
    CallGetFeatures.register();
    CallGetFramebufferColor.register();
    CallGetFramebufferDepth.register();
    CallGetSchema.register();
    CallGetStringTable.register();
    CallGetTimingInfo.register();
    CallImportCapture.register();
    CallLoadCapture.register();
    CallSet.register();
    ResultFollow.register();
    ResultGet.register();
    ResultGetAvailableStringTables.register();
    ResultGetCaptures.register();
    ResultGetDevices.register();
    ResultGetFeatures.register();
    ResultGetFramebufferColor.register();
    ResultGetFramebufferDepth.register();
    ResultGetSchema.register();
    ResultGetStringTable.register();
    ResultGetTimingInfo.register();
    ResultImportCapture.register();
    ResultLoadCapture.register();
    ResultSet.register();
    //<<<End:Java.FactoryBody:2>>>
  }
}
