/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.idea.editors.gfxtrace.service;

import com.android.tools.rpclib.binary.*;
import com.android.tools.rpclib.schema.Entity;
import com.android.tools.rpclib.schema.Field;
import com.android.tools.rpclib.schema.Slice;
import com.android.tools.rpclib.schema.Struct;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;

public final class ResourceBundles implements BinaryObject {
  //<<<Start:Java.ClassBody:1>>>
  private ResourceBundle[] myBundles;

  // Constructs a default-initialized {@link ResourceBundles}.
  public ResourceBundles() {}


  public ResourceBundle[] getBundles() {
    return myBundles;
  }

  public ResourceBundles setBundles(ResourceBundle[] v) {
    myBundles = v;
    return this;
  }

  @Override @NotNull
  public BinaryClass klass() { return Klass.INSTANCE; }


  private static final Entity ENTITY = new Entity("service", "ResourceBundles", "", "");

  static {
    ENTITY.setFields(new Field[]{
      new Field("Bundles", new Slice("", new Struct(ResourceBundle.Klass.INSTANCE.entity()))),
    });
    Namespace.register(Klass.INSTANCE);
  }
  public static void register() {}
  //<<<End:Java.ClassBody:1>>>
  public enum Klass implements BinaryClass {
    //<<<Start:Java.KlassBody:2>>>
    INSTANCE;

    @Override @NotNull
    public Entity entity() { return ENTITY; }

    @Override @NotNull
    public BinaryObject create() { return new ResourceBundles(); }

    @Override
    public void encode(@NotNull Encoder e, BinaryObject obj) throws IOException {
      ResourceBundles o = (ResourceBundles)obj;
      e.uint32(o.myBundles.length);
      for (int i = 0; i < o.myBundles.length; i++) {
        e.value(o.myBundles[i]);
      }
    }

    @Override
    public void decode(@NotNull Decoder d, BinaryObject obj) throws IOException {
      ResourceBundles o = (ResourceBundles)obj;
      o.myBundles = new ResourceBundle[d.uint32()];
      for (int i = 0; i <o.myBundles.length; i++) {
        o.myBundles[i] = new ResourceBundle();
        d.value(o.myBundles[i]);
      }
    }
    //<<<End:Java.KlassBody:2>>>
  }
}
