load(
    "//gensrcjars:gen_srcjar.bzl",
    "gen_srcjar",
)

package(
    default_visibility = ["//visibility:public"],
)

gen_srcjar(
    name = "jar2",
    src = "Jar2Class.java_",
    package_dir = "com/example/jar2",
)
