load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "sherpa-ui",
    srcs = ["src"],
    iml_files = ["sherpa-ui.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/sherpa:sherpa-solver[module]"],
)
