load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.app-inspection.inspector.ide",
    srcs = ["src"],
    iml_files = ["intellij.android.app-inspection.inspector.ide.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:kotlin-stdlib-jdk8"],
)
