load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.android.app-inspection.inspectors.livestore.view",
    srcs = ["src"],
    iml_files = ["intellij.android.app-inspection.inspectors.livestore.view.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:kotlin-stdlib-jdk8",
        "//tools/adt/idea/app-inspection/inspectors/livestore/model:intellij.android.app-inspection.inspectors.livestore.model[module]",
        "//tools/adt/idea/app-inspection/inspector/api:intellij.android.app-inspection.inspector.api[module]",
    ],
)
